import { SupportedLanguage, ExplosionGiftItem, ScrapbookPage, BoxOccasion, PaperStyle } from '../types';

export interface LanguagePresets {
  title: string;
  recipientNameDefault: string;
  senderNameDefault: string;
  occasionDefault: BoxOccasion;
  giftTagMessage: string;
  giftTagFrom: string;
  giftTagTo: string;
  reasonWhySpecial: string;
  customWishMessage: string;
  letterTitle: string;
  letterContent: string;
  letterSignature: string;
  paperStyle: PaperStyle;
  scrapbookPages: ScrapbookPage[];
  voiceTitle: string;
  cakeMessage: string;
  wishBannerText: string;
  wishSecretNote: string;
  treatName: string;
  treatDesc: string;
  insideJokeMessage: string;
  timeCapsuleTitle: string;
  timeCapsuleMessage: string;
  customItemName: string;
  customItemDesc: string;
  customItemTag: string;
  relationshipNotes: string[];
  explosionTitle: string;
  explosionSubtitle: string;
  explosionGifts: ExplosionGiftItem[];
  lastNoteTitle: string;
  lastNoteParchment: string;
  lastNoteSignature: string;
  passwordHint: string;
}

export const LANGUAGE_DEFAULTS: Record<SupportedLanguage, LanguagePresets> = {
  mr: {
    title: 'माझ्या प्रिय व्यक्तीसाठी — ४ वर्षांचे अतूट प्रेम व आठवणींचा खजिना ✨',
    recipientNameDefault: 'अनन्या',
    senderNameDefault: 'आर्यन',
    occasionDefault: 'anniversary',
    giftTagMessage: 'फक्त तुझ्यासाठी खास प्रेमाने सजवलेली आठवणींची पेटी. जेव्हा हसायचे असेल तेव्हा उघडून बघ.',
    giftTagFrom: 'फक्त तुझाच',
    giftTagTo: 'माझ्या लाडक्यासाठी',
    reasonWhySpecial: 'तू माझ्या आयुष्यात आल्यापासून प्रत्येक दिवस सोन्यासारखा सुंदर झाला आहे आणि प्रत्येक कठीण प्रसंगात तू नेहमी माझी खंबीर ढाल बनून उभी राहिलीस.',
    customWishMessage: 'तुझ्या चेहऱ्यावरील हे गोड हास्य असेच कायम राहो ❤️',
    letterTitle: 'माझ्या मनातील सर्वात खास व्यक्तीसाठी 💌',
    letterContent: `माझ्या लाडक्या,\n\nशब्दांत मांडता येणार नाही इतकं अथांग प्रेम मी तुझ्यावर करतो. जेव्हापासून तू माझ्या आयुष्यात आलीस, तेव्हापासून माझ्या जगाला एक नवा अर्थ मिळाला आहे. तुझ्या एका गोड हास्याने माझे सारे दुःख क्षणात दूर पळतात.\n\nतुझ्या सोबतीत घालवलेला प्रत्येक क्षण माझ्या आठवणींच्या डायरीत सुवर्ण अक्षरांनी कोरला गेला आहे. तू फक्त माझी जोडीदार नाहीस, तर माझ्या हृदयाची प्रत्येक धडकन आहेस.\n\nनेहमी अशीच हसत राहा आणि माझ्या सोबत राहा. आयुष्याच्या प्रत्येक वळणावर मी तुझा हात कधीच सोडणार नाही.`,
    letterSignature: '~ मनापासून फक्त तुझाच, आर्यन ❤️',
    paperStyle: 'rose_petal_pressed',
    scrapbookPages: [
      {
        id: 'page-1',
        title: 'कशी झाली सुरुवात',
        date: 'आपली पहिली अविस्मरणीय भेट',
        photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
        note: 'जेव्हा पहिल्यांदा आपले डोळे मिळाले, तेव्हा जणू संपूर्ण जग तिथेच थांबले होते.',
        stickers: ['✨', '☕', '❤️'],
        tapeColor: '#D4AF37',
      },
      {
        id: 'page-2',
        title: 'आपली गोड सफर',
        date: 'तो सुंदर पावसाळी वीकेंड',
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        note: 'खळखळून हसणे, एकत्र भिजणे आणि भविष्याची सुंदर स्वप्ने रंगवणे.',
        stickers: ['🌊', '🌅'],
        tapeColor: '#E8B4B8',
      },
    ],
    voiceTitle: 'तुझ्यासाठी एक खास आवाजाचा निरोप 🎙️',
    cakeMessage: 'लग्नाच्या वाढदिवसाच्या मनःपूर्वक शुभेच्छा अनन्या ✨',
    wishBannerText: 'एक गोड इच्छा व्यक्त करा! 🎂',
    wishSecretNote: 'आपल्या नात्यातील गोडवा, विश्वास आणि प्रेम वर्षानुवर्षे असेच बहरत राहो.',
    treatName: 'शाही बेल्जियन डार्क ट्रफल्स चॉकलेट 🍫',
    treatDesc: '७०% शुद्ध डार्क कोको आणि खमंग हेझलनटचे मखमली मिश्रण.',
    insideJokeMessage: '“पिझ्झावर अननस टाकणे म्हणजे मोठा गुन्हा आहे — आणि हे आपल्या दोघांनाही ठाऊक आहे!”',
    timeCapsuleTitle: 'आपल्या भविष्यातील स्वप्नांची तिजोरी ⏳',
    timeCapsuleMessage: 'आयुष्यात कितीही बदल झाले किंवा कितीही वर्षे लोटली तरी, माझे तुझ्यावरील प्रेम नेहमी असेच अढळ राहील.',
    customItemName: 'आपल्या पहिल्या रोडट्रिपची सुंदर आठवण 🚗',
    customItemDesc: 'डोंगरांच्या कुशीत मध्यरात्री केलेली सफर आणि एकत्र पाहिलेला सुंदर सूर्योदय.',
    customItemTag: 'अनमोल आठवण',
    relationshipNotes: [
      'आपण नेहमी जास्तीचे गार्लिक ब्रेड मागवतो आणि शेवटच्या तुकड्यासाठी भांडतो.',
      'पावसात मध्यरात्री गाडी चालवताना वाजलेले आपले आवडते गाणे.',
      'तू नेहमी माझे स्वेटर घालतेस कारण त्यात तुला घराचा सुगंध येतो.',
    ],
    explosionTitle: 'प्रेम आणि सरप्राईजचा महाधमाका (गिफ्ट ब्लास्ट) 💥',
    explosionSubtitle: 'खालील धडधडणाऱ्या बॉक्सवर टॅप करा आणि हवेत उडणाऱ्या भेटवस्तू पहा!',
    explosionGifts: [
      {
        id: 'exp-1',
        title: 'लाल मखमली गुलाबांचा गुच्छ 🌹',
        category: 'flower_bouquet',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        caption: 'कधीही न सुकणारी ५० ताजी गुलाबाची फुले, जी आपल्या अमर प्रेमाची साक्ष देतात.',
        tags: ['अमर प्रेम', 'सुगंधित फुले'],
        reactionEmoji: '🌹',
      },
      {
        id: 'exp-2',
        title: 'क्यूट टेडी बेअर 🧸',
        category: 'teddy_bear',
        imageUrl: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
        caption: 'मी जवळ नसताना तुला मिठी मारण्यासाठी आणि रात्रीच्या गप्पांसाठी एक गोड साथीदार.',
        tags: ['गोड मिठी', 'हृदयाचा साथी'],
        reactionEmoji: '🧸',
      },
      {
        id: 'exp-3',
        title: 'रॉयल बेल्जियन ट्रफल्स 🍫',
        category: 'chocolates',
        imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
        caption: 'गोड आठवणींसोबत जिभेवर विरघळणारे शाही डार्क चॉकलेट्स.',
        tags: ['शाही गोडवा', 'खास आनंद'],
        reactionEmoji: '🍫',
      },
    ],
    lastNoteTitle: 'शेवटचा गुप्त संदेश (The Last Whispering Note) 📜',
    lastNoteParchment: `आणि अशा प्रकारे, जेव्हा तू माझ्या या छोट्याशा विश्वाच्या तळाशी पोहोचशील, तेव्हा हे लक्षात ठेव की या पेटीत ठेवलेली प्रत्येक गोष्ट माझ्या तुझ्यावरील अथांग प्रेमाची फक्त एक छोटीशी झलक आहे.\n\nमाझ्या आयुष्याची वाट धरल्याबद्दल मनःपूर्वक धन्यवाद. जेव्हा जेव्हा जग कठीण वाटेल किंवा दिवस लांब वाटतील, तेव्हा या पेटीकडे ये, माझा आवाज ऐक, ही पाने वाच आणि लक्षात ठेव की तू नेहमी माझ्या आयुष्यातील सर्वात मोठा चमत्कार असशील.\n\nआज रात्री चेहऱ्यावर गोड हास्य ठेवून झोप.`,
    lastNoteSignature: '~ मनाच्या तळातून, फक्त तुझाच आर्यन ❤️',
    passwordHint: 'आपण वांद्रे येथे ज्या कॅफेमध्ये भेटलो होतो त्याचे नाव (लहान अक्षरे)',
  },
  hi: {
    title: 'मेरी प्यारी अनन्या के नाम — ४ सालों का अटूट प्यार और यादों का संदूक ✨',
    recipientNameDefault: 'अनन्या',
    senderNameDefault: 'आर्यन',
    occasionDefault: 'anniversary',
    giftTagMessage: 'सिर्फ तुम्हारे लिए प्यार से सजाया गया यादों का तोहफा। जब भी मुस्कुराने का मन करे, इसे खोल लेना।',
    giftTagFrom: 'तुम्हारा अपना',
    giftTagTo: 'मेरी जान के लिए',
    reasonWhySpecial: 'तुमने मेरी बेरंग जिंदगी को खुशियों के रंगों से भर दिया है और हर मुश्किल वक्त में हमेशा मेरा सबसे बड़ा सहारा बनी रही हो।',
    customWishMessage: 'तुम्हारी प्यारी सी मुस्कान हमेशा ऐसे ही चमकती रहे ❤️',
    letterTitle: 'मेरे दिल की सबसे अजीज दास्तान 💌',
    letterContent: `मेरी प्यारी जान,\n\nशब्दों में बयां करना मुश्किल है कि तुम मेरे लिए क्या मायने रखती हो। जब से तुम मेरी जिंदगी में आई हो, हर दिन किसी खूबसूरत त्योहार जैसा लगता है। तुम्हारी एक हंसी मेरे सारे गम भुला देती है।\n\nतुम्हारे साथ बिताया हर लम्हा मेरे दिल की तिजोरी में महफूज है। तुम सिर्फ मेरी हमसफर नहीं, बल्कि मेरी जिंदगी का सबसे अनमोल तोहफा हो।\n\nहमेशा ऐसे ही हंसती रहना। चाहे रास्ते कैसे भी हों, मेरा हाथ हमेशा तुम्हारे हाथ में रहेगा।`,
    letterSignature: '~ तहे दिल से, सिर्फ तुम्हारा आर्यन ❤️',
    paperStyle: 'rose_petal_pressed',
    scrapbookPages: [
      {
        id: 'page-1',
        title: 'शुरुआत की वो खूबसूरत शाम',
        date: 'हमारी पहली मुलाकात',
        photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
        note: 'जब पहली बार हमारी नजरें मिलीं, ऐसा लगा जैसे पूरी कायनात ठहर गई हो।',
        stickers: ['✨', '☕', '❤️'],
        tapeColor: '#D4AF37',
      },
      {
        id: 'page-2',
        title: 'हमारी प्यारी सी सैर',
        date: 'वो यादगार बारिश का वीकेंड',
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        note: 'खुलकर हंसना, बारिश में भीगना और साथ जीने-मरने के वादे।',
        stickers: ['🌊', '🌅'],
        tapeColor: '#E8B4B8',
      },
    ],
    voiceTitle: 'तुम्हारे लिए एक दिल से निकली आवाज 🎙️',
    cakeMessage: 'सालगिरह की ढेरों मुबारकबाद अनन्या ✨',
    wishBannerText: 'एक प्यारी सी दुआ मांगो! 🎂',
    wishSecretNote: 'हमारा प्यार और यह खूबसूरत रिश्ता वक्त के साथ और भी गहरा और मीठा होता जाए।',
    treatName: 'शाही बेल्जियन डार्क ट्रफल्स चॉकलेट्स 🍫',
    treatDesc: '७०% शुद्ध डार्क कोको और रोस्टेड हेज़लनट का जादुई स्वाद।',
    insideJokeMessage: '“पिज़्ज़ा पर अनानास डालना जुर्म है — और यह बात हम दोनों बखूबी जानते हैं!”',
    timeCapsuleTitle: 'हमारे आने वाले कल की खूबसूरत तिजोरी ⏳',
    timeCapsuleMessage: 'चाहे जिंदगी हमें किसी भी मोड़ पर ले जाए, मेरा प्यार तुम्हारे लिए हमेशा अटूट और ताजा रहेगा।',
    customItemName: 'हमारी पहली रोड ट्रिप की निशानी 🚗',
    customItemDesc: 'पहाड़ों की ठंडी हवाओं में आधी रात का सफर और साथ देखा हुआ पहला सूरज।',
    customItemTag: 'अनमोल याद',
    relationshipNotes: [
      'हम हमेशा एक्स्ट्रा गार्लिक ब्रेड मंगाते हैं और आखिरी टुकड़े पर लड़ते हैं।',
      'बारिश में गाड़ी चलाते हुए बजा हमारा सबसे पसंदीदा गाना।',
      'तुम हमेशा मेरा स्वेटर चुराती हो क्योंकि उसमें तुम्हें अपनेपन की खुशबू आती है।',
    ],
    explosionTitle: 'प्यार और सरप्राइज का महाधमाका (गिफ्ट ब्लास्ट) 💥',
    explosionSubtitle: 'नीचे कांपते हुए बॉक्स को छुएं और सारे तोहफे हवा में उड़ते देखें!',
    explosionGifts: [
      {
        id: 'exp-1',
        title: 'लाल मखमली गुलाबों का गुलदस्ता 🌹',
        category: 'flower_bouquet',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        caption: 'कभी न मुरझाने वाले ५० ताजे लाल गुलाब, जो हमारे अटूट प्यार की निशानी हैं।',
        tags: ['अमर प्यार', 'महकता गुलदस्ता'],
        reactionEmoji: '🌹',
      },
      {
        id: 'exp-2',
        title: 'क्यूट विंटेज टेडी बेअर 🧸',
        category: 'teddy_bear',
        imageUrl: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
        caption: 'जब मैं दूर रहूं, तो रात की बातों और गले लगाने के लिए तुम्हारा प्यारा साथी।',
        tags: ['मीठी झप्पी', 'हमसफर'],
        reactionEmoji: '🧸',
      },
      {
        id: 'exp-3',
        title: 'रॉयल बेल्जियन ट्रफल्स 🍫',
        category: 'chocolates',
        imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
        caption: 'हर बाइट में प्यार की मिठास घोलने वाली रिच डार्क चॉकलेट।',
        tags: ['शाही मिठास', 'दिल की दावत'],
        reactionEmoji: '🍫',
      },
    ],
    lastNoteTitle: 'आखिरी गुप्त खत (The Last Whispering Note) 📜',
    lastNoteParchment: `और आखिरकार, जब तुम इस संदूक की गहराइयों तक पहुंचोगी, तो याद रखना कि यहां रखी हर चीज तुम्हारे लिए मेरे असीम प्यार का बस एक छोटा सा हिस्सा है।\n\nमेरा हाथ थामने के लिए शुक्रिया। जब भी दुनिया भारी लगे या दिन मुश्किल हों, इस संदूक को खोलना, मेरी आवाज सुनना, इन पन्नों को पढ़ना और याद रखना कि तुम हमेशा मेरी जिंदगी का सबसे बड़ा चमत्कार रहोगी।\n\nआज रात चेहरे पर एक प्यारी सी मुस्कान लेकर सोना।`,
    lastNoteSignature: '~ हमेशा-हमेशा के लिए, सिर्फ तुम्हारा आर्यन ❤️',
    passwordHint: 'बांद्रा के उस कैफे का नाम जहां हम पहली बार मिले थे (छोटे अक्षरों में)',
  },
  en: {
    title: 'To My Dearest Ananya — 4 Years of Endless Love & Keepsake Vault ✨',
    recipientNameDefault: 'Ananya',
    senderNameDefault: 'Aryan',
    occasionDefault: 'anniversary',
    giftTagMessage: 'A treasure chest handcrafted for the woman who made my world soft and golden. Open when you are ready to smile.',
    giftTagFrom: 'Always Yours',
    giftTagTo: 'My Beloved',
    reasonWhySpecial: 'You make even the quietest ordinary moments feel magical, and you have stood by me through thick and thin.',
    customWishMessage: 'May your radiant smile forever brighten my universe ❤️',
    letterTitle: 'To the One Who Holds My Heart 💌',
    letterContent: `My Dearest,\n\nWords often fall short when I try to describe how endlessly you are cherished. Since the day you walked into my life, everything has taken on a softer, warmer glow. Your laughter is my favorite song, and your embrace is the only home I will ever need.\n\nEvery memory we have built together is etched in pure gold. You are not just my partner, you are my heart’s constant compass.\n\nStay just as radiant as you are today. Through every season and every storm, I promise to walk hand in hand with you forever.`,
    letterSignature: '~ With All My Soul, Aryan ❤️',
    paperStyle: 'rose_petal_pressed',
    scrapbookPages: [
      {
        id: 'page-1',
        title: 'How It All Began',
        date: 'Our First Encounter',
        photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
        note: 'The very first moment our eyes met, time stood completely still.',
        stickers: ['✨', '☕', '❤️'],
        tapeColor: '#D4AF37',
      },
      {
        id: 'page-2',
        title: 'Our Sweetest Adventure',
        date: 'That Unforgettable Weekend',
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        note: 'Laughing until our stomachs hurt and making promises for a beautiful tomorrow.',
        stickers: ['🌊', '🌅'],
        tapeColor: '#E8B4B8',
      },
    ],
    voiceTitle: 'A Spoken Whisper for You 🎙️',
    cakeMessage: 'Happy 4th Anniversary Ananya ✨',
    wishBannerText: 'Make a Wish My Love! 🎂',
    wishSecretNote: 'May our laughter always outlive the storms, and may every sunrise find us holding hands forever.',
    treatName: 'Artisanal Belgian Dark Truffles 🍫',
    treatDesc: 'Rich 70% dark cocoa dusted with roasted hazelnut praline.',
    insideJokeMessage: '“Pineapple on pizza is a crime against humanity — and we both know it!”',
    timeCapsuleTitle: 'Secret Future Milestone Vault ⏳',
    timeCapsuleMessage: 'No matter where life takes us, my love for you will always remain constant.',
    customItemName: 'Our First Roadtrip Souvenir 🚗',
    customItemDesc: 'Picked up during our wild midnight drive to the hills where we watched sunrise together.',
    customItemTag: 'Keepsake Souvenir',
    relationshipNotes: [
      'We always order extra garlic bread and fight over the last piece.',
      'Our song played in the car during that midnight drive in the rain.',
      'You always steal my sweaters because you say they smell like home.',
    ],
    explosionTitle: 'A Shower of Love & Surprises (Gift Blast) 💥',
    explosionSubtitle: 'Tap the vibrating box below to blast every treasure into the air!',
    explosionGifts: [
      {
        id: 'exp-1',
        title: 'Crimson Dutch Roses Bouquet 🌹',
        category: 'flower_bouquet',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        caption: '50 freshly bloomed velvety roses that never wither, symbolizing our eternal bond.',
        tags: ['Eternal Blooms', 'Fragrant Love'],
        reactionEmoji: '🌹',
      },
      {
        id: 'exp-2',
        title: 'Vintage Honey Plush Bear 🧸',
        category: 'teddy_bear',
        imageUrl: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
        caption: 'A warm cuddle buddy for midnight study sessions and movie marathons when I am away.',
        tags: ['Soft Hugs', 'Forever Warmth'],
        reactionEmoji: '🧸',
      },
      {
        id: 'exp-3',
        title: 'Belgian Truffle Gold Selection 🍫',
        category: 'chocolates',
        imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
        caption: 'Handcrafted luxury dark chocolates that melt on your tongue like sweet memories.',
        tags: ['Luxury Sweet', 'Heart Melting'],
        reactionEmoji: '🍫',
      },
    ],
    lastNoteTitle: 'The Last Whispering Note (आखिरी संदेश) 📜',
    lastNoteParchment: `And so, as you reach the bottom of this little universe I built for you, know that everything packed inside here is just a humble shadow of how endlessly you are cherished.\n\nThank you for choosing to walk by my side. Whenever the world gets too noisy or the days grow long, come back to this box, play my voice, read these pages, and remember that you will always be my greatest miracle.\n\nSleep with a smile tonight.`,
    lastNoteSignature: '~ With All My Heart, Aryan ❤️',
    passwordHint: 'The cafe in Bandra where we first met (lowercase, no spaces)',
  },
  gu: {
    title: 'મારી વહાલી અનન્યા માટે — ૪ વર્ષનો અતૂટ પ્રેમ અને યાદોનો ખજાનો ✨',
    recipientNameDefault: 'અનન્યા',
    senderNameDefault: 'આર્યન',
    occasionDefault: 'anniversary',
    giftTagMessage: 'ફક્ત તમારા માટે પ્રેમથી સજાવેલ યાદોની ભેટ. જ્યારે પણ હસવાનું મન થાય ત્યારે ખોલજો.',
    giftTagFrom: 'હંમેશા તમારો',
    giftTagTo: 'મારી વહાલી માટે',
    reasonWhySpecial: 'તમે મારા જીવનમાં આવ્યા પછી દરેક ક્ષણ સોના જેવી સુંદર બની ગઈ છે અને દરેક મુશ્કેલીમાં તમે હંમેશા મારો સાથ આપ્યો છે.',
    customWishMessage: 'તમારું આ સુંદર સ્મિત હંમેશા આમ જ ચમકતું રહે ❤️',
    letterTitle: 'મારા દિલની સૌથી ખાસ વ્યક્તિ માટે 💌',
    letterContent: `મારી વહાલી,\n\nશબ્દોમાં વર્ણવવું અશક્ય છે કે હું તમને કેટલો પ્રેમ કરું છું. જ્યારેથી તમે મારા જીવનમાં આવ્યા છો, મારું આખું વિશ્વ બદલાઈ ગયું છે. તમારું એક સ્મિત મારા બધા દુઃખ ભૂલાવી દે છે.\n\nતમારી સાથે વિતાવેલી દરેક પળ મારી યાદોની ડાયરીમાં સુવર્ણ અક્ષરે લખાયેલી છે. તમે ફક્ત મારી જીવનસાથી નથી, પણ મારા હૃદયનો ધબકારો છો.\n\nહંમેશા આમ જ હસતા રહો. દરેક રસ્તે મારો હાથ તમારા હાથમાં રહેશે.`,
    letterSignature: '~ દિલથી ફક્ત તમારો, આર્યન ❤️',
    paperStyle: 'rose_petal_pressed',
    scrapbookPages: [
      {
        id: 'page-1',
        title: 'શરૂઆતની એ સુંદર મુલાકાત',
        date: 'આપણી પહેલી મુલાકાત',
        photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
        note: 'જ્યારે પહેલીવાર આપણી નજર મળી, જાણે આખું વિશ્વ ત્યાં જ થંભી ગયું હતું.',
        stickers: ['✨', '☕', '❤️'],
        tapeColor: '#D4AF37',
      },
      {
        id: 'page-2',
        title: 'આપણી મીઠી સફર',
        date: 'તે યાદગાર વરસાદી વીકેન્ડ',
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        note: 'ખિલખિલાટ હસવું, વરસાદમાં પલળવું અને સુંદર ભવિષ્યના સપના જોવું.',
        stickers: ['🌊', '🌅'],
        tapeColor: '#E8B4B8',
      },
    ],
    voiceTitle: 'તમારા માટે ખાસ અવાજનો સંદેશ 🎙️',
    cakeMessage: 'લગ્ન વર્ષગાંઠની ખૂબ ખૂબ શુભેચ્છાઓ અનન્યા ✨',
    wishBannerText: 'એક મીઠી ઈચ્છા વ્યક્ત કરો! 🎂',
    wishSecretNote: 'આપણો પ્રેમ અને મીઠો સંબંધ સમય સાથે વધુ ગાઢ અને મજબૂત થતો રહે.',
    treatName: 'શાહી બેલ્જિયન ડાર્ક ટ્રફલ્સ 🍫',
    treatDesc: '૭૦% પ્યોર ડાર્ક કોકો અને હેઝલનટનું સ્વાદિષ્ટ મિશ્રણ.',
    insideJokeMessage: '“પીઝા પર અનાનસ મૂકવું એ ગુનો છે — અને આપણે બંને જાણીએ છીએ!”',
    timeCapsuleTitle: 'આપણા સુંદર ભવિષ્યની તિજોરી ⏳',
    timeCapsuleMessage: 'જીવન ગમે તે વળાંક પર લઈ જાય, મારો પ્રેમ હંમેશા અડગ રહેશે.',
    customItemName: 'આપણી પહેલી રોડટ્રીપની યાદગાર નિશાની 🚗',
    customItemDesc: 'પહાડોની વચ્ચે અડધી રાતની સફર અને સાથે જોયેલો સૂર્યોદય.',
    customItemTag: 'અનમોલ યાદ',
    relationshipNotes: [
      'આપણે હંમેશા એક્સ્ટ્રા ગાર્લિક બ્રેડ મંગાવીએ છીએ અને છેલ્લા ટુકડા માટે લડીએ છીએ.',
      'વરસાદમાં ગાડી ચલાવતી વખતે વાગેલું આપણું ફેવરિટ ગીત.',
      'તમે હંમેશા મારું સ્વેટર પહેરો છો કારણ કે તેમાં ઘર જેવી સુગંધ આવે છે.',
    ],
    explosionTitle: 'પ્રેમ અને સરપ્રાઈઝનો ધમાકો (ગિફ્ટ બ્લાસ્ટ) 💥',
    explosionSubtitle: 'નીચે આપેલા બોક્સ પર ટેપ કરો અને ઉડતી ભેટો જુઓ!',
    explosionGifts: [
      {
        id: 'exp-1',
        title: 'લાલ ગુલાબનો સુંદર ગુલદસ્તો 🌹',
        category: 'flower_bouquet',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        caption: 'ક્યારેય ન કરમાતા ૫૦ તાજા લાલ ગુલાબ.',
        tags: ['અમર પ્રેમ', 'સુગંધ'],
        reactionEmoji: '🌹',
      },
      {
        id: 'exp-2',
        title: 'ક્યૂટ ટેડી બેઅર 🧸',
        category: 'teddy_bear',
        imageUrl: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
        caption: 'જ્યારે હું દૂર હોઉં ત્યારે વહાલ કરવા માટે એક મીઠો દોસ્ત.',
        tags: ['મીઠી ભેટ', 'સાથી'],
        reactionEmoji: '🧸',
      },
      {
        id: 'exp-3',
        title: 'બેલ્જિયન ચોકલેટ્સ 🍫',
        category: 'chocolates',
        imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
        caption: 'જીભ પર પીગળી જતી શાહી ડાર્ક ચોકલેટ્સ.',
        tags: ['મીઠાશ', 'આનંદ'],
        reactionEmoji: '🍫',
      },
    ],
    lastNoteTitle: 'છેલ્લો પત્ર (The Last Whispering Note) 📜',
    lastNoteParchment: `અને છેલ્લે, જ્યારે તમે આ પેટીના તળિયે પહોંચશો, ત્યારે યાદ રાખજો કે આ બધું તમારા પ્રત્યેના મારા અસીમ પ્રેમનું નાનું પ્રતિબિંબ છે.\n\nમારો સાથ આપવા બદલ આભાર. જ્યારે પણ જીવન મુશ્કેલ લાગે, આ પેટી ખોલજો, મારો અવાજ સાંભળજો અને યાદ રાખજો કે તમે મારો સૌથી મોટો ચમત્કાર છો.\n\nઆજે રાત્રે મીઠા સ્મિત સાથે સૂઈ જજો.`,
    lastNoteSignature: '~ સદાય તમારો, આર્યન ❤️',
    passwordHint: 'બાંદ્રાનું કેફે જ્યાં આપણે પહેલીવાર મળ્યા હતા',
  },
  bn: {
    title: 'আমার প্রিয় অনন্যার জন্য — ৪ বছরের চিরন্তন ভালোবাসার উপহার ✨',
    recipientNameDefault: 'অনন্যা',
    senderNameDefault: 'আর্যন',
    occasionDefault: 'anniversary',
    giftTagMessage: 'শুধুমাত্র তোমার জন্য ভালোবাসায় সাজানো স্মৃতির উপহার। যখনই হাসতে ইচ্ছে করবে, খুলে দেখো।',
    giftTagFrom: 'চিরকাল তোমার',
    giftTagTo: 'আমার প্রিয়তমা',
    reasonWhySpecial: 'তুমি আমার জীবনে আসার পর প্রতিটি মুহূর্ত সোনালী হয়ে উঠেছে এবং প্রতিটি কঠিন সময়ে তুমি আমার পাশে থেকেছো।',
    customWishMessage: 'তোমার মুখের এই মিষ্টি হাসি চিরকাল অম্লান থাকুক ❤️',
    letterTitle: 'আমার হৃদয়ের গভীরতম অনুভূতি 💌',
    letterContent: `আমার প্রিয়তমা,\n\nভাষায় প্রকাশ করা অসম্ভব আমি তোমাকে কতটা ভালোবাসি। তুমি আমার জীবনে আসার পর থেকে পৃথিবীটা আরও সুন্দর হয়ে উঠেছে। তোমার একটা মিষ্টি হাসি আমার সব কষ্ট ভুলিয়ে দেয়।\n\nতোমার সাথে কাটানো প্রতিটি মুহূর্ত আমার হৃদয়ে সোনার অক্ষরে লেখা আছে। তুমি শুধু আমার জীবনসঙ্গী নও, আমার প্রতিটি নিঃশ্বাসের অংশ।\n\nচিরকাল এভাবেই ভালো থেকো। জীবনের প্রতিটি পদক্ষেপে আমি তোমার পাশে থাকবো।`,
    letterSignature: '~ হৃদয় থেকে, তোমারই আর্যন ❤️',
    paperStyle: 'rose_petal_pressed',
    scrapbookPages: [
      {
        id: 'page-1',
        title: 'শুরুর সেই মধুর ক্ষণ',
        date: 'আমাদের প্রথম দেখা',
        photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
        note: 'প্রথমবার যখন আমাদের চোখ মিললো, মনে হলো যেন পুরো পৃথিবীটাই থেমে গেছে।',
        stickers: ['✨', '☕', '❤️'],
        tapeColor: '#D4AF37',
      },
      {
        id: 'page-2',
        title: 'আমাদের সুন্দর ভ্রমণ',
        date: 'সেই বৃষ্টির দিন',
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        note: 'প্রাণখোলা হাসি, বৃষ্টিতে ভেজা আর ভবিষ্যতের রঙিন স্বপ্ন দেখা।',
        stickers: ['🌊', '🌅'],
        tapeColor: '#E8B4B8',
      },
    ],
    voiceTitle: 'তোমার জন্য একটি ভালোবাসার কণ্ঠবার্তা 🎙️',
    cakeMessage: 'শুভ বিবাহবার্ষিকী অনন্যা ✨',
    wishBannerText: 'একটি মিষ্টি ইচ্ছে প্রকাশ করো! 🎂',
    wishSecretNote: 'আমাদের ভালোবাসা ও বিশ্বাসের বন্ধন সময়ের সাথে সাথে আরও নিবিড় হোক।',
    treatName: 'রয়্যাল বেলজিয়ান ডার্ক ট্রাফেল 🍫',
    treatDesc: '৭০% খাঁটি ডার্ক কোকো ও হেজেলনাটের অপূর্ব স্বাদ।',
    insideJokeMessage: '“পিজ্জার ওপর আনারস দেওয়া মহা অপরাধ — এটা আমরা দুজনেই জানি!”',
    timeCapsuleTitle: 'আমাদের ভবিষ্যতের স্বপ্নের সিন্দুক ⏳',
    timeCapsuleMessage: 'জীবন যেদিকেই যাক না কেন, তোমার প্রতি আমার ভালোবাসা চিরকাল অটুট থাকবে।',
    customItemName: 'আমাদের প্রথম রোডট্রিপের স্মৃতি 🚗',
    customItemDesc: 'পাহাড়ের বুকে মধ্যরাতের যাত্রা আর একসাথে দেখা অপরূপ সূর্যোদয়।',
    customItemTag: 'অনমোল স্মৃতি',
    relationshipNotes: [
      'আমরা সবসময় অতিরিক্ত গার্লিক ব্রেড অর্ডার করি এবং শেষ টুকরোর জন্য লড়াই করি।',
      'বৃষ্টির রাতে গাড়ি চালানোর সময় বাজানো আমাদের প্রিয় গান।',
      'তুমি সবসময় আমার সোয়েটার পরো কারণ তাতে তোমার আপন গন্ধ পাওয়া যায়।',
    ],
    explosionTitle: 'ভালোবাসা ও চমকের গিফট ব্লাস্ট 💥',
    explosionSubtitle: 'নিচের বক্সে ট্যাপ করুন এবং বাতাসে উপহার ছড়িয়ে পড়তে দেখুন!',
    explosionGifts: [
      {
        id: 'exp-1',
        title: 'লাল গোলাপের তোড়া 🌹',
        category: 'flower_bouquet',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        caption: '৫০টি তাজা লাল গোলাপ যা আমাদের চিরন্তন ভালোবাসার প্রতীক।',
        tags: ['চিরন্তন প্রেম', 'সুগন্ধি'],
        reactionEmoji: '🌹',
      },
      {
        id: 'exp-2',
        title: 'কিউট টেডি বেয়ার 🧸',
        category: 'teddy_bear',
        imageUrl: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
        caption: 'যখন আমি দূরে থাকবো, জড়িয়ে ধরার জন্য তোমার মিষ্টি সঙ্গী।',
        tags: ['মিষ্টি উপহার', 'বন্ধু'],
        reactionEmoji: '🧸',
      },
      {
        id: 'exp-3',
        title: 'বেলজিয়ান চকোলেট 🍫',
        category: 'chocolates',
        imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
        caption: 'মুখে মিলিয়ে যাওয়া রাজকীয় ডার্ক চকোলেট।',
        tags: ['মিষ্টি স্বাদ', 'আনন্দ'],
        reactionEmoji: '🍫',
      },
    ],
    lastNoteTitle: 'শেষ চিঠি (The Last Whispering Note) 📜',
    lastNoteParchment: `আর অবশেষে, যখন তুমি এই সিন্দুকের গভীরে পৌঁছাবে, মনে রাখবে এখানে রাখা সবকিছু তোমার প্রতি আমার ভালোবাসার সামান্য একটি ঝলক মাত্র।\n\nআমার হাত ধরার জন্য ধন্যবাদ। যখনই দিন কঠিন লাগবে, এই সিন্দুক খুলে আমার কণ্ঠ শুনো, এই পাতাগুলো পড়ো আর মনে রেখো তুমি আমার জীবনের শ্রেষ্ঠ উপহার।\n\nআজ রাতে মিষ্টি হাসি মুখে নিয়ে ঘুমিও।`,
    lastNoteSignature: '~ চিরদিনের জন্য, তোমারই আর্যন ❤️',
    passwordHint: 'বান্দ্রার সেই ক্যাফের নাম যেখানে আমরা প্রথম দেখা করেছিলাম',
  },
  pa: {
    title: 'ਮੇਰੀ ਪਿਆਰੀ ਅਨੰਨਿਆ ਲਈ — ੪ ਸਾਲਾਂ ਦਾ ਅਟੁੱਟ ਪਿਆਰ ਤੇ ਯਾਦਾਂ ਦਾ ਖ਼ਜ਼ਾਨਾ ✨',
    recipientNameDefault: 'ਅਨੰਨਿਆ',
    senderNameDefault: 'ਆਰੀਅਨ',
    occasionDefault: 'anniversary',
    giftTagMessage: 'ਸਿਰਫ਼ ਤੇਰੇ ਲਈ ਪਿਆਰ ਨਾਲ ਸਜਾਇਆ ਯਾਦਾਂ ਦਾ ਤੋਹਫ਼ਾ। ਜਦੋਂ ਵੀ ਮੁਸਕਰਾਉਣ ਦਾ ਮਨ ਕਰੇ, ਖੋਲ੍ਹ ਕੇ ਵੇਖ ਲੈਣਾ।',
    giftTagFrom: 'ਹਮੇਸ਼ਾ ਤੇਰਾ',
    giftTagTo: 'ਮੇਰੀ ਜਾਨ ਲਈ',
    reasonWhySpecial: 'ਤੂੰ ਮੇਰੀ ਜ਼ਿੰਦਗੀ ਨੂੰ ਖ਼ੁਸ਼ੀਆਂ ਨਾਲ ਭਰ ਦਿੱਤਾ ਹੈ ਅਤੇ ਹਰ ਔਖੇ ਵੇਲੇ ਮੇਰੀ ਸਭ ਤੋਂ ਵੱਡੀ ਤਾਕਤ ਬਣ ਕੇ ਖੜ੍ਹੀ ਰਹੀ ਹੈਂ।',
    customWishMessage: 'ਤੇਰੇ ਚਿਹਰੇ ਦਾ ਇਹ ਪਿਆਰਾ ਹਾਸਾ ਹਮੇਸ਼ਾ ਇੰਝ ਹੀ ਚਮਕਦਾ ਰਹੇ ❤️',
    letterTitle: 'ਮੇਰੇ ਦਿਲ ਦੀ ਸਭ ਤੋਂ ਖ਼ਾਸ ਬਾਤ 💌',
    letterContent: `ਮੇਰੀ ਪਿਆਰੀਏ,\n\nਲਫ਼ਜ਼ਾਂ ਵਿੱਚ ਬਿਆਨ ਕਰਨਾ ਮੁਸ਼ਕਲ ਹੈ ਕਿ ਤੂੰ ਮੇਰੇ ਲਈ ਕੀ ਮਾਇਨੇ ਰੱਖਦੀ ਹੈਂ। ਜਦੋਂ ਦੀ ਤੂੰ ਮੇਰੀ ਜ਼ਿੰਦਗੀ ਵਿੱਚ ਆਈ ਹੈਂ, ਹਰ ਦਿਨ ਕਿਸੇ ਤਿਉਹਾਰ ਵਾਂਗ ਲੱਗਦਾ ਹੈ। ਤੇਰਾ ਇੱਕ ਹਾਸਾ ਮੇਰੇ ਸਾਰੇ ਦੁੱਖ ਭੁਲਾ ਦਿੰਦਾ ਹੈ।\n\nਤੇਰੇ ਨਾਲ ਬਿਤਾਇਆ ਹਰ ਪਲ ਮੇਰੇ ਦਿਲ ਦੀ ਤਿਜੋਰੀ ਵਿੱਚ ਸਾਂਭਿਆ ਹੋਇਆ ਹੈ। ਤੂੰ ਸਿਰਫ਼ ਮੇਰੀ ਹਮਸਫ਼ਰ ਨਹੀਂ, ਮੇਰੇ ਸਾਹਾਂ ਦਾ ਹਿੱਸਾ ਹੈਂ।\n\nਹਮੇਸ਼ਾ ਇਵੇਂ ਹੀ ਹੱਸਦੀ ਰਹਿ। ਮੇਰਾ ਹੱਥ ਹਮੇਸ਼ਾ ਤੇਰੇ ਹੱਥ ਵਿੱਚ ਰਹੇਗਾ।`,
    letterSignature: '~ ਦਿਲੋਂ, ਸਿਰਫ਼ ਤੇਰਾ ਆਰੀਅਨ ❤️',
    paperStyle: 'rose_petal_pressed',
    scrapbookPages: [
      {
        id: 'page-1',
        title: 'ਸ਼ੁਰੂਆਤ ਦੀ ਉਹ ਖ਼ੂਬਸੂਰਤ ਸ਼ਾਮ',
        date: 'ਸਾਡੀ ਪਹਿਲੀ ਮੁਲਾਕਾਤ',
        photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
        note: 'ਜਦੋਂ ਪਹਿਲੀ ਵਾਰ ਸਾਡੀਆਂ ਨਜ਼ਰਾਂ ਮਿਲੀਆਂ, ਇੰਝ ਲੱਗਾ ਜਿਵੇਂ ਸਾਰਾ ਜਹਾਨ ਠਹਿਰ ਗਿਆ ਹੋਵੇ।',
        stickers: ['✨', '☕', '❤️'],
        tapeColor: '#D4AF37',
      },
      {
        id: 'page-2',
        title: 'ਸਾਡਾ ਪਿਆਰਾ ਜਿਹਾ ਸਫ਼ਰ',
        date: 'ਉਹ ਯਾਦਗਾਰ ਮੀਂਹ ਦਾ ਦਿਨ',
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        note: 'ਖੁੱਲ੍ਹ ਕੇ ਹੱਸਣਾ, ਮੀਂਹ ਵਿੱਚ ਭਿੱਜਣਾ ਤੇ ਸੋਹਣੇ ਭਵਿੱਖ ਦੇ ਸੁਪਨੇ ਦੇਖਣਾ।',
        stickers: ['🌊', '🌅'],
        tapeColor: '#E8B4B8',
      },
    ],
    voiceTitle: 'ਤੇਰੇ ਲਈ ਇੱਕ ਦਿਲੋਂ ਨਿਕਲੀ ਆਵਾਜ਼ 🎙️',
    cakeMessage: 'ਵਿਆਹ ਦੀ ਵਰ੍ਹੇਗੰਢ ਮੁਬਾਰਕ ਅਨੰਨਿਆ ✨',
    wishBannerText: 'ਇੱਕ ਪਿਆਰੀ ਜਿਹੀ ਦੁਆ ਮੰਗੋ! 🎂',
    wishSecretNote: 'ਸਾਡਾ ਪਿਆਰ ਤੇ ਇਹ ਖ਼ੂਬਸੂਰਤ ਰਿਸ਼ਤਾ ਵਕਤ ਦੇ ਨਾਲ ਹੋਰ ਵੀ ਗੂੜ੍ਹਾ ਹੁੰਦਾ ਜਾਵੇ।',
    treatName: 'ਸ਼ਾਹੀ ਬੈਲਜੀਅਨ ਡਾਰਕ ਟਰਫਲਜ਼ 🍫',
    treatDesc: '੭੦% ਸ਼ੁੱਧ ਡਾਰਕ ਕੋਕੋ ਤੇ ਹੇਜ਼ਲਨਟ ਦਾ ਸ਼ਾਨਦਾਰ ਸਵਾਦ।',
    insideJokeMessage: '“ਪਿੱਜ਼ਾ ’ਤੇ ਅਨਾਨਾਸ ਪਾਉਣਾ ਗੁਨਾਹ ਹੈ — ਤੇ ਇਹ ਅਸੀਂ ਦੋਵੇਂ ਜਾਣਦੇ ਹਾਂ!”',
    timeCapsuleTitle: 'ਸਾਡੇ ਆਉਣ ਵਾਲੇ ਕੱਲ੍ਹ ਦੀ ਤਿਜੋਰੀ ⏳',
    timeCapsuleMessage: 'ਜ਼ਿੰਦਗੀ ਜਿੱਥੇ ਮਰਜ਼ੀ ਲੈ ਜਾਵੇ, ਮੇਰਾ ਪਿਆਰ ਤੇਰੇ ਲਈ ਹਮੇਸ਼ਾ ਅਟੁੱਟ ਰਹੇਗਾ।',
    customItemName: 'ਸਾਡੀ ਪਹਿਲੀ ਰੋਡ ਟ੍ਰਿਪ ਦੀ ਯਾਦਗਾਰ 🚗',
    customItemDesc: 'ਪਹਾੜਾਂ ਵਿੱਚ ਅੱਧੀ ਰਾਤ ਦਾ ਸਫ਼ਰ ਤੇ ਇਕੱਠਿਆਂ ਵੇਖਿਆ ਸੂਰਜ।',
    customItemTag: 'ਅਨਮੋਲ ਯਾਦ',
    relationshipNotes: [
      'ਅਸੀਂ ਹਮੇਸ਼ਾ ਐਕਸਟ੍ਰਾ ਗਾਰਲਿਕ ਬ੍ਰੈੱਡ ਮੰਗਾਉਂਦੇ ਹਾਂ ਤੇ ਆਖ਼ਰੀ ਟੁਕੜੇ ਲਈ ਲੜਦੇ ਹਾਂ।',
      'ਮੀਂਹ ਵਿੱਚ ਗੱਡੀ ਚਲਾਉਂਦੇ ਹੋਏ ਵੱਜਿਆ ਸਾਡਾ ਮਨਪਸੰਦ ਗੀਤ।',
      'ਤੂੰ ਹਮੇਸ਼ਾ ਮੇਰਾ ਸਵੈਟਰ ਪਾਉਂਦੀ ਹੈਂ ਕਿਉਂਕਿ ਉਸ ਵਿੱਚੋਂ ਅਪਣੱਤ ਦੀ ਖ਼ੁਸ਼ਬੂ ਆਉਂਦੀ ਹੈ।',
    ],
    explosionTitle: 'ਪਿਆਰ ਤੇ ਸਰਪ੍ਰਾਈਜ਼ ਦਾ ਗਿਫ਼ਟ ਬਲਾਸਟ 💥',
    explosionSubtitle: 'ਹੇਠਾਂ ਵਾਲੇ ਬਾਕਸ ਨੂੰ ਛੂਹੋ ਤੇ ਸਾਰੇ ਤੋਹਫ਼ੇ ਉੱਡਦੇ ਵੇਖੋ!',
    explosionGifts: [
      {
        id: 'exp-1',
        title: 'ਲਾਲ ਗੁਲਾਬਾਂ ਦਾ ਗੁਲਦਸਤਾ 🌹',
        category: 'flower_bouquet',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        caption: 'ਕਦੇ ਨਾ ਮੁਰਝਾਉਣ ਵਾਲੇ ੫੦ ਤਾਜ਼ਾ ਲਾਲ ਗੁਲਾਬ।',
        tags: ['ਸੱਚਾ ਪਿਆਰ', 'ਮਹਿਕ'],
        reactionEmoji: '🌹',
      },
      {
        id: 'exp-2',
        title: 'ਪਿਆਰਾ ਟੈਡੀ ਬੇਅਰ 🧸',
        category: 'teddy_bear',
        imageUrl: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
        caption: 'ਜਦੋਂ ਮੈਂ ਦੂਰ ਹੋਵਾਂ ਤਾਂ ਗਲਵੱਕੜੀ ਪਾਉਣ ਲਈ ਤੇਰਾ ਪਿਆਰਾ ਸਾਥੀ।',
        tags: ['ਨਿੱਘੀ ਜੱਫੀ', 'ਦੋਸਤ'],
        reactionEmoji: '🧸',
      },
      {
        id: 'exp-3',
        title: 'ਬੈਲਜੀਅਨ ਚਾਕਲੇਟ 🍫',
        category: 'chocolates',
        imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
        caption: 'ਮੂੰਹ ਵਿੱਚ ਘੁਲ ਜਾਣ ਵਾਲੀ ਸ਼ਾਹੀ ਡਾਰਕ ਚਾਕਲੇਟ।',
        tags: ['ਮਿਠਾਸ', 'ਖ਼ੁਸ਼ੀ'],
        reactionEmoji: '🍫',
      },
    ],
    lastNoteTitle: 'ਆਖ਼ਰੀ ਗੁਪਤ ਚਿੱਠੀ (The Last Whispering Note) 📜',
    lastNoteParchment: `ਤੇ ਆਖ਼ਰਕਾਰ, ਜਦੋਂ ਤੂੰ ਇਸ ਸੰਦੂਕ ਦੇ ਤਲ ’ਤੇ ਪਹੁੰਚੇਂਗੀ, ਤਾਂ ਯਾਦ ਰੱਖੀਂ ਕਿ ਇੱਥੇ ਰੱਖੀ ਹਰ ਚੀਜ਼ ਤੇਰੇ ਲਈ ਮੇਰੇ ਪਿਆਰ ਦਾ ਇੱਕ ਨਿੱਕਾ ਜਿਹਾ ਹਿੱਸਾ ਹੈ।\n\nਮੇਰਾ ਹੱਥ ਫੜਨ ਲਈ ਸ਼ੁਕਰੀਆ। ਜਦੋਂ ਵੀ ਦਿਨ ਔਖੇ ਲੱਗਣ, ਇਸ ਸੰਦੂਕ ਨੂੰ ਖੋਲ੍ਹੀਂ, ਮੇਰੀ ਆਵਾਜ਼ ਸੁਣੀਂ ਤੇ ਯਾਦ ਰੱਖੀਂ ਕਿ ਤੂੰ ਮੇਰੀ ਜ਼ਿੰਦਗੀ ਦਾ ਸਭ ਤੋਂ ਵੱਡਾ ਚਮਤਕਾਰ ਹੈਂ।\n\nਅੱਜ ਰਾਤ ਚਿਹਰੇ ’ਤੇ ਮੁਸਕਰਾਹਟ ਲੈ ਕੇ ਸੌਂਵੀਂ।`,
    lastNoteSignature: '~ ਸਦਾ ਲਈ, ਸਿਰਫ਼ ਤੇਰਾ ਆਰੀਅਨ ❤️',
    passwordHint: 'ਬਾਂਦਰਾ ਦੇ ਉਸ ਕੈਫ਼ੇ ਦਾ ਨਾਂ ਜਿੱਥੇ ਅਸੀਂ ਪਹਿਲੀ ਵਾਰ ਮਿਲੇ ਸੀ',
  },
  ta: {
    title: 'என் அன்பிற்குரிய அனன்யாவிற்கு — 4 ஆண்டுகால அழியாத காதல் பெட்டகம் ✨',
    recipientNameDefault: 'அனன்யா',
    senderNameDefault: 'ஆர்யன்',
    occasionDefault: 'anniversary',
    giftTagMessage: 'உனக்காகவே அன்புடன் உருவாக்கப்பட்ட நினைவுகளின் பொக்கிஷம். புன்னகைக்க விரும்பும் போதெல்லாம் திறந்து பார்.',
    giftTagFrom: 'என்றும் உனது',
    giftTagTo: 'என் காதலிக்கு',
    reasonWhySpecial: 'நீ என் வாழ்க்கையில் வந்த பிறகு ஒவ்வொரு தருணமும் அழகாக மாறியது, எந்த சூழலிலும் நீ என் பக்கபலமாக இருந்தாய்.',
    customWishMessage: 'உன் அழகான புன்னகை எப்போதும் ஒளிரட்டும் ❤️',
    letterTitle: 'என் இதயத்தின் ஆழமான காதல் மடல் 💌',
    letterContent: `என் அன்பே,\n\nநான் உன்னை எவ்வளவு நேசிக்கிறேன் என்பதை வார்த்தைகளால் விவரிக்க முடியாது. நீ என் வாழ்க்கையில் வந்த தருணம் முதல், என் உலகம் ஒளிமயமாகிவிட்டது. உன் ஒற்றைப் புன்னகை என் அனைத்து கவலைகளையும் போக்கிவிடும்.\n\nஉன்னுடன் கழித்த ஒவ்வொரு நொடியும் என் நினைவுகளில் பொக்கிஷமாய் பதிந்துள்ளது. நீ என் துணை மட்டுமல்ல, என் சுவாசத்தின் ஒரு பகுதி.\n\nஎப்போதும் இப்படியே புன்னகையோடு இரு. எந்த சூழ்நிலையிலும் உன் கையை நான் விடமாட்டேன்.`,
    letterSignature: '~ இதயபூர்வமாக, உனது ஆர்யன் ❤️',
    paperStyle: 'rose_petal_pressed',
    scrapbookPages: [
      {
        id: 'page-1',
        title: 'அழகான தொடக்கம்',
        date: 'நமது முதல் சந்திப்பு',
        photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
        note: 'முதன்முதலில் நமது கண்கள் சந்தித்த போது, உலகமே உறைந்து போனது போல் இருந்தது.',
        stickers: ['✨', '☕', '❤️'],
        tapeColor: '#D4AF37',
      },
      {
        id: 'page-2',
        title: 'இனிய பயணம்',
        date: 'அந்த மறக்கமுடியாத மழை நாள்',
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        note: 'மனம் விட்டு சிரிப்பது, மழையில் நனைவது, எதிர்கால கனவுகளை பகிர்வது.',
        stickers: ['🌊', '🌅'],
        tapeColor: '#E8B4B8',
      },
    ],
    voiceTitle: 'உனக்காக ஒரு இதயபூர்வ குரல் பதிவு 🎙️',
    cakeMessage: 'இனிய திருமண நாள் வாழ்த்துகள் அனன்யா ✨',
    wishBannerText: 'ஒரு இனிமையான விருப்பத்தை வேண்டிக்கொள்! 🎂',
    wishSecretNote: 'நமது அன்பும் பாசமும் காலங்கள் கடந்தும் மென்மேலும் வளரட்டும்.',
    treatName: 'ராயல் பெல்ஜியன் டார்க் சாக்லேட் 🍫',
    treatDesc: '70% தூய டார்க் கோகோ மற்றும் ஹேசல்நட் கலந்த இனிப்பு.',
    insideJokeMessage: '“பீட்சாவில் அன்னாசிப்பழம் வைப்பது குற்றம் — இது நம் இருவருக்கும் நன்றாகவே தெரியும்!”',
    timeCapsuleTitle: 'நமது எதிர்கால கனவுகளின் பெட்டகம் ⏳',
    timeCapsuleMessage: 'வாழ்க்கை எந்த திசையில் சென்றாலும், உன் மீதான என் காதல் மாறாது.',
    customItemName: 'நமது முதல் பயணத்தின் நினைவு 🚗',
    customItemDesc: 'மலையடிவாரத்தில் நடு இரவில் மேற்கொண்ட பயணமும், ஒன்றாக கண்ட சூரிய உதயமும்.',
    customItemTag: 'விலைமதிப்பற்ற நினைவு',
    relationshipNotes: [
      'நாம் எப்போதும் கூடுதல் கார்லிக் பிரெட் ஆர்டர் செய்து கடைசி துண்டுக்காக சண்டையிடுகிறோம்.',
      'மழையில் கார் ஓட்டும் போது ஒலித்த நமது விருப்பமான பாடல்.',
      'நீ எப்போதும் என் ஸ்வெட்டரை அணிகிறாய், ஏனெனில் அதில் நம் அன்பின் வாசம் உள்ளது.',
    ],
    explosionTitle: 'காதல் மற்றும் ஆச்சரியங்களின் கிஃப்ட் பிளாஸ்ட் 💥',
    explosionSubtitle: 'கீழே உள்ள பெட்டியைத் தொட்டு பரிசுகள் காற்றில் பறப்பதை பாருங்கள்!',
    explosionGifts: [
      {
        id: 'exp-1',
        title: 'சிவப்பு ரோஜா கொத்து 🌹',
        category: 'flower_bouquet',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        caption: 'என்றும் வாடாத 50 புதிய சிவப்பு ரோஜாக்கள்.',
        tags: ['அழியாத காதல்', 'நறுமணம்'],
        reactionEmoji: '🌹',
      },
      {
        id: 'exp-2',
        title: 'அழகான டெடி பியர் 🧸',
        category: 'teddy_bear',
        imageUrl: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
        caption: 'நான் அருகில் இல்லாத போது அணைத்துக் கொள்ள ஒரு இனிய தோழன்.',
        tags: ['அன்பு அணைப்பு', 'தோழன்'],
        reactionEmoji: '🧸',
      },
      {
        id: 'exp-3',
        title: 'பெல்ஜியன் சாக்லேட் 🍫',
        category: 'chocolates',
        imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
        caption: 'நாவில் கரையும் சுவையான டார்க் சாக்லேட்.',
        tags: ['இனிப்பு', 'மகிழ்ச்சி'],
        reactionEmoji: '🍫',
      },
    ],
    lastNoteTitle: 'கடைசி ரகசிய மடல் (The Last Whispering Note) 📜',
    lastNoteParchment: `இறுதியாக, நீ இந்த பெட்டியின் அடிவாரத்தை அடையும் போது, இங்குள்ள அனைத்தும் உன் மீதான என் அன்பின் சிறிய அடையாளம் என்பதை நினைவில் கொள்.\n\nஎன் கை பிடித்ததற்கு நன்றி. நாட்கள் கடினமாக இருக்கும் போது, இந்த பெட்டியை திறந்து என் குரலைக் கேள், என் வரிகளை வாசி, நீயே என் வாழ்க்கையின் ஆகச்சிறந்த அற்புதம்.\n\nஇன்று இரவு முகத்தில் புன்னகையோடு உறங்கு.`,
    lastNoteSignature: '~ என்றென்றும் உனது, ஆர்யன் ❤️',
    passwordHint: 'நாம் முதலில் சந்தித்த பாந்த்ராவில் உள்ள கஃபே பெயர்',
  },
  te: {
    title: 'నా ప్రియమైన అనన్యకు — 4 సంవత్సరాల అంతులేని ప్రేమ మరియు జ్ఞాపకాల పేటిక ✨',
    recipientNameDefault: 'అనన్య',
    senderNameDefault: 'ఆర్యన్',
    occasionDefault: 'anniversary',
    giftTagMessage: 'నీ కోసమే ప్రత్యేకంగా ప్రేమతో రూపొందించిన జ్ఞాపకాల నిధి. ఎప్పుడు నవ్వాలనిపించినా తెరిచి చూడు.',
    giftTagFrom: 'ఎల్లప్పుడూ నీవాడే',
    giftTagTo: 'నా ప్రియతమకు',
    reasonWhySpecial: 'నువ్వు నా జీవితంలోకి వచ్చిన తర్వాత ప్రతి క్షణం బంగారమైంది మరియు ప్రతి కష్టంలో నువ్వు నాకు అండగా నిలిచావు.',
    customWishMessage: 'నీ ముఖంలో ఈ చిరునవ్వు ఎల్లప్పుడూ ఇలాగే వెలగాలి ❤️',
    letterTitle: 'నా హృదయపూర్వక ప్రేమలేఖ 💌',
    letterContent: `నా ప్రియతమా,\n\nనేను నిన్ను ఎంతగా ప్రేమిస్తున్నానో మాటల్లో చెప్పడం సాధ్యం కాదు. నువ్వు నా జీవితంలోకి వచ్చిన క్షణం నుండి, నా ప్రపంచం మరింత అందంగా మారింది. నీ ఒక్క చిరునవ్వు నా బాధలన్నింటినీ మాయం చేస్తుంది.\n\nనీతో గడిపిన ప్రతి క్షణం నా జ్ఞాపకాలలో బంగారు అక్షరాలతో నిలిచిపోయింది. నువ్వు నా జీవిత భాగస్వామివి మాత్రమే కాదు, నా ప్రాణం.\n\nఎల్లప్పుడూ ఇలాగే నవ్వుతూ ఉండు. జీవితంలో ప్రతి అడుగులో నీ చేయి పట్టుకుని ఉంటాను.`,
    letterSignature: '~ మనస్ఫూర్తిగా, నీ ఆర్యన్ ❤️',
    paperStyle: 'rose_petal_pressed',
    scrapbookPages: [
      {
        id: 'page-1',
        title: 'మధురమైన ఆరంభం',
        date: 'మన మొదటి కలయిక',
        photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
        note: 'మొదటిసారి మన కళ్ళు కలిసినప్పుడు, సమయం అక్కడే ఆగిపోయినట్లు అనిపించింది.',
        stickers: ['✨', '☕', '❤️'],
        tapeColor: '#D4AF37',
      },
      {
        id: 'page-2',
        title: 'మన అందమైన ప్రయాణం',
        date: 'ఆ మరపురాని వర్షపు రోజు',
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        note: 'మనసారా నవ్వుకోవడం, వర్షంలో తడవడం మరియు భవిష్యత్ కలలు పంచుకోవడం.',
        stickers: ['🌊', '🌅'],
        tapeColor: '#E8B4B8',
      },
    ],
    voiceTitle: 'నీ కోసం ఒక ప్రేమపూర్వక వాయిస్ సందేశం 🎙️',
    cakeMessage: 'వివాహ వార్షికోత్సవ శుభాకాంక్షలు అనన్య ✨',
    wishBannerText: 'ఒక తీపి కోరికను కోరుకోండి! 🎂',
    wishSecretNote: 'మన ప్రేమ మరియు అనుబంధం కాలంతో పాటు మరింత బలపడాలి.',
    treatName: 'రాయల్ బెల్జియన్ డార్క్ చాక్లెట్స్ 🍫',
    treatDesc: '70% స్వచ్ఛమైన డార్క్ కోకో మరియు హాజెల్‌నట్ కలయిక.',
    insideJokeMessage: '“పిజ్జాపై పైనాపిల్ వేయడం నేరం — ఇది మన ఇద్దరికీ బాగా తెలుసు!”',
    timeCapsuleTitle: 'మన భవిష్యత్ కలల పేటిక ⏳',
    timeCapsuleMessage: 'జీవితం ఏ మలుపు తిరిగినా, నీపై నా ప్రేమ ఎప్పటికీ మారదు.',
    customItemName: 'మన మొదటి రోడ్‌ట్రిప్ జ్ఞాపకం 🚗',
    customItemDesc: 'కొండల్లో అర్ధరాత్రి ప్రయాణం మరియు కలిసి చూసిన అందమైన సూర్యోదయం.',
    customItemTag: 'అమూల్యమైన జ్ఞాపకం',
    relationshipNotes: [
      'మనం ఎప్పుడూ అదనంగా గార్లిక్ బ్రెడ్ ఆర్డర్ చేస్తాం మరియు చివరి ముక్క కోసం గొడవపడతాం.',
      'వర్షంలో డ్రైవ్ చేస్తున్నప్పుడు మోగిన మన ఫేవరెట్ పాట.',
      'నువ్వు ఎప్పుడూ నా స్వెటర్ వేసుకుంటావు ఎందుకంటే అందులో మన ప్రేమ సువాసన ఉంటుంది.',
    ],
    explosionTitle: 'ప్రేమ మరియు ఆశ్చర్యాల గిఫ్ట్ బ్లాస్ట్ 💥',
    explosionSubtitle: 'క్రింది బాక్స్‌ను తాకి బహుమతులు గాల్లో ఎగరడం చూడండి!',
    explosionGifts: [
      {
        id: 'exp-1',
        title: 'ఎర్ర గులాబీల గుత్తి 🌹',
        category: 'flower_bouquet',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        caption: 'ఎప్పటికీ వాడిపోని 50 తాజా ఎర్ర గులాబీలు.',
        tags: ['శాశ్వత ప్రేమ', 'సువాసన'],
        reactionEmoji: '🌹',
      },
      {
        id: 'exp-2',
        title: 'ముద్దొచ్చే టెడ్డీ బేర్ 🧸',
        category: 'teddy_bear',
        imageUrl: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
        caption: 'నేను దూరంగా ఉన్నప్పుడు హత్తుకోవడానికి ఒక తీపి నేస్తం.',
        tags: ['తీపి కౌగిలి', 'నేస్తం'],
        reactionEmoji: '🧸',
      },
      {
        id: 'exp-3',
        title: 'బెల్జియన్ చాక్లెట్స్ 🍫',
        category: 'chocolates',
        imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
        caption: 'నోట్లో కరిగిపోయే రాయల్ డార్క్ చాక్లెట్.',
        tags: ['తీపి రుచి', 'ఆనందం'],
        reactionEmoji: '🍫',
      },
    ],
    lastNoteTitle: 'చివరి రహస్య లేఖ (The Last Whispering Note) 📜',
    lastNoteParchment: `చివరిగా, నువ్వు ఈ పెట్టె అడుగుభాగానికి చేరుకున్నప్పుడు, ఇక్కడ ఉన్న ప్రతిదీ నీపై నాకున్న ప్రేమకు ఒక చిన్న గుర్తు మాత్రమే అని గుర్తుంచుకో.\n\nనా చేయి పట్టుకున్నందుకు ధన్యవాదాలు. కష్ట సమయాల్లో ఈ పెట్టె తెరిచి నా గొంతు విను, ఈ పేజీలు చదువు, నువ్వే నా జీవితంలో అతిపెద్ద అద్భుతం.\n\nఈ రాత్రి చిరునవ్వుతో నిద్రపో.`,
    lastNoteSignature: '~ ఎప్పటికీ నీవాడే, ఆర్యన్ ❤️',
    passwordHint: 'మనం మొదట కలిసిన బాంద్రాలోని కేఫ్ పేరు',
  },
  es: {
    title: 'Para mi querida Ananya — 4 Años de Amor Incondicional y Recuerdos ✨',
    recipientNameDefault: 'Ananya',
    senderNameDefault: 'Aryan',
    occasionDefault: 'anniversary',
    giftTagMessage: 'Un cofre del tesoro hecho a mano con amor. Ábrelo cuando quieras sonreír.',
    giftTagFrom: 'Siempre Tuyo',
    giftTagTo: 'Mi Amor',
    reasonWhySpecial: 'Haces que los momentos más simples sean mágicos y siempre has estado a mi lado en las buenas y en las malas.',
    customWishMessage: 'Que tu hermosa sonrisa ilumine siempre mi mundo ❤️',
    letterTitle: 'Para la Dueña de mi Corazón 💌',
    letterContent: `Mi Amor,\n\nLas palabras no bastan para describir cuánto te amo. Desde que llegaste a mi vida, todo es más brillante y cálido. Tu risa es mi refugio favorito.\n\nCada momento compartido está grabado en oro en mi memoria. Eres mi compañera de vida y el latido de mi corazón.\n\nPrometo caminar a tu lado por siempre, en cada paso y en cada aventura.`,
    letterSignature: '~ Con todo mi corazón, Aryan ❤️',
    paperStyle: 'rose_petal_pressed',
    scrapbookPages: [
      {
        id: 'page-1',
        title: 'El Comienzo de Nuestra Historia',
        date: 'Nuestro Primer Encuentro',
        photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
        note: 'La primera vez que nuestras miradas se cruzaron, el tiempo se detuvo.',
        stickers: ['✨', '☕', '❤️'],
        tapeColor: '#D4AF37',
      },
      {
        id: 'page-2',
        title: 'Nuestra Dulce Aventura',
        date: 'Aquel Fin de Semana Inolvidable',
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        note: 'Riendo sin parar, caminando bajo la lluvia y soñando con un futuro juntos.',
        stickers: ['🌊', '🌅'],
        tapeColor: '#E8B4B8',
      },
    ],
    voiceTitle: 'Un Mensaje de Voz para Ti 🎙️',
    cakeMessage: '¡Feliz 4º Aniversario Ananya! ✨',
    wishBannerText: '¡Pide un Deseo con Amor! 🎂',
    wishSecretNote: 'Que nuestro amor y nuestras risas sean eternas ante cualquier tormenta.',
    treatName: 'Trufas de Chocolate Belga 🍫',
    treatDesc: 'Cacao oscuro al 70% con crujiente de avellanas tostadas.',
    insideJokeMessage: '“La piña en la pizza es un crimen contra la humanidad — ¡y ambos lo sabemos!”',
    timeCapsuleTitle: 'Nuestra Cápsula del Tiempo Secreta ⏳',
    timeCapsuleMessage: 'No importa dónde nos lleve la vida, mi amor por ti será siempre inquebrantable.',
    customItemName: 'Recuerdo de Nuestro Primer Viaje 🚗',
    customItemDesc: 'De aquel viaje a las montañas viendo juntos el amanecer.',
    customItemTag: 'Recuerdo Inolvidable',
    relationshipNotes: [
      'Siempre pedimos pan de ajo extra y peleamos por el último trozo.',
      'Nuestra canción sonando en el coche mientras llovía.',
      'Siempre usas mis suéteres porque dices que huelen a hogar.',
    ],
    explosionTitle: 'Lluvia de Amor y Sorpresas (Explosión de Regalos) 💥',
    explosionSubtitle: '¡Toca la caja vibrante y mira los regalos volar por el aire!',
    explosionGifts: [
      {
        id: 'exp-1',
        title: 'Ramo de Rosas Rojas 🌹',
        category: 'flower_bouquet',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        caption: '50 rosas frescas que simbolizan nuestro amor eterno.',
        tags: ['Amor Eterno', 'Fragancia'],
        reactionEmoji: '🌹',
      },
      {
        id: 'exp-2',
        title: 'Tierno Oso de Peluche 🧸',
        category: 'teddy_bear',
        imageUrl: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
        caption: 'Un tierno abrazo para cuando esté lejos.',
        tags: ['Abrazo Suave', 'Compañero'],
        reactionEmoji: '🧸',
      },
      {
        id: 'exp-3',
        title: 'Selección de Trufas Belgas 🍫',
        category: 'chocolates',
        imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
        caption: 'Deliciosos chocolates artesanales que se derriten en tu boca.',
        tags: ['Dulzura', 'Placer'],
        reactionEmoji: '🍫',
      },
    ],
    lastNoteTitle: 'La Última Carta Secreta (The Last Note) 📜',
    lastNoteParchment: `Y así, cuando llegues al fondo de este pequeño universo que creé para ti, recuerda que todo lo guardado aquí es solo un reflejo de lo inmensamente que te amo.\n\nGracias por caminar a mi lado. Cuando los días sean difíciles, ven a esta caja, escucha mi voz y recuerda que eres mi mayor milagro.\n\nDuerme con una sonrisa esta noche.`,
    lastNoteSignature: '~ Con todo mi amor, Aryan ❤️',
    passwordHint: 'El nombre del café donde nos conocimos por primera vez',
  },
  fr: {
    title: 'Pour ma chère Ananya — 4 Ans d\'Amour Éternel et de Souvenirs ✨',
    recipientNameDefault: 'Ananya',
    senderNameDefault: 'Aryan',
    occasionDefault: 'anniversary',
    giftTagMessage: 'Un coffre aux trésors fait à la main avec amour. Ouvre-le pour sourire.',
    giftTagFrom: 'À jamais tien',
    giftTagTo: 'Mon Amour',
    reasonWhySpecial: 'Tu rends chaque instant magique et tu as toujours été mon repère.',
    customWishMessage: 'Que ton doux sourire illumine toujours ma vie ❤️',
    letterTitle: 'À celle qui fait battre mon cœur 💌',
    letterContent: `Mon Amour,\n\nLes mots ne suffisent pas pour exprimer à quel point je t'aime. Depuis que tu es entrée dans ma vie, chaque jour est plus lumineux. Ton rire est ma plus belle mélodie.\n\nChaque instant passé ensemble est gravé pour toujours dans mon cœur. Tu es ma moitié et mon éternel bonheur.\n\nJe promets d'être à tes côtés, main dans la main, pour toujours.`,
    letterSignature: '~ De tout mon cœur, Aryan ❤️',
    paperStyle: 'rose_petal_pressed',
    scrapbookPages: [
      {
        id: 'page-1',
        title: 'Notre Première Rencontre',
        date: 'Le Début de Tout',
        photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
        note: 'Lorsque nos regards se sont croisés, le temps s\'est arrêté.',
        stickers: ['✨', '☕', '❤️'],
        tapeColor: '#D4AF37',
      },
      {
        id: 'page-2',
        title: 'Notre Douce Aventure',
        date: 'Ce Weekend Inoubliable',
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        note: 'Rires complices sous la pluie et promesses d\'un bel avenir.',
        stickers: ['🌊', '🌅'],
        tapeColor: '#E8B4B8',
      },
    ],
    voiceTitle: 'Un Doux Message Vocal 🎙️',
    cakeMessage: 'Joyeux 4ème Anniversaire Ananya ✨',
    wishBannerText: 'Fais un Vœu d\'Amour ! 🎂',
    wishSecretNote: 'Que notre amour grandisse chaque jour avec tendresse et complicité.',
    treatName: 'Truffes Belges au Chocolat Noir 🍫',
    treatDesc: 'Cacao noir 70% et praliné noisette croquant.',
    insideJokeMessage: '“L\'ananas sur la pizza est un crime — et nous le savons tous les deux !”',
    timeCapsuleTitle: 'Notre Capsule Temporelle Secrète ⏳',
    timeCapsuleMessage: 'Peu importe où la vie nous mène, mon amour pour toi restera infini.',
    customItemName: 'Souvenir de Notre Premier Voyage 🚗',
    customItemDesc: 'Rapporté de notre voyage au lever du soleil sur les collines.',
    customItemTag: 'Souvenir Précieux',
    relationshipNotes: [
      'Nous commandons toujours du pain à l\'ail en plus et nous disputons le dernier morceau.',
      'Notre chanson préférée résonnant dans la voiture sous la pluie.',
      'Tu portes toujours mes pulls parce qu\'ils sentent notre chez-nous.',
    ],
    explosionTitle: 'Pluie d\'Amour et de Surprises (Gift Blast) 💥',
    explosionSubtitle: 'Touche la boîte et regarde tous tes cadeaux s\'envoler dans les airs !',
    explosionGifts: [
      {
        id: 'exp-1',
        title: 'Bouquet de Roses Rouges 🌹',
        category: 'flower_bouquet',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        caption: '50 roses fraîches symbolisant notre amour éternel.',
        tags: ['Amour Éternel', 'Parfum'],
        reactionEmoji: '🌹',
      },
      {
        id: 'exp-2',
        title: 'Adorable Ours en Peluche 🧸',
        category: 'teddy_bear',
        imageUrl: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
        caption: 'Un câlin tout doux pour quand je suis loin de toi.',
        tags: ['Douceur', 'Compagnon'],
        reactionEmoji: '🧸',
      },
      {
        id: 'exp-3',
        title: 'Sélection de Chocolats Belges 🍫',
        category: 'chocolates',
        imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
        caption: 'Chocolats artisanaux qui fondent délicatement en bouche.',
        tags: ['Gourmandise', 'Douceur'],
        reactionEmoji: '🍫',
      },
    ],
    lastNoteTitle: 'La Dernière Lettre Secrète (The Last Note) 📜',
    lastNoteParchment: `Et enfin, lorsque tu atteindras le fond de ce petit univers créé pour toi, rappelle-toi que tout cela n\'est qu\'un reflet de mon amour infini.\n\nMerci d\'être à mes côtés. Quand la vie sera difficile, ouvre cette boîte, écoute ma voix et souviens-toi que tu es mon plus beau miracle.\n\nDors avec le sourire ce soir.`,
    lastNoteSignature: '~ De tout mon cœur, Aryan ❤️',
    passwordHint: 'Le nom du café où nous nous sommes rencontrés pour la première fois',
  },
  it: {
    title: 'Per la mia cara Ananya — 4 Anni di Amore Eterno e Ricordi ✨',
    recipientNameDefault: 'Ananya',
    senderNameDefault: 'Aryan',
    occasionDefault: 'anniversary',
    giftTagMessage: 'Uno scrigno di ricordi fatto a mano con amore. Aprilo per sorridere.',
    giftTagFrom: 'Sempre tuo',
    giftTagTo: 'Amore Mio',
    reasonWhySpecial: 'Rendi ogni momento speciale e sei sempre stata la mia forza.',
    customWishMessage: 'Possa il tuo splendido sorriso illuminare sempre il mio cuore ❤️',
    letterTitle: 'Per la Persona Più Speciale della Mia Vita 💌',
    letterContent: `Amore Mio,\n\nLe parole non bastano per descrivere quanto ti amo. Da quando fai parte della mia vita, tutto ha un colore più dolce. Il tuo sorriso è la mia felicità.\n\nOgni ricordo con te è custodito nel mio cuore. Sei la mia compagna di vita e la mia anima gemella.\n\nPrometto di camminare sempre al tuo fianco, mano nella mano.`,
    letterSignature: '~ Con tutto il mio cuore, Aryan ❤️',
    paperStyle: 'rose_petal_pressed',
    scrapbookPages: [
      {
        id: 'page-1',
        title: 'Il Nostro Primo Incontro',
        date: 'L\'Inizio di Tutto',
        photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
        note: 'Quando i nostri sguardi si sono incrociati, il tempo si è fermato.',
        stickers: ['✨', '☕', '❤️'],
        tapeColor: '#D4AF37',
      },
      {
        id: 'page-2',
        title: 'La Nostra Dolce Avventura',
        date: 'Quel Weekend Indimenticabile',
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        note: 'Risate, pioggia e sogni per un futuro meraviglioso insieme.',
        stickers: ['🌊', '🌅'],
        tapeColor: '#E8B4B8',
      },
    ],
    voiceTitle: 'Un Dolce Messaggio Vocale 🎙️',
    cakeMessage: 'Buon 4º Anniversario Ananya ✨',
    wishBannerText: 'Esprimi un Desiderio d\'Amore! 🎂',
    wishSecretNote: 'Che il nostro amore cresca ogni giorno con gioia e complicità.',
    treatName: 'Tartufi di Cioccolato Belga 🍫',
    treatDesc: 'Cacao fondente al 70% con granella di nocciole tostate.',
    insideJokeMessage: '“L\'ananas sulla pizza è un crimine — e lo sappiamo entrambi!”',
    timeCapsuleTitle: 'La Nostra Capsula del Tempo ⏳',
    timeCapsuleMessage: 'Ovunque la vita ci porti, il mio amore per te sarà per sempre.',
    customItemName: 'Ricordo del Nostro Primo Viaggio 🚗',
    customItemDesc: 'Dal nostro viaggio verso le colline all\'alba.',
    customItemTag: 'Ricordo Prezioso',
    relationshipNotes: [
      'Ordiniamo sempre pane all\'aglio extra e litighiamo per l\'ultimo pezzo.',
      'La nostra canzone che suonava in macchina sotto la pioggia.',
      'Indossi sempre i miei maglioni perché profumano di casa.',
    ],
    explosionTitle: 'Esplosione di Regali e Amore 💥',
    explosionSubtitle: 'Tocca la scatola e guarda i regali volare!',
    explosionGifts: [
      {
        id: 'exp-1',
        title: 'Bouquet di Rose Rosse 🌹',
        category: 'flower_bouquet',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        caption: '50 rose fresche per il nostro amore eterno.',
        tags: ['Amore Eterno', 'Profumo'],
        reactionEmoji: '🌹',
      },
      {
        id: 'exp-2',
        title: 'Tenero Orsetto di Peluche 🧸',
        category: 'teddy_bear',
        imageUrl: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
        caption: 'Un dolce abbraccio per quando sono lontano.',
        tags: ['Dolcezza', 'Amico'],
        reactionEmoji: '🧸',
      },
      {
        id: 'exp-3',
        title: 'Selezione di Cioccolatini Belgi 🍫',
        category: 'chocolates',
        imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
        caption: 'Cioccolato fondente artigianale che si scioglie in bocca.',
        tags: ['Dolcezza', 'Gusto'],
        reactionEmoji: '🍫',
      },
    ],
    lastNoteTitle: 'L\'Ultima Lettera Segreta (The Last Note) 📜',
    lastNoteParchment: `E infine, quando arriverai in fondo a questo piccolo universo, ricorda che tutto questo è solo una parte del mio immenso amore per te.\n\nGrazie per camminare al mio fianco. Quando le giornate saranno difficili, apri questo scrigno, ascolta la mia voce e ricorda che sei il mio miracolo più grande.\n\nBuonanotte con il sorriso stasera.`,
    lastNoteSignature: '~ Con tutto l\'amore, Aryan ❤️',
    passwordHint: 'Il nome del caffè dove ci siamo incontrati la prima volta',
  },
  de: {
    title: 'Für meine liebste Ananya — 4 Jahre ewige Liebe & Erinnerungsschatz ✨',
    recipientNameDefault: 'Ananya',
    senderNameDefault: 'Aryan',
    occasionDefault: 'anniversary',
    giftTagMessage: 'Eine liebevoll handgefertigte Schatztruhe voller Erinnerungen. Öffne sie, wenn du lächeln möchtest.',
    giftTagFrom: 'Für immer dein',
    giftTagTo: 'Meine Liebe',
    reasonWhySpecial: 'Du machst jeden Tag besonders und bist mein Fels in der Brandung.',
    customWishMessage: 'Möge dein strahlendes Lächeln immer mein Herz erwärmen ❤️',
    letterTitle: 'An die Liebe Meines Lebens 💌',
    letterContent: `Meine Liebste,\n\nWorte können nicht beschreiben, wie unendlich viel du mir bedeutest. Seit du in mein Leben getreten bist, ist alles heller und wärmer geworden. Dein Lachen ist mein schönster Trost.\n\nJeder Moment mit dir ist unbezahlbar. Du bist meine Seelenverwandte und mein größtes Glück.\n\nIch verspreche, immer an deiner Seite zu sein, Hand in Hand durchs Leben.`,
    letterSignature: '~ Von ganzem Herzen, dein Aryan ❤️',
    paperStyle: 'rose_petal_pressed',
    scrapbookPages: [
      {
        id: 'page-1',
        title: 'Unser Erstes Treffen',
        date: 'Der Anfang von Allem',
        photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
        note: 'Als sich unsere Blicke zum ersten Mal trafen, stand die Welt still.',
        stickers: ['✨', '☕', '❤️'],
        tapeColor: '#D4AF37',
      },
      {
        id: 'page-2',
        title: 'Unser Schönes Abenteuer',
        date: 'Ein Unvergesslicher Tag',
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        note: 'Gemeinsam lachen, durch den Regen tanzen und von der Zukunft träumen.',
        stickers: ['🌊', '🌅'],
        tapeColor: '#E8B4B8',
      },
    ],
    voiceTitle: 'Eine Liebevolle Sprachnachricht 🎙️',
    cakeMessage: 'Alles Liebe zum 4. Jahrestag Ananya ✨',
    wishBannerText: 'Wünsche dir etwas von Herzen! 🎂',
    wishSecretNote: 'Möge unsere Liebe und Verbundenheit jeden Tag noch tiefer werden.',
    treatName: 'Belgische Zartbitter-Trüffel 🍫',
    treatDesc: '70% dunkler Kakao mit geröstetem Haselnusskrokant.',
    insideJokeMessage: '“Ananas auf Pizza ist ein Verbrechen — und das wissen wir beide!”',
    timeCapsuleTitle: 'Unsere Geheime Zeitkapsel ⏳',
    timeCapsuleMessage: 'Wohin das Leben uns auch führt, meine Liebe zu dir bleibt ewig bestehen.',
    customItemName: 'Erinnerung an Unseren Ersten Roadtrip 🚗',
    customItemDesc: 'Von unserer nächtlichen Fahrt in die Berge zum Sonnenaufgang.',
    customItemTag: 'Wertvolles Andenken',
    relationshipNotes: [
      'Wir bestellen immer extra Knoblauchbrot und streiten um das letzte Stück.',
      'Unser Lieblingslied im Auto während es draußen regnete.',
      'Du trägst immer meine Pullover, weil sie nach Zuhause riechen.',
    ],
    explosionTitle: 'Geschenk-Explosion voller Liebe 💥',
    explosionSubtitle: 'Berühre die Box und sieh zu, wie die Geschenke fliegen!',
    explosionGifts: [
      {
        id: 'exp-1',
        title: 'Strauß Roter Rosen 🌹',
        category: 'flower_bouquet',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        caption: '50 frische rote Rosen für unsere ewige Liebe.',
        tags: ['Ewige Liebe', 'Duft'],
        reactionEmoji: '🌹',
      },
      {
        id: 'exp-2',
        title: 'Süßer Teddybär 🧸',
        category: 'teddy_bear',
        imageUrl: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
        caption: 'Zum Kuscheln, wenn ich mal nicht bei dir bin.',
        tags: ['Kuscheln', 'Freund'],
        reactionEmoji: '🧸',
      },
      {
        id: 'exp-3',
        title: 'Belgische Pralinenauswahl 🍫',
        category: 'chocolates',
        imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
        caption: 'Edle Zartbitterschokolade, die auf der Zunge zergeht.',
        tags: ['Genuss', 'Süße'],
        reactionEmoji: '🍫',
      },
    ],
    lastNoteTitle: 'Der Letzte Geheime Brief (The Last Note) 📜',
    lastNoteParchment: `Und wenn du den Boden dieser kleinen Welt erreichst, wisse, dass all das nur ein kleiner Spiegel meiner unendlichen Liebe zu dir ist.\n\nDanke, dass du mein Leben teilst. Wenn die Tage schwer sind, öffne diese Box, höre meine Stimme und erinnere dich daran, dass du mein größtes Wunder bist.\n\nSchlafe heute Nacht mit einem Lächeln ein.`,
    lastNoteSignature: '~ Von ganzem Herzen, dein Aryan ❤️',
    passwordHint: 'Der Name des Cafés, in dem wir uns zum ersten Mal trafen',
  },
  ar: {
    title: 'إلى عزيزتي أنانيا — 4 سنوات من الحب الأبدي وكنز الذكريات ✨',
    recipientNameDefault: 'أنانيا',
    senderNameDefault: 'آريان',
    occasionDefault: 'anniversary',
    giftTagMessage: 'صندوق ذكريات مصنوع بحب من أجلك. افتحيه كلما أردتِ أن تبتسمي.',
    giftTagFrom: 'دائماً لكِ',
    giftTagTo: 'إلى حبيبتي',
    reasonWhySpecial: 'جعلتِ حياتي أجمل بوجودكِ وكنتِ دائماً سندي في كل لحظة.',
    customWishMessage: 'أتمنى أن تظل ابتسامتكِ الجميلة تضيء عالمي دائماً ❤️',
    letterTitle: 'رسالة من أعماق قلبي 💌',
    letterContent: `حبيبتي الغالية،\n\nتعجز الكلمات عن وصف مدى حبي لكِ. منذ أن دخلتِ حياتي، أصبح كل يوم أجمل وأدفأ. ضحكتكِ هي سر سعادتي.\n\nكل لحظة قضيناها معاً محفورة في قلبي ككنز ثمين. أنتِ لستِ فقط شريكة حياتي، بل نبض قلبي.\n\nأعدكِ بأن أظل بجانبكِ دائماً، يداً بيد إلى الأبد.`,
    letterSignature: '~ بكل حبي، آريان ❤️',
    paperStyle: 'rose_petal_pressed',
    scrapbookPages: [
      {
        id: 'page-1',
        title: 'بداية حكايتنا الجميلة',
        date: 'لقاؤنا الأول',
        photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
        note: 'عندما تلاقت أعيننا لأول مرة، شعرنا وكأن العالم قد توقف.',
        stickers: ['✨', '☕', '❤️'],
        tapeColor: '#D4AF37',
      },
      {
        id: 'page-2',
        title: 'رحلتنا السعيدة',
        date: 'ذلك اليوم الماطر الجميل',
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        note: 'ضحكاتنا تحت المطر وأحلامنا بمستقبل رائع معاً.',
        stickers: ['🌊', '🌅'],
        tapeColor: '#E8B4B8',
      },
    ],
    voiceTitle: 'تسجيل صوتي خاص من القلب 🎙️',
    cakeMessage: 'ذكرى سنوية سعيدة يا أنانيا ✨',
    wishBannerText: 'تمني أمنية من قلبكِ! 🎂',
    wishSecretNote: 'أتمنى أن يزداد حبنا وترابطنا عمقاً وجمالاً مع كل يوم يمر.',
    treatName: 'شوكولاتة الترافل البلجيكية الفاخرة 🍫',
    treatDesc: 'كاكاو داكن 70% مع قطع البندق المحمص المقرمش.',
    insideJokeMessage: '“وضع الأناناس على البيتزا جريمة — وكلانا يعلم ذلك جيداً!”',
    timeCapsuleTitle: 'كبسولة الزمن لذكرياتنا القادمة ⏳',
    timeCapsuleMessage: 'مهما تغيرت الحياة، سيبقى حبي لكِ ثابتاً لا يتغير.',
    customItemName: 'تذكار رحلتنا الأولى 🚗',
    customItemDesc: 'من رحلتنا الليلية إلى الجبال ومشاهدة شروق الشمس معاً.',
    customItemTag: 'تذكار ثمين',
    relationshipNotes: [
      'نطلب دائماً خبز الثوم الإضافي ونتنافس على القطعة الأخيرة.',
      'أغنيتنا المفضلة في السيارة أثناء تساقط المطر.',
      'ترتدين دائماً ستراتي لأنها تشعركِ بالدفء والأمان.',
    ],
    explosionTitle: 'انفجار الهدايا والمفاجآت 💥',
    explosionSubtitle: 'المسي الصندوق وشاهدي الهدايا تتطاير في الهواء!',
    explosionGifts: [
      {
        id: 'exp-1',
        title: 'باقة ورود حمراء 🌹',
        category: 'flower_bouquet',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        caption: '50 وردة حمراء ترمز إلى حبنا الأبدي.',
        tags: ['حب أبدي', 'عطر'],
        reactionEmoji: '🌹',
      },
      {
        id: 'exp-2',
        title: 'دبدوب لطيف 🧸',
        category: 'teddy_bear',
        imageUrl: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
        caption: 'رفيق دافئ عندما أكون بعيداً عنكِ.',
        tags: ['عناق دافئ', 'صديق'],
        reactionEmoji: '🧸',
      },
      {
        id: 'exp-3',
        title: 'شوكولاتة بلجيكية فاخرة 🍫',
        category: 'chocolates',
        imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
        caption: 'شوكولاتة داكنة لذيذة تذوب في الفم.',
        tags: ['حلوى فاخرة', 'سعادة'],
        reactionEmoji: '🍫',
      },
    ],
    lastNoteTitle: 'الرسالة السرية الأخيرة (The Last Note) 📜',
    lastNoteParchment: `وأخيراً، عندما تصلين إلى قاع هذا الصندوق الصغير، تذكري أن كل ما فيه هو مجرد تعبير بسيط عن حبي الكبير لكِ.\n\nشكراً لأنكِ بجانبي دائماً. في الأيام الصعبة، افتحي هذا الصندوق واسمعي صوتي وتذكري أنكِ أعظم معجزة في حياتي.\n\nنامي بابتسامة الليلة.`,
    lastNoteSignature: '~ من كل قلبي، آريان ❤️',
    passwordHint: 'اسم المقهى الذي التقينا فيه لأول مرة',
  },
  ja: {
    title: '最愛のアナニヤへ — 4年間の永遠の愛と思い出の宝箱 ✨',
    recipientNameDefault: 'アナニヤ',
    senderNameDefault: 'アリヤン',
    occasionDefault: 'anniversary',
    giftTagMessage: '愛を込めて手作りした思い出の宝箱。笑顔になりたい時に開けてね。',
    giftTagFrom: 'ずっと君のもの',
    giftTagTo: '最愛の君へ',
    reasonWhySpecial: '君が人生に来てくれてから毎日が輝いていて、いつも私を支えてくれた。',
    customWishMessage: '君の素敵な笑顔がずっと輝き続けますように ❤️',
    letterTitle: '心からのラブレター 💌',
    letterContent: `最愛のアナニヤへ、\n\n君をどれほど愛しているか、言葉では言い尽くせません。君と出会ってから、世界がより優しく温かいものになりました。君の笑顔が私の最大の幸せです。\n\n君と過ごしたすべての瞬間は私の宝物です。君は私のパートナーであり、私の心そのものです。\n\nずっと手をつないで一緒に歩んでいこう。`,
    letterSignature: '~ 心を込めて、アリヤン ❤️',
    paperStyle: 'rose_petal_pressed',
    scrapbookPages: [
      {
        id: 'page-1',
        title: '二人の始まり',
        date: '初めての出会い',
        photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
        note: '初めて目が合った瞬間、まるで時間が止まったかのようでした。',
        stickers: ['✨', '☕', '❤️'],
        tapeColor: '#D4AF37',
      },
      {
        id: 'page-2',
        title: '素敵な冒険',
        date: '忘れられない雨の週末',
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        note: 'たくさん笑って、雨の中を歩いて、未来の夢を語り合いました。',
        stickers: ['🌊', '🌅'],
        tapeColor: '#E8B4B8',
      },
    ],
    voiceTitle: '君への特別な音声メッセージ 🎙️',
    cakeMessage: '4周年記念おめでとう、アナニヤ ✨',
    wishBannerText: '願い事をしよう！ 🎂',
    wishSecretNote: '二人の愛と絆がこれからもずっと深まり続けますように。',
    treatName: 'ベルギー産ダークトリュフチョコレート 🍫',
    treatDesc: '70%ダークカカオと香ばしいローストヘーゼルナッツの贅沢な味わい。',
    insideJokeMessage: '“ピザにパイナップルを載せるのは大罪 — 二人ともよく知っているよね！”',
    timeCapsuleTitle: '二人の秘密のタイムカプセル ⏳',
    timeCapsuleMessage: '人生がどこへ向かおうとも、君への愛は永遠に変わりません。',
    customItemName: '初めてのロードトリップの思い出 🚗',
    customItemDesc: '真夜中のドライブと、丘の上で一緒に見た美しい日の出。',
    customItemTag: '大切な思い出',
    relationshipNotes: [
      'いつもガーリックブレッドを追加して、最後の一切れを取り合います。',
      '雨のドライブで車の中に流れていたお気に入りの曲。',
      '君はいつも私のセーターを着て、落ち着くと言ってくれます。',
    ],
    explosionTitle: 'サプライズギフトブラスト 💥',
    explosionSubtitle: '下のボックスをタップして、飛び出すギフトを楽しんでね！',
    explosionGifts: [
      {
        id: 'exp-1',
        title: '真紅のバラの花束 🌹',
        category: 'flower_bouquet',
        imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        caption: '二人の永遠の愛を象徴する50本の新鮮なバラ。',
        tags: ['永遠の愛', '香り'],
        reactionEmoji: '🌹',
      },
      {
        id: 'exp-2',
        title: '可愛いテディベア 🧸',
        category: 'teddy_bear',
        imageUrl: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80',
        caption: '離れている時も君を抱きしめてくれるパートナー。',
        tags: ['温かいハグ', '相棒'],
        reactionEmoji: '🧸',
      },
      {
        id: 'exp-3',
        title: 'ベルギーチョコレート 🍫',
        category: 'chocolates',
        imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
        caption: '口の中でとろける贅沢なダークチョコレート。',
        tags: ['甘い時間', '幸せ'],
        reactionEmoji: '🍫',
      },
    ],
    lastNoteTitle: '最後の秘密の手紙 (The Last Note) 📜',
    lastNoteParchment: `そして最後に、この小さな宝箱の底にたどり着いた時、ここにあるすべてが君への大きな愛のほんの一部であることを思い出してね。\n\n私と一緒に歩んでくれてありがとう。辛い時はいつでもこの箱を開けて、私の声を聞き、この手紙を読んでね。\n\n今夜は笑顔で眠ってね。`,
    lastNoteSignature: '~ 心から愛を込めて、アリヤン ❤️',
    passwordHint: '初めて出会ったバンドラのカフェの名前',
  },
};
