import { LanguageOption, SupportedLanguage } from "../types";

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    greetingSample: 'With endless love'
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिंदी',
    greetingSample: 'मेरी जान, तेरे बिना सब सूना है'
  },
  {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    greetingSample: 'माझं तुझ्यावर मनापासून प्रेम आहे'
  },
  {
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    greetingSample: 'તારું સ્મિત મારી દુનિયા છે'
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    greetingSample: 'তুমি আমার চাঁদের আলো'
  },
  {
    code: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    greetingSample: 'ਤੂੰ ਮੇਰੀ ਰੂਹ ਦਾ ਸਕੂਨ ਹੈਂ'
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    greetingSample: 'நீயே என் உயிர் மூச்சு'
  },
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    greetingSample: 'నా ప్రతి శ్వాసలో నీవే'
  },
  {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    greetingSample: 'Eres el amor de mi vida'
  },
  {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    greetingSample: 'Tu es mon trésor éternel'
  },
  {
    code: 'it',
    name: 'Italian',
    nativeName: 'Italiano',
    greetingSample: 'Sei tutta la mia vita'
  },
  {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    greetingSample: 'Du bist mein größtes Glück'
  },
  {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    greetingSample: 'أنت نبض قلبي وحبيبي'
  },
  {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    greetingSample: 'ずっとそばにいてね'
  }
];

export const UI_TRANSLATIONS: Record<SupportedLanguage, {
  unboxingTitle: string;
  unboxingSubtitle: string;
  secretGateTitle: string;
  enterPassword: string;
  unlockBox: string;
  incorrectPassword: string;
  askSenderHint: string;
  layer1Title: string;
  layer2Title: string;
  layer3Title: string;
  unwrapItem: string;
  viewMemory: string;
  listenVoice: string;
  flipScrapbook: string;
  lockedUntil: string;
  memoryBuddyTitle: string;
  memoryBuddySubtitle: string;
  translateMotherTongue: string;
  viewOriginal: string;
  emotionalIdiom: string;
}> = {
  en: {
    unboxingTitle: "Keepsake Hamper Box",
    unboxingSubtitle: "Handmade with love & precious memories",
    secretGateTitle: "Enter Secret Password to Unlock",
    enterPassword: "Enter the secret word shared by the sender...",
    unlockBox: "Unfasten Ribbon & Open Box",
    incorrectPassword: "Incorrect password. Check hint or ask your sender!",
    askSenderHint: "Hint from sender",
    layer1Title: "Layer 1: Sweet Delights & Aromas",
    layer2Title: "Layer 2: Sentimental Souvenirs & Journal",
    layer3Title: "Layer 3: The Core Vault — Heartfelt Words",
    unwrapItem: "Unwrap Surprise",
    viewMemory: "View Memory",
    listenVoice: "Play Voice Note",
    flipScrapbook: "Flip Album Pages",
    lockedUntil: "Sealed Time Capsule (Unlocks on date)",
    memoryBuddyTitle: "Memory Companion",
    memoryBuddySubtitle: "Ask anything about our shared story",
    translateMotherTongue: "Read in Mother Tongue",
    viewOriginal: "Show Original",
    emotionalIdiom: "Poetic & Cultural Idiom"
  },
  hi: {
    unboxingTitle: "यादों का खूबसूरत संदूक",
    unboxingSubtitle: "बेपनाह मोहब्बत और दिलकश पलों से सजा",
    secretGateTitle: "संदूक खोलने के लिए गुप्त पासवर्ड दर्ज करें",
    enterPassword: "सेंडर द्वारा साझा किया गया गुप्त शब्द लिखें...",
    unlockBox: "रिबन खोलें और संदूक का दीदार करें",
    incorrectPassword: "गलत पासवर्ड! कृपया हिंट देखें या सेंडर से पूछें।",
    askSenderHint: "सेंडर का गुप्त इशारा (हिंट)",
    layer1Title: "पहली परत: मीठी सौगातें और खुशबू",
    layer2Title: "दूसरी परत: यादगार तराने और स्क्रैपबुक डायरी",
    layer3Title: "भीतरी खजाना: दिल की सबसे गहरी बात",
    unwrapItem: "तोहफा खोलें",
    viewMemory: "यादें देखें",
    listenVoice: "आवाज़ सुनें",
    flipScrapbook: "डायरी के पन्ने पलटें",
    lockedUntil: "समय का ताला (मुकर्रर तारीख पर खुलेगा)",
    memoryBuddyTitle: "यादों का साथी (Memory Buddy)",
    memoryBuddySubtitle: "हमारे खूबसूरत सफर के बारे में कुछ भी पूछें",
    translateMotherTongue: "मातृभाषा में पढ़ें",
    viewOriginal: "मूल शब्द देखें",
    emotionalIdiom: "भावुक मुहावरा व शायरी का भाव"
  },
  mr: {
    unboxingTitle: "आठवणींचा सुंदर पेटी-हॅम्पार",
    unboxingSubtitle: "मनापासून जोडलेल्या प्रेमाचे अनमोल क्षण",
    secretGateTitle: "पेटी उघडण्यासाठी गुपित पासवर्ड टाका",
    enterPassword: "पाठवणाऱ्याने दिलेला पासवर्ड येथे टाका...",
    unlockBox: "रेशमी रिबन सोडा आणि पेटी उघडा",
    incorrectPassword: "चुकलेला पासवर्ड! कृपया हिंट तपासा.",
    askSenderHint: "खास आठवणीचा इशारा",
    layer1Title: "पहिली पायरी: गोड भेटवस्तू आणि सुगंध",
    layer2Title: "दुसरी पायरी: आठवणींची फोटो डायरी",
    layer3Title: "गाभ्यातील खजिना: मनातील खोल भावनांचे पत्र",
    unwrapItem: "भेट उघडा",
    viewMemory: "क्षणचित्रे पहा",
    listenVoice: "आवाज ऐका",
    flipScrapbook: "डायरीची पाने उलटा",
    lockedUntil: "वेळेचे रहस्य (विशिष्ट तारखेला उघडेल)",
    memoryBuddyTitle: "आपला आठवणींचा सखा",
    memoryBuddySubtitle: "आपल्या सुंदर प्रवासाबद्दल बोला",
    translateMotherTongue: "मराठीत वाचा",
    viewOriginal: "मूळ मजकूर पहा",
    emotionalIdiom: "हृदयस्पर्शी शब्दरचना"
  },
  gu: {
    unboxingTitle: "યાદોનો મનોહર બોક્સ",
    unboxingSubtitle: "પ્રેમ અને અણમોલ પળોની ભેટ",
    secretGateTitle: "બોક્સ ખોલવા માટે ગુપ્ત પાસવર્ડ દાખલ કરો",
    enterPassword: "મોકલનાર દ્વારા આપેલો પાસવર્ડ લખો...",
    unlockBox: "રીબન ખોલો અને બોક્સ ઉઘાડો",
    incorrectPassword: "ખોટો પાસવર્ડ! કૃપા કરીને સંકેત જુઓ.",
    askSenderHint: "મોકલનારનો સંકેત",
    layer1Title: "પહેલો ભાગ: મીઠાશ અને સુગંધ",
    layer2Title: "બીજો ભાગ: સ્મૃતિઓની ડાયરી",
    layer3Title: "મુખ્ય ખજાનો: હૃદયપૂર્વક લખેલો પત્ર",
    unwrapItem: "ઉપહાર ખોલો",
    viewMemory: "યાદો જુઓ",
    listenVoice: "અવાજ સાંભળો",
    flipScrapbook: "ડાયરીના પાના ફેરવો",
    lockedUntil: "સમય કેપ્સ્યુલ (નક્કી કરેલ તારીખે ખુલશે)",
    memoryBuddyTitle: "યાદોનો સાથીદાર",
    memoryBuddySubtitle: "આપણી સફર વિશે વાત કરો",
    translateMotherTongue: "માતૃભાષામાં વાંચો",
    viewOriginal: "મૂળ લખાણ જુઓ",
    emotionalIdiom: "ભાવનાત્મક શબ્દપ્રયોગ"
  },
  bn: {
    unboxingTitle: "স্মৃতির বাক্স",
    unboxingSubtitle: "ভালোবাসা ও অনুভূতির অপূর্ব উপহার",
    secretGateTitle: "খোলার জন্য গোপন পাসওয়ার্ড দিন",
    enterPassword: "গোপন শব্দ লিখুন...",
    unlockBox: "ফিতা খুলে বাক্স উন্মোচন করুন",
    incorrectPassword: "ভুল পাসওয়ার্ড! সংকেতটি দেখুন।",
    askSenderHint: "গোপন সংকেত",
    layer1Title: "প্রথম স্তর: মিষ্টি উপহার ও সুবাস",
    layer2Title: "দ্বিতীয় স্তর: স্মৃতির ডায়রি",
    layer3Title: "অন্তরের উপহার: হৃদয়ের চিঠি",
    unwrapItem: "উপহার খুলুন",
    viewMemory: "ছবি দেখুন",
    listenVoice: "কণ্ঠ শুনুন",
    flipScrapbook: "পৃষ্ঠা উল্টান",
    lockedUntil: "টাইম ক্যাপসুল (নির্দিষ্ট দিনে খুলবে)",
    memoryBuddyTitle: "স্মৃতির সহচর",
    memoryBuddySubtitle: "আমাদের ভালোবাসা নিয়ে জিজ্ঞাসা করুন",
    translateMotherTongue: "মাতৃভাষায় পড়ুন",
    viewOriginal: "মূল লেখা",
    emotionalIdiom: "কাব্যিক ভাবার্থ"
  },
  pa: {
    unboxingTitle: "ਯਾਦਾਂ ਦਾ ਖ਼ਜ਼ਾਨਾ",
    unboxingSubtitle: "ਸੱਚੇ ਦਿਲੋਂ ਬਣਾਇਆ ਤੋਹਫ਼ਾ",
    secretGateTitle: "ਖੋਲ੍ਹਣ ਲਈ ਗੁਪਤ ਪਾਸਵਰਡ ਭਰੋ",
    enterPassword: "ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ...",
    unlockBox: "ਰਿਬਨ ਖੋਲ੍ਹੋ ਤੇ ਤੋਹਫ਼ਾ ਵੇਖੋ",
    incorrectPassword: "ਗ਼ਲਤ ਪਾਸਵਰਡ! ਕਿਰਪਾ ਕਰਕੇ ਇਸ਼ਾਰਾ ਵੇਖੋ।",
    askSenderHint: "ਸੇਂਡਰ ਦਾ ਇਸ਼ਾਰਾ",
    layer1Title: "ਪਹਿਲੀ ਪਰਤ: ਮਿਠਾਸ ਤੇ ਖ਼ੁਸ਼ਬੋ",
    layer2Title: "ਦੂਜੀ ਪਰਤ: ਯਾਦਗਾਰ ਤਸਵੀਰਾਂ",
    layer3Title: "ਅਸਲ ਤੋਹਫ਼ਾ: ਦਿਲੋਂ ਲਿਖੀ ਚਿੱਠੀ",
    unwrapItem: "ਤੋਹਫ਼ਾ ਖੋਲ੍ਹੋ",
    viewMemory: "ਯਾਦਾਂ ਵੇਖੋ",
    listenVoice: "ਆਵਾਜ਼ ਸੁਣੋ",
    flipScrapbook: "ਡਾਇਰੀ ਦੇ ਪੰਨੇ ਪਲਟੋ",
    lockedUntil: "ਸਮੇਂ ਦਾ ਤਾਲਾ",
    memoryBuddyTitle: "ਯਾਦਾਂ ਦਾ ਹਮਸਫ਼ਰ",
    memoryBuddySubtitle: "ਸਾਡੇ ਪਿਆਰ ਬਾਰੇ ਪੁੱਛੋ",
    translateMotherTongue: "ਮਾਂ-ਬੋਲੀ 'ਚ ਪੜ੍ਹੋ",
    viewOriginal: "ਅਸਲ ਚਿੱਠੀ",
    emotionalIdiom: "ਰੂਹਾਨੀ ਭਾਵਨਾ"
  },
  ta: {
    unboxingTitle: "நினைவுகளின் பெட்டகம்",
    unboxingSubtitle: "இதயப்பூர்வமான நினைவுகளின் தொகுப்பு",
    secretGateTitle: "திறக்க ரகசிய கடவுச்சொல்லை உள்ளிடவும்",
    enterPassword: "ரகசிய சொல்லை உள்ளிடவும்...",
    unlockBox: "ரிப்பனை அவிழ்த்து பெட்டியை திறக்கவும்",
    incorrectPassword: "தவறான கடவுச்சொல்! குறிப்பை பார்க்கவும்.",
    askSenderHint: "ரகசிய குறிப்பு",
    layer1Title: "முதல் அடுக்கு: இனிய பரிசுகள்",
    layer2Title: "இரண்டாம் அடுக்கு: புகைப்பட ஆல்பம்",
    layer3Title: "மைய பெட்டகம்: காதல் கடிதம்",
    unwrapItem: "பரிசை திற",
    viewMemory: "நினைவுகளை காண்",
    listenVoice: "குரலை கேள்",
    flipScrapbook: "பக்கங்களை திருப்பு",
    lockedUntil: "காலப் பெட்டகம்",
    memoryBuddyTitle: "நினைவு தோழன்",
    memoryBuddySubtitle: "நம் கதையை பற்றி கேளுங்கள்",
    translateMotherTongue: "தாய்மொழியில் வாசி",
    viewOriginal: "அசல் வடிவம்",
    emotionalIdiom: "கவித்துவ உணர்வு"
  },
  te: {
    unboxingTitle: "మధుర జ్ఞాపకాల పేటిక",
    unboxingSubtitle: "అనంతమైన ప్రేమతో నిండిన బహుమతి",
    secretGateTitle: "తెరవడానికి రహస్య పాస్‌వర్డ్ నమోదు చేయండి",
    enterPassword: "రహస్య పదం నమోదు చేయండి...",
    unlockBox: "రిబ్బన్ విప్పి పేటికను తెరవండి",
    incorrectPassword: "తప్పు పాస్‌వర్డ్! సూచనను చూడండి.",
    askSenderHint: "రహస్య సూచన",
    layer1Title: "మొదటి అంచె: తీపి కానుకలు",
    layer2Title: "రెండవ అంచె: జ్ఞాపకాల డైరీ",
    layer3Title: "అంతరంగం: హృదయపూర్వక లేఖ",
    unwrapItem: "కానుకను విప్పండి",
    viewMemory: "జ్ఞాపకాలు చూడండి",
    listenVoice: "వాయిస్ వినండి",
    flipScrapbook: "పేజీలు తిప్పండి",
    lockedUntil: "టైమ్ క్యాప్సూల్",
    memoryBuddyTitle: "జ్ఞాపకాల నేస్తం",
    memoryBuddySubtitle: "మన ప్రయాణం గురించి అడగండి",
    translateMotherTongue: "మాతృభాషలో చదవండి",
    viewOriginal: "అసలు లేఖ",
    emotionalIdiom: "భావోద్వేగ అర్థం"
  },
  es: {
    unboxingTitle: "Cofre de Recuerdos Inolvidables",
    unboxingSubtitle: "Hecho a mano con amor y devoción",
    secretGateTitle: "Ingresa la Contraseña Secreta para Abrir",
    enterPassword: "Escribe la palabra secreta compartida...",
    unlockBox: "Desatar Lazo y Abrir Cofre",
    incorrectPassword: "Contraseña incorrecta. ¡Revisa la pista!",
    askSenderHint: "Pista del remitente",
    layer1Title: "Capa 1: Delicias Dulces y Aromas",
    layer2Title: "Capa 2: Recuerdos y Álbum de Fotos",
    layer3Title: "Capa 3: El Núcleo — Carta del Alma",
    unwrapItem: "Desenvolver Regalo",
    viewMemory: "Ver Recuerdo",
    listenVoice: "Escuchar Nota de Voz",
    flipScrapbook: "Pasar Páginas",
    lockedUntil: "Cápsula del Tiempo Sellada",
    memoryBuddyTitle: "Compañero de Recuerdos",
    memoryBuddySubtitle: "Pregúntame sobre nuestra historia de amor",
    translateMotherTongue: "Leer en tu idioma materno",
    viewOriginal: "Ver Original",
    emotionalIdiom: "Expresión Poética y Cultural"
  },
  fr: {
    unboxingTitle: "Boîte à Souvenirs Précieux",
    unboxingSubtitle: "Faite à la main avec amour et tendresse",
    secretGateTitle: "Entrez le Mot de Passe Secret pour Déverrouiller",
    enterPassword: "Entrez le mot secret partagé...",
    unlockBox: "Dénouer le Ruban et Ouvrir",
    incorrectPassword: "Mot de passe incorrect. Vérifiez l'indice !",
    askSenderHint: "Indice de l'expéditeur",
    layer1Title: "Couche 1: Douceurs et Parfums",
    layer2Title: "Couche 2: Journal & Galerie de Souvenirs",
    layer3Title: "Couche 3: Le Trésor — Lettre du Cœur",
    unwrapItem: "Déballer la Surprise",
    viewMemory: "Voir le Souvenir",
    listenVoice: "Écouter le Message Vocal",
    flipScrapbook: "Tourner les Pages",
    lockedUntil: "Capsule Temporelle Scellée",
    memoryBuddyTitle: "Compagnon de Mémoire",
    memoryBuddySubtitle: "Posez-moi des questions sur notre histoire",
    translateMotherTongue: "Lire dans votre langue",
    viewOriginal: "Afficher l'Original",
    emotionalIdiom: "Élégance Poétique"
  },
  it: {
    unboxingTitle: "Scrigno dei Ricordi Preziosi",
    unboxingSubtitle: "Fatto a mano con amore infinito",
    secretGateTitle: "Inserisci la Password Segreta per Aprire",
    enterPassword: "Scrivi la parola segreta...",
    unlockBox: "Sciogli il Nastro e Apri lo Scrigno",
    incorrectPassword: "Password errata. Controlla l'indizio!",
    askSenderHint: "Indizio del mittente",
    layer1Title: "Livello 1: Dolcezze e Profumi",
    layer2Title: "Livello 2: Diario e Ricordi",
    layer3Title: "Livello 3: Il Cuore — Lettera d'Amore",
    unwrapItem: "Scarta il Regalo",
    viewMemory: "Vedi Ricordo",
    listenVoice: "Ascolta il Messaggio Vocale",
    flipScrapbook: "Sfoglia l'Album",
    lockedUntil: "Capsula del Tempo Sigillata",
    memoryBuddyTitle: "Custode dei Ricordi",
    memoryBuddySubtitle: "Chiedimi qualsiasi cosa sulla nostra storia",
    translateMotherTongue: "Leggi nella tua lingua",
    viewOriginal: "Mostra Originale",
    emotionalIdiom: "Espressione Poetica"
  },
  de: {
    unboxingTitle: "Schatztruhe der Erinnerungen",
    unboxingSubtitle: "Handgefertigt mit Liebe und Zuneigung",
    secretGateTitle: "Geheimes Passwort eingeben zum Entsperren",
    enterPassword: "Geheimwort eingeben...",
    unlockBox: "Schleife lösen & Truhe öffnen",
    incorrectPassword: "Falsches Passwort. Prüfe den Hinweis!",
    askSenderHint: "Hinweis des Absenders",
    layer1Title: "Ebene 1: Süße Freuden & Düfte",
    layer2Title: "Ebene 2: Fotoalbum & Souvenirs",
    layer3Title: "Ebene 3: Der Kern — Brief aus tiefstem Herzen",
    unwrapItem: "Geschenk auspacken",
    viewMemory: "Erinnerung ansehen",
    listenVoice: "Sprachnachricht anhören",
    flipScrapbook: "Seiten umblättern",
    lockedUntil: "Versiegelte Zeitkapsel",
    memoryBuddyTitle: "Erinnerungs-Begleiter",
    memoryBuddySubtitle: "Frag mich nach unseren gemeinsamen Momenten",
    translateMotherTongue: "In Muttersprache lesen",
    viewOriginal: "Original anzeigen",
    emotionalIdiom: "Gefühlvoller Ausdruck"
  },
  ar: {
    unboxingTitle: "صندوق الذكريات النفيسة",
    unboxingSubtitle: "صنع بكل حب ووفاء لقلبك",
    secretGateTitle: "أدخل كلمة السر الخاصة لفتح الصندوق",
    enterPassword: "اكتب الكلمة السرية المشتركة...",
    unlockBox: "فك الشريط الحريري وافتح الصندوق",
    incorrectPassword: "كلمة السر غير صحيحة! تأكد من التلميح.",
    askSenderHint: "تلميح المرسل",
    layer1Title: "الطبقة الأولى: حلوى وعطور دافئة",
    layer2Title: "الطبقة الثانية: ألبوم الذكريات المشتركة",
    layer3Title: "الكنز الداخلي: رسالة الروح الصادقة",
    unwrapItem: "افتح الهدية",
    viewMemory: "مشاهدة الذكرى",
    listenVoice: "استمع للتسجيل الصوتي",
    flipScrapbook: "تصفح صفحات الدفتر",
    lockedUntil: "كبسولة زمنية مغلقة",
    memoryBuddyTitle: "رفيق الذكريات",
    memoryBuddySubtitle: "اسألني عن أجمل أوقاتنا معاً",
    translateMotherTongue: "اقرأ بلغتك الأم",
    viewOriginal: "عرض النص الأصلي",
    emotionalIdiom: "تعبير شعري وعاطفي"
  },
  ja: {
    unboxingTitle: "想い出の宝石箱 (MemoryBox)",
    unboxingSubtitle: "心からの愛と大切な記憶を込めて",
    secretGateTitle: "開けるための秘密の合言葉を入力",
    enterPassword: "送り主と共有した合言葉を入力...",
    unlockBox: "リボンを解いて箱を開ける",
    incorrectPassword: "合言葉が違います。ヒントをご確認ください。",
    askSenderHint: "送り主からのヒント",
    layer1Title: "第1層: 甘いお菓子と香りの贈り物",
    layer2Title: "第2層: 二人の思い出スクラップブック",
    layer3Title: "最深部: 心を込めた直筆の手紙",
    unwrapItem: "包みを開ける",
    viewMemory: "思い出を見る",
    listenVoice: "音声メッセージを聴く",
    flipScrapbook: "アルバムをめくる",
    lockedUntil: "タイムカプセル (指定日まで封印)",
    memoryBuddyTitle: "思い出のコンパニオン",
    memoryBuddySubtitle: "二人の思い出について何でも聞いてね",
    translateMotherTongue: "母国語で読む",
    viewOriginal: "元の文章を表示",
    emotionalIdiom: "心温まる表現"
  }
};

export interface CreatorStudioTranslation {
  studioTitle: string;
  studioSubtitle: string;
  languageSelectLabel: string;
  tabs: {
    workshop: string;
    basics: string;
    whySpecial?: string;
    vortexHeart?: string;
    letter: string;
    scrapbook: string;
    voice: string;
    cake?: string;
    delights: string;
    customMemory: string;
    giftBlast?: string;
    lastNote?: string;
    seal: string;
  };
  tableWorkshop: {
    title: string;
    subtitle: string;
    beddingTitle: string;
    beddingSubtitle: string;
    scatterBeddingBtn: string;
    tagTitle: string;
    tagSubtitle: string;
    stickersTitle: string;
    stickersSubtitle: string;
    aromaTitle: string;
    aromaSubtitle: string;
  };
  basics: {
    boxTitleLabel: string;
    boxTitlePlaceholder: string;
    recipientLabel: string;
    recipientPlaceholder: string;
    senderLabel: string;
    senderPlaceholder: string;
    occasionLabel: string;
    themeLabel: string;
    passwordLabel: string;
    passwordPlaceholder: string;
    passwordHintLabel: string;
    passwordHintPlaceholder: string;
    waxSealLabel: string;
  };
  letter: {
    title: string;
    aiHelperTitle: string;
    aiHelperDesc: string;
    toneLabel: string;
    memoriesPromptLabel: string;
    memoriesPromptPlaceholder: string;
    generateLetterBtn: string;
    generatingLetter: string;
    letterTitlePlaceholder: string;
    letterContentPlaceholder: string;
    paperStyleLabel: string;
  };
  scrapbook: {
    title: string;
    subtitle: string;
    addPhotoBtn: string;
    photoCaptionPlaceholder: string;
    photoDatePlaceholder: string;
    photoNotePlaceholder: string;
    washiTapeLabel: string;
  };
  voice: {
    title: string;
    subtitle: string;
    recordBtn: string;
    stopBtn: string;
    recording: string;
    noteTitlePlaceholder: string;
    transcriptPlaceholder: string;
  };
  delights: {
    title: string;
    subtitle: string;
    treatLabel: string;
    insideJokePlaceholder: string;
    capsuleTitle: string;
    capsuleDateLabel: string;
    capsuleMessagePlaceholder: string;
  };
  customMemory: {
    customItemTitle: string;
    customItemPlaceholder: string;
    customItemTagPlaceholder: string;
    memoryBuddyTrainerTitle: string;
    memoryBuddyTrainerSubtitle: string;
    memoryInputPlaceholder: string;
    addMemoryBtn: string;
  };
  saveAndSealBtn: string;
  savingBox: string;
  cancelBtn: string;
}

export const CREATOR_STUDIO_TRANSLATIONS: Record<SupportedLanguage, CreatorStudioTranslation> = {
  en: {
    studioTitle: "Artisan Gift Creator Studio",
    studioSubtitle: "Handcraft a personalized emotional virtual keepsake hamper for your loved one",
    languageSelectLabel: "Crafting Language (आपकी भाषा):",
    tabs: {
      workshop: "Packing Table",
      basics: "Basics & Lock",
      whySpecial: "Why Special?",
      vortexHeart: "Vortex Heart",
      letter: "AI Love Letter",
      scrapbook: "Photo Scrapbook",
      voice: "Voice Note",
      cake: "Celebration Cake",
      delights: "Treats & Delights",
      customMemory: "Souvenir & AI",
      giftBlast: "Gift Blast",
      lastNote: "The Last Note",
      seal: "Seal & Share",
    },
    tableWorkshop: {
      title: "Interactive Virtual Gift Packing Table",
      subtitle: "Click items to pack texture, fragrance, tags, and stickers into your open box",
      beddingTitle: "Shredded Paper Bedding",
      beddingSubtitle: "Scatter soft crinkle paper shavings inside the box base",
      scatterBeddingBtn: "Scatter Paper Bedding",
      tagTitle: "Calligraphy Gift Tag & Twine",
      tagSubtitle: "Tie a handwritten parchment tag onto the satin ribbon",
      stickersTitle: "Aesthetic Stamp Stickers & Washi",
      stickersSubtitle: "Stamp seals & inside joke emblems onto keepsakes",
      aromaTitle: "Aroma Scent & Atmosphere",
      aromaSubtitle: "Choose the floating ambient fragrance and particle mood",
    },
    basics: {
      boxTitleLabel: "Hamper Box Title",
      boxTitlePlaceholder: "e.g. To My Forever Love — 4th Anniversary Keepsake",
      recipientLabel: "Recipient's Name (Who is this for?)",
      recipientPlaceholder: "e.g. Ananya / Priya / Alex",
      senderLabel: "Your Name (Sender)",
      senderPlaceholder: "e.g. Aryan / Rohan / Sam",
      occasionLabel: "Celebration Occasion",
      themeLabel: "Trunk Leather & Ribbon Velvet Theme",
      passwordLabel: "Secret Word Gate Password (Optional)",
      passwordPlaceholder: "e.g. ourfirstcoffee (leave blank for instant unbox)",
      passwordHintLabel: "Secret Whisper Hint for Recipient",
      passwordHintPlaceholder: "e.g. Where we sat for 4 hours on our first rainy date...",
      waxSealLabel: "Wax Seal Monogram Initials",
    },
    letter: {
      title: "Handwritten Parchment Letter",
      aiHelperTitle: "Gemini AI Love Letter Muse",
      aiHelperDesc: "Let AI weave your real memories into an evocative, tearfully romantic letter in your language",
      toneLabel: "Emotional Tone & Atmosphere",
      memoriesPromptLabel: "Key Memories & Nicknames to weave in",
      memoriesPromptPlaceholder: "e.g. That rainy Tuesday at the coffee shop, burning the pasta on our 1st anniversary, dancing in Lonavala...",
      generateLetterBtn: "Draft Soulful Letter with Gemini AI",
      generatingLetter: "Composing heartfelt words in your chosen language...",
      letterTitlePlaceholder: "Letter Title (e.g. An Eternal Promise To You)",
      letterContentPlaceholder: "Write your heart out, or let Gemini AI help you craft the perfect words...",
      paperStyleLabel: "Parchment Sheet Style",
    },
    scrapbook: {
      title: "Polaroid Memory Scrapbook",
      subtitle: "Tilted photos with washi tapes, handwritten cursive dates, and nostalgic stories",
      addPhotoBtn: "Add Another Polaroid Snapshot",
      photoCaptionPlaceholder: "Cursive photo caption (e.g. The day the world stood still...)",
      photoDatePlaceholder: "Date / Moment (e.g. October 14, 2021)",
      photoNotePlaceholder: "The memory behind this snapshot...",
      washiTapeLabel: "Pastel Washi Tape",
    },
    voice: {
      title: "Vintage Cassette Voice Note",
      subtitle: "Record your real voice directly from your browser so they can hear your heartbeat",
      recordBtn: "Start Recording Real Voice",
      stopBtn: "Stop & Save Voice Note",
      recording: "Recording in progress...",
      noteTitlePlaceholder: "Audio Title (e.g. A Spoken Whisper for You)",
      transcriptPlaceholder: "Spoken transcript / note preview for your voice message...",
    },
    delights: {
      title: "Sweet Treats, Inside Jokes & Time Capsule",
      subtitle: "Artisanal chocolates, secret jokes revealed on unwrap, and milestone countdown locks",
      treatLabel: "Treat / Delight Selection",
      insideJokePlaceholder: "Secret Inside Joke revealed on unwrap (e.g. 'Pineapple on pizza is a crime!')",
      capsuleTitle: "Milestone Time-Capsule Vault",
      capsuleDateLabel: "Lock Vault Until (Future Date / Milestone)",
      capsuleMessagePlaceholder: "Secret milestone message / concert tickets revealed in the future...",
    },
    customMemory: {
      customItemTitle: "Custom Souvenir Keepsake Badge",
      customItemPlaceholder: "Unique Item Name (e.g. Our First Coffee Cup, Ticket Stubs)",
      customItemTagPlaceholder: "Short Tag (e.g. Where everything began)",
      memoryBuddyTrainerTitle: "Memory Buddy AI Relationship Trainer",
      memoryBuddyTrainerSubtitle: "Type your private anecdotes to train the recipient's interactive AI companion",
      memoryInputPlaceholder: "Add an inside joke, anniversary memory, or cute habit...",
      addMemoryBtn: "Add Memory Anecdote",
    },
    saveAndSealBtn: "Seal Keepsake Hamper & Generate Share Link",
    savingBox: "Polishing and sealing your handmade hamper...",
    cancelBtn: "Cancel & Return",
  },
  hi: {
    studioTitle: "तोहफ़ा निर्माण स्टूडियो (Artisan Creator Studio)",
    studioSubtitle: "अपने अज़ीज़ के लिए दिल से बना एक खूबसूरत, भावनात्मक डिजिटल संदूक तैयार करें",
    languageSelectLabel: "निर्माण की भाषा (Crafting Language):",
    tabs: {
      workshop: "पैकिंग टेबल",
      basics: "बुनियाद व ताला",
      whySpecial: "खासियत व वजह",
      vortexHeart: "3D दिल का जादू",
      letter: "AI प्रेम पत्र",
      scrapbook: "यादों की डायरी",
      voice: "आवाज़ का पैगाम",
      cake: "सेलिब्रेशन केक",
      delights: "मीठी सौगातें",
      customMemory: "निशानी व AI",
      giftBlast: "गिफ्ट ब्लास्ट",
      lastNote: "अंतिम गुप्त पैगाम",
      seal: "सील व शेयर",
    },
    tableWorkshop: {
      title: "असली पैकिंग का मज़ा (Interactive Virtual Gift Table)",
      subtitle: "संदूक में खुशबू, कागज़ी कतरनें, रिबन टैग और स्टिकर सजाने के लिए क्लिक करें",
      beddingTitle: "कागज़ की मुलायम कतरनें (Paper Bedding)",
      beddingSubtitle: "संदूक के तल में सजावटी रंगीन कतरनें बिखेरें",
      scatterBeddingBtn: "कतरनें बिखेरें (Scatter Bedding)",
      tagTitle: "सुलेखन कार्ड टैग व डोरी (Gift Tag)",
      tagSubtitle: "रेशमी रिबन पर हाथ से लिखा नाम टैग बांधें",
      stickersTitle: "प्यारे स्टिकर्स और वाशी टेप (Stickers)",
      stickersSubtitle: "तोहफ़ों पर सील और गुप्त इशारों के स्टिकर चिपकाएं",
      aromaTitle: "सुगंध व रूहानी माहौल (Aroma Mood)",
      aromaSubtitle: "संदूक की खुशबू और उड़ती पंखुड़ियों का मिज़ाज चुनें",
    },
    basics: {
      boxTitleLabel: "संदूक का शीर्षक (Title)",
      boxTitlePlaceholder: "उदा. मेरी जान के नाम — चौथी सालगिरह की सौगात",
      recipientLabel: "किसके लिए है? (पाने वाले का नाम)",
      recipientPlaceholder: "उदा. अनन्या / प्रिया / सिमरन",
      senderLabel: "आपका नाम (भेजने वाला)",
      senderPlaceholder: "उदा. आर्यन / रोहन / कबीर",
      occasionLabel: "खास मौका (Occasion)",
      themeLabel: "संदूक का लेदर व मखमली रिबन रंग",
      passwordLabel: "गुप्त पासवर्ड (अगर ताला लगाना चाहें)",
      passwordPlaceholder: "उदा. ourfirstcoffee (खाली छोड़ने पर सीधे खुलेगा)",
      passwordHintLabel: "पासवर्ड का गुप्त इशारा (Hint)",
      passwordHintPlaceholder: "उदा. वो कैफ़े जहाँ हम पहली बार ४ घंटे तक बातें करते रहे...",
      waxSealLabel: "मोम की सील के शुरुआती अक्षर (Initials)",
    },
    letter: {
      title: "हाथ से लिखा दिलकश ख़त (Parchment Letter)",
      aiHelperTitle: "Gemini AI दिल की बात लेखक",
      aiHelperDesc: "अपनी यादों को अपनी भाषा में एक बेहद भावुक, शायराना और दिल को छू लेने वाले ख़त में बदलें",
      toneLabel: "ख़त का अंदाज़ व भावना",
      memoriesPromptLabel: "ख़ास यादें व नाम जो ख़त में शामिल करने हैं",
      memoriesPromptPlaceholder: "उदा. बांद्रा के कैफ़े की वो बारिश, पहली सालगिरह पर जला हुआ पास्ता, लोनावला का वो हसीन सफर...",
      generateLetterBtn: "Gemini AI से खूबसूरत ख़त लिखवाएं",
      generatingLetter: "आपकी मातृभाषा में दिलकश अल्फ़ाज़ पिरोए जा रहे हैं...",
      letterTitlePlaceholder: "ख़त का शीर्षक (उदा. तुमसे ही मेरी हर सुबह है)",
      letterContentPlaceholder: "अपने दिल के जज़्बात लिखें, या AI से मदद लें...",
      paperStyleLabel: "कागज़ की बनावट (Paper Style)",
    },
    scrapbook: {
      title: "यादों की पोलरॉइड डायरी (Scrapbook)",
      subtitle: "रंगीन वाशी टेप, खूबसूरत तारीखों और दिलकश यादों के साथ तस्वीरें सजाएं",
      addPhotoBtn: "नई पोलरॉइड तस्वीर जोड़ें",
      photoCaptionPlaceholder: "तस्वीर की शायरी या पंक्ति (उदा. वो शाम जब वक्त ठहर गया था...)",
      photoDatePlaceholder: "तारीख / पल (उदा. १४ अक्टूबर, २०२१)",
      photoNotePlaceholder: "इस तस्वीर के पीछे की अनमोल कहानी...",
      washiTapeLabel: "पेस्टल वाशी टेप",
    },
    voice: {
      title: "विंटेज कैसेट पर आवाज़ का पैगाम (Voice Note)",
      subtitle: "अपनी असली आवाज़ रिकॉर्ड करें ताकि वे जब भी चाहें आपकी धड़कनें सुन सकें",
      recordBtn: "असली आवाज़ रिकॉर्ड करें",
      stopBtn: "रोकें और सुरक्षित करें",
      recording: "रिकॉर्डिंग जारी है...",
      noteTitlePlaceholder: "ऑडियो का नाम (उदा. तेरे लिए एक सरगोशी)",
      transcriptPlaceholder: "बोले गए शब्दों का सारांश...",
    },
    delights: {
      title: "मीठी सौगातें, गुप्त मज़ाक और समय का ताला",
      subtitle: "स्वादिष्ट चॉकलेट्स, तोहफ़े के अंदर छुपा मज़ाक, और भविष्य में खुलने वाला ताला",
      treatLabel: "तोहफ़े का चुनाव (चॉकलेट्स/टेडी)",
      insideJokePlaceholder: "तोहफ़ा खोलने पर दिखने वाला गुप्त मज़ाक (उदा. 'पिज्जा पर अनानास सच में गुनाह है!')",
      capsuleTitle: "टाइम कैप्सूल (Time Capsule Lock)",
      capsuleDateLabel: "यह तोहफ़ा किस तारीख को खुलेगा?",
      capsuleMessagePlaceholder: "भविष्य के लिए छुपाया गया सरप्राइज संदेश...",
    },
    customMemory: {
      customItemTitle: "खास निशानी का बैज (Custom Souvenir)",
      customItemPlaceholder: "निशानी का नाम (उदा. हमारी पहली कॉफ़ी का कप, मूवी के टिकट)",
      customItemTagPlaceholder: "छोटा सा टैग (उदा. जहाँ से सब शुरू हुआ)",
      memoryBuddyTrainerTitle: "Memory Buddy AI को अपनी कहानियाँ सिखाएं",
      memoryBuddyTrainerSubtitle: "अपनी निजी यादें लिखें ताकि चैटबॉट ठीक आपके अंदाज़ में जवाब दे सके",
      memoryInputPlaceholder: "कोई प्यारी आदत, निकनेम या यादगार किस्सा जोड़ें...",
      addMemoryBtn: "याद जोड़ें (Add Memory)",
    },
    saveAndSealBtn: "संदूक को मोम से सील करें और लिंक बनाएं",
    savingBox: "संदूक को रेशमी धागों से सजाया जा रहा है...",
    cancelBtn: "रद्द करें और वापस जाएं",
  },
  mr: {
    studioTitle: "भेटवस्तू निर्मिती स्टुडिओ (Creator Studio)",
    studioSubtitle: "आपल्या प्रिय व्यक्तीसाठी मनापासून सजवलेली अनमोल डिजिटल पेटी तयार करा",
    languageSelectLabel: "निर्मितीची भाषा (Crafting Language):",
    tabs: {
      workshop: "पॅकिंग टेबल",
      basics: "माहिती व कुलूप",
      whySpecial: "खास का आहे?",
      vortexHeart: "3D हार्ट जादू",
      letter: "AI प्रेमपत्र",
      scrapbook: "आठवणींची डायरी",
      voice: "आवाजाचा निरोप",
      cake: "केक व शुभेच्छा",
      delights: "गोड भेट",
      customMemory: "आठवण व AI",
      giftBlast: "गिफ्ट ब्लास्ट",
      lastNote: "शेवटची गुप्त चिठ्ठी",
      seal: "सील व शेअर",
    },
    tableWorkshop: {
      title: "प्रत्यक्ष पॅकिंगचा आनंद (Virtual Gift Table)",
      subtitle: "पेटीमध्ये सुगंध, कागदी तुकडे, रिबन टॅग आणि स्टिकर्स सजवण्यासाठी क्लिक करा",
      beddingTitle: "मऊ कागदी कतरण (Shredded Bedding)",
      beddingSubtitle: "पेटीच्या तळाशी सुंदर रंगीत कतरण पसरा",
      scatterBeddingBtn: "कतरण पसरा (Scatter Bedding)",
      tagTitle: "सुलेखन टॅग आणि दोरा (Gift Tag)",
      tagSubtitle: "रेशमी रिबनवर नावाची सुंदर पाटी बांधा",
      stickersTitle: "आकर्षक स्टिकर्स (Stickers)",
      stickersSubtitle: "भेटवस्तूंवर खास खुणांचे स्टिकर्स चिकटवा",
      aromaTitle: "सुगंध आणि वातावरण (Aroma Mood)",
      aromaSubtitle: "पेटीचा सुगंध आणि हवेत तरंगणाऱ्या पाकळ्यांची निवड करा",
    },
    basics: {
      boxTitleLabel: "पेटीचे नाव (Hamper Title)",
      boxTitlePlaceholder: "उदा. माझ्या प्रियेसाठी — ४ वर्षांच्या प्रेमाची आठवण",
      recipientLabel: "कोणासाठी आहे? (नाव)",
      recipientPlaceholder: "उदा. अनघा / तन्वी / सिया",
      senderLabel: "आपले नाव (पाठवणारा)",
      senderPlaceholder: "उदा. रोहन / पार्थ / अमेय",
      occasionLabel: "विशेष प्रसंग (Occasion)",
      themeLabel: "पेटीचा मखमली रंग व रिबन",
      passwordLabel: "गुप्त पासवर्ड (इच्छा असल्यास)",
      passwordPlaceholder: "उदा. ourfirstcoffee (रिकामे ठेवल्यास थेट उघडेल)",
      passwordHintLabel: "पासवर्डचा खास इशारा (Hint)",
      passwordHintPlaceholder: "उदा. आपण पहिल्यांदा ज्या कॅफेमध्ये ४ तास बसलो होतो...",
      waxSealLabel: "सीलवरील आद्याक्षरे (Initials)",
    },
    letter: {
      title: "हस्तलिखित सुंदर पत्र (Parchment Letter)",
      aiHelperTitle: "Gemini AI प्रेमपत्र सहाय्यक",
      aiHelperDesc: "आपल्या आठवणींचे रूपांतर मराठीतील अत्यंत भावुक आणि रोमँटिक पत्रात करा",
      toneLabel: "पत्राचा भाव व सूर",
      memoriesPromptLabel: "पत्रात समाविष्ट करायच्या खास आठवणी",
      memoriesPromptPlaceholder: "उदा. पहिल्या पावसातील ती भेट, वाढदिवसाची गंमत, लोणावळ्याची ती सुंदर संध्याकाळ...",
      generateLetterBtn: "Gemini AI द्वारे सुंदर पत्र तयार करा",
      generatingLetter: "हृदयस्पर्शी शब्दरचना तयार होत आहे...",
      letterTitlePlaceholder: "पत्राचे शीर्षक (उदा. तुझ्या असण्याने जीवन सुंदर आहे)",
      letterContentPlaceholder: "आपल्या मनातील भावना लिहा...",
      paperStyleLabel: "कागदाची शैली (Paper Style)",
    },
    scrapbook: {
      title: "आठवणींची पोलरॉइड डायरी (Scrapbook)",
      subtitle: "रंगीत वाशी टेप आणि हस्तलिखित नोंदींसह सुंदर फोटो सजवा",
      addPhotoBtn: "नवीन फोटो जोडा",
      photoCaptionPlaceholder: "फोटोवरील सुंदर ओळ (उदा. तो क्षण जेव्हा वेळ थांबली होती...)",
      photoDatePlaceholder: "तारीख / प्रसंग (उदा. १४ ऑक्टोबर, २०२१)",
      photoNotePlaceholder: "या आठवणीमागची कहाणी...",
      washiTapeLabel: "पेस्टल वाशी टेप",
    },
    voice: {
      title: "कॅसेटवरील आवाजाचा संदेश (Voice Note)",
      subtitle: "आपला खरा आवाज रेकॉर्ड करा जेणेकरून त्यांना आपले प्रेम जाणवेल",
      recordBtn: "आवाज रेकॉर्ड करा",
      stopBtn: "थांबवा आणि जतन करा",
      recording: "रेकॉर्डिंग सुरू आहे...",
      noteTitlePlaceholder: "ऑडिओचे नाव (उदा. खास तुझ्यासाठी एक संदेश)",
      transcriptPlaceholder: "बोलेल्या शब्दांचा गोषवारा...",
    },
    delights: {
      title: "गोड भेट, गुपित विनोद आणि वेळेचे कुलूप",
      subtitle: "स्वादिष्ट चॉकलेट्स, आतील गुपित विनोद आणि भविष्यात उघडणारे सरप्राईज",
      treatLabel: "गोड भेटवस्तूची निवड",
      insideJokePlaceholder: "भेट उघडल्यावर दिसणारा गुपित विनोद (उदा. 'तुझा चहा नेहमी गार होतो!')",
      capsuleTitle: "टाईम कॅप्सूल (Time Capsule Lock)",
      capsuleDateLabel: "ही भेट कोणत्या तारखेला उघडावी?",
      capsuleMessagePlaceholder: "भविष्यासाठी राखून ठेवलेला खास संदेश...",
    },
    customMemory: {
      customItemTitle: "खास वस्तूची डिजिटल ओळख (Custom Souvenir)",
      customItemPlaceholder: "वस्तूचे नाव (उदा. आपला पहिला कॉफी कप, प्रवासाचे तिकीट)",
      customItemTagPlaceholder: "छोटा टॅग (उदा. जिथून सर्व सुरू झाले)",
      memoryBuddyTrainerTitle: "Memory Buddy AI ला आपल्या आठवणी शिकवा",
      memoryBuddyTrainerSubtitle: "आपले प्रसंग लिहा जेणेकरून चॅटबॉट अगदी आपल्यासारखा संवाद साधेल",
      memoryInputPlaceholder: "एखादी गोड सवय किंवा किस्सा जोडा...",
      addMemoryBtn: "आठवण जोडा (Add Memory)",
    },
    saveAndSealBtn: "पेटी सील करा आणि शेअर लिंक मिळवा",
    savingBox: "पेटी मखमली दोऱ्याने सजवली जात आहे...",
    cancelBtn: "रद्द करा",
  },
  gu: {
    studioTitle: "ઉપહાર સર્જન સ્ટુડિયો (Creator Studio)",
    studioSubtitle: "તમારા પ્રિયજન માટે લાગણીઓથી ભરેલો અનોખો ડિજિટલ બોક્સ તૈયાર કરો",
    languageSelectLabel: "સર્જનની ભાષા (Crafting Language):",
    tabs: {
      workshop: "પેકિંગ ટેબલ",
      basics: "માહિતી व લૉક",
      whySpecial: "કેમ ખાસ છે?",
      vortexHeart: "3D હાર્ટ જાદુ",
      letter: "AI પ્રેમપત્ર",
      scrapbook: "સ્મૃતિ ડાયરી",
      voice: "અવાજનો સંદેશ",
      cake: "સેલિબ્રેશન કેક",
      delights: "મીઠાઈ",
      customMemory: "સ્મૃતિ અને AI",
      giftBlast: "ગિફ્ટ બ્લાસ્ટ",
      lastNote: "છેલ્લો પત્ર",
      seal: "સીલ કરો",
    },
    tableWorkshop: {
      title: "સાચા પેકિંગની મજા (Virtual Gift Table)",
      subtitle: "બોક્સમાં સુગંધ, કાગળની કતરણ અને ટેગ સજાવવા ક્લિક કરો",
      beddingTitle: "કાગળની કતરણ (Shredded Bedding)",
      beddingSubtitle: "બોક્સના તળિયે સુંદર કાગળ પાથરો",
      scatterBeddingBtn: "કતરણ પાથરો (Scatter Bedding)",
      tagTitle: "કાર્ડ ટેગ અને દોરી (Gift Tag)",
      tagSubtitle: "હાથે લખેલું નામનું ટેગ બાંધો",
      stickersTitle: "સુંદર સ્ટિકર્સ (Stickers)",
      stickersSubtitle: "ભેટ પર ખાસ સ્મૃતિના સ્ટિકર્સ લગાવો",
      aromaTitle: "સુગંધ અને વાતાવરણ (Aroma Mood)",
      aromaSubtitle: "બોક્સની સુગંધ પસંદ કરો",
    },
    basics: {
      boxTitleLabel: "બોક્સનું નામ (Title)",
      boxTitlePlaceholder: "દા.ત. મારા વહાલા માટે — ચોથી વર્ષગાંઠની ભેટ",
      recipientLabel: "કોના માટે છે? (નામ)",
      recipientPlaceholder: "દા.ત. અદિતિ / રિયા / હેતલ",
      senderLabel: "તમારું નામ (મોકલનાર)",
      senderPlaceholder: "દા.ત. મનન / હર્ષ / કિશન",
      occasionLabel: "ખાસ પ્રસંગ (Occasion)",
      themeLabel: "બોક્સનો રંગ અને રીબન",
      passwordLabel: "ગુપ્ત પાસવર્ડ (જો રાખવો હોય તો)",
      passwordPlaceholder: "દા.ત. ourfirstcoffee",
      passwordHintLabel: "પાસવર્ડનો સંકેત (Hint)",
      passwordHintPlaceholder: "દા.ત. આપણે જ્યાં પહેલીવાર ૪ કલાક બેઠા હતા...",
      waxSealLabel: "સીલ પરના આદ્યાક્ષરો (Initials)",
    },
    letter: {
      title: "હાથે લખાયેલો પ્રેમપત્ર (Parchment Letter)",
      aiHelperTitle: "Gemini AI પ્રેમપત્ર સહાયક",
      aiHelperDesc: "તમારી યાદોને ગુજરાતીમાં અત્યંત ભાવુક અને સુંદર પત્રમાં ફેરવો",
      toneLabel: "પત્રનો ભાવ",
      memoriesPromptLabel: "પત્રમાં ઉમેરવાની ખાસ યાદો",
      memoriesPromptPlaceholder: "દા.ત. પહેલી મુલાકાતનો વરસાદ, સાથે વિતાવેલી મધુર પળો...",
      generateLetterBtn: "Gemini AI દ્વારા પત્ર લખાવો",
      generatingLetter: "હૃદયસ્પર્શી શબ્દો તૈયાર થઈ રહ્યા છે...",
      letterTitlePlaceholder: "પત્રનું શીર્ષક (દા.ત. તું જ મારું જીવન છે)",
      letterContentPlaceholder: "તમારા દિલની વાત લખો...",
      paperStyleLabel: "કાગળની શૈલી",
    },
    scrapbook: {
      title: "સ્મૃતિઓની પોલરોઇડ ડાયરી (Scrapbook)",
      subtitle: "રંગીન ટેપ અને યાદગાર તારીખો સાથે ફોટા ગોઠવો",
      addPhotoBtn: "નવો ફોટો ઉમેરો",
      photoCaptionPlaceholder: "ફોટો પરનું લખાણ (દા.ત. એ સાંજ જ્યારે સમય થંભી ગયો...)",
      photoDatePlaceholder: "તારીખ (દા.ત. ૧૪ ઓક્ટોબર, ૨૦૨૧)",
      photoNotePlaceholder: "આ ફોટા પાછળની યાદ...",
      washiTapeLabel: "વાશી ટેપ",
    },
    voice: {
      title: "અવાજનો મીઠો સંદેશ (Voice Note)",
      subtitle: "તમારો સાચો અવાજ રેકોર્ડ કરો",
      recordBtn: "અવાજ રેકોર્ડ કરો",
      stopBtn: "રોકો અને સાચવો",
      recording: "રેકોર્ડિંગ ચાલુ છે...",
      noteTitlePlaceholder: "ઓડિયોનું નામ (દા.ત. ખાસ તારા માટે)",
      transcriptPlaceholder: "બોલેલા શબ્દો...",
    },
    delights: {
      title: "મીઠી ભેટ, ગુપ્ત મજાક અને ટાઇમ કેપ્સ્યુલ",
      subtitle: "ચોકલેટ્સ, ભેટની અંદર છુપાયેલો મજાક અને ભવિષ્યનું સરપ્રાઈઝ",
      treatLabel: "મીઠાઈની પસંદગી",
      insideJokePlaceholder: "ભેટ ખોલવા પર દેખાતો ગુપ્ત મજાક",
      capsuleTitle: "ટાઈમ કેપ્સ્યુલ (Time Capsule Lock)",
      capsuleDateLabel: "આ ભેટ કઈ તારીખે ખુલશે?",
      capsuleMessagePlaceholder: "ભવિષ્ય માટેનો સંદેશ...",
    },
    customMemory: {
      customItemTitle: "ખાસ સ્મૃતિનું બેજ (Custom Souvenir)",
      customItemPlaceholder: "વસ્તુનું નામ (દા.ત. આપણો પહેલો કોફી કપ)",
      customItemTagPlaceholder: "નાનો ટેગ",
      memoryBuddyTrainerTitle: "Memory Buddy AI ને તમારી વાર્તાઓ શીખવો",
      memoryBuddyTrainerSubtitle: "તમારા ખાસ કિસ્સાઓ લખો જેથી AI તમારી જેમ વાત કરી શકે",
      memoryInputPlaceholder: "કોઈ યાદગાર કિસ્સો ઉમેરો...",
      addMemoryBtn: "યાદ ઉમેરો (Add Memory)",
    },
    saveAndSealBtn: "બોક્સ સીલ કરો અને લિંક મેળવો",
    savingBox: "બોક્સ તૈયાર થઈ રહ્યું છે...",
    cancelBtn: "રદ કરો",
  },
  bn: {
    studioTitle: "উপহার প্রস্তুত স্টুডিও (Artisan Creator Studio)",
    studioSubtitle: "প্রিয়জনের জন্য ভালোবাসায় ভরা একটি সুন্দর ডিজিটাল উপহার বাক্স তৈরি করুন",
    languageSelectLabel: "তৈরি করার ভাষা (Crafting Language):",
    tabs: {
      workshop: "প্যাকিং টেবিল",
      basics: "বিবরণ ও লক",
      whySpecial: "কেন সে বিশেষ?",
      vortexHeart: "3D হার্ট ম্যাজিক",
      letter: "AI প্রেমপত্র",
      scrapbook: "স্মৃতির ডায়েরি",
      voice: "কণ্ঠবার্তা",
      cake: "সেলিব্রেশন কেক",
      delights: "মিষ্টি উপহার",
      customMemory: "স্মৃতি ও AI",
      giftBlast: "গিফট ব্লাস্ট",
      lastNote: "শেষ চিঠি",
      seal: "সিল ও শেয়ার",
    },
    tableWorkshop: {
      title: "আসল প্যাকিংয়ের আনন্দ (Virtual Gift Table)",
      subtitle: "বাক্সে সুবাস, রঙিন কাগজের কুচি, ফিতার ট্যাগ ও স্টিকার সাজাতে ক্লিক করুন",
      beddingTitle: "কাগজের নরম কুচি (Shredded Bedding)",
      beddingSubtitle: "বাক্সের নিচে রঙিন কাগজের কুচি ছড়ান",
      scatterBeddingBtn: "কুচি ছড়ান (Scatter Bedding)",
      tagTitle: "হাতে লেখা উপহার ট্যাগ (Gift Tag)",
      tagSubtitle: "রেশমি ফিতায় নাম লেখা ট্যাগ বাঁধুন",
      stickersTitle: "সুন্দর স্টিকার (Stickers)",
      stickersSubtitle: "উপহারের ওপর ভালোবাসার স্টিকার লাগান",
      aromaTitle: "সুবাস ও পরিবেশ (Aroma Mood)",
      aromaSubtitle: "বাক্সের মিষ্টি সুবাস ও পাপড়ির মেজাজ বেছে নিন",
    },
    basics: {
      boxTitleLabel: "বাক্সের শিরোনাম (Title)",
      boxTitlePlaceholder: "উদা. আমার ভালোবাসার জন্য — চতুর্থ বার্ষিকীর উপহার",
      recipientLabel: "কার জন্য? (নাম)",
      recipientPlaceholder: "উদা. অনন্যা / শ্রেয়া / অন্তরা",
      senderLabel: "আপনার নাম (প্রেরক)",
      senderPlaceholder: "উদা. আর্য / রোহন / সৈকত",
      occasionLabel: "বিশেষ উপলক্ষ (Occasion)",
      themeLabel: "বাক্সের চামড়া ও ফিতার রঙ",
      passwordLabel: "গোপন পাসওয়ার্ড (যদি লক করতে চান)",
      passwordPlaceholder: "উদা. ourfirstcoffee",
      passwordHintLabel: "পাসওয়ার্ডের সংকেত (Hint)",
      passwordHintPlaceholder: "উদা. যেখানে আমরা প্রথম কফি ডেটে বসেছিলাম...",
      waxSealLabel: "সিলের আদ্যক্ষর (Initials)",
    },
    letter: {
      title: "হাতে লেখা হৃদয়ের চিঠি (Parchment Letter)",
      aiHelperTitle: "Gemini AI প্রেমপত্র লেখক",
      aiHelperDesc: "আপনার স্মৃতিগুলোকে একটি অপূর্ব, কাব্যিক ও আবেগঘন চিঠিতে রূপান্তর করুন",
      toneLabel: "চিঠির মেজাজ ও আবেগ",
      memoriesPromptLabel: "চিঠিতে যুক্ত করার মতো প্রিয় স্মৃতি",
      memoriesPromptPlaceholder: "উদা. বৃষ্টির দিনে ক্যাফেতে দেখা, প্রথম বার্ষিকীর আনন্দ...",
      generateLetterBtn: "Gemini AI দিয়ে চিঠি লিখুন",
      generatingLetter: "বাংলা ভাষায় হৃদয়ের শব্দ সাজানো হচ্ছে...",
      letterTitlePlaceholder: "চিঠির শিরোনাম (উদা. তুমি আছো বলেই পৃথিবী সুন্দর)",
      letterContentPlaceholder: "আপনার মনের কথা লিখুন...",
      paperStyleLabel: "কাগজের স্টাইল",
    },
    scrapbook: {
      title: "স্মৃতির পোলারয়েড ডায়েরি (Scrapbook)",
      subtitle: "রঙিন টেপ ও হাতে লেখা তারিখ দিয়ে ছবি সাজান",
      addPhotoBtn: "নতুন ছবি যোগ করুন",
      photoCaptionPlaceholder: "ছবির ক্যাপশন (উদা. যেদিন সময় থমকে গিয়েছিল...)",
      photoDatePlaceholder: "তারিখ (উদা. ১৪ অক্টোবর, ২০২১)",
      photoNotePlaceholder: "এই ছবির পেছনের গল্প...",
      washiTapeLabel: "ওয়াশি টেপ",
    },
    voice: {
      title: "ক্যাসেটে কণ্ঠবার্তা (Voice Note)",
      subtitle: "আপনার আসল কণ্ঠ রেকর্ড করুন যাতে তারা সবসময় আপনার অনুভূতি শুনতে পায়",
      recordBtn: "কণ্ঠ রেকর্ড শুরু করুন",
      stopBtn: "থামুন ও সেভ করুন",
      recording: "রেকর্ডিং চলছে...",
      noteTitlePlaceholder: "অডিওর নাম (উদা. শুধু তোমার জন্য)",
      transcriptPlaceholder: "কথার সারাংশ...",
    },
    delights: {
      title: "মিষ্টি উপহার, গোপন কৌতুক ও টাইম ক্যাপসুল",
      subtitle: "চকলেট, উপহারের ভেতর গোপন কৌতুক ও ভবিষ্যতের সারপ্রাইজ",
      treatLabel: "মিষ্টি উপহার নির্বাচন",
      insideJokePlaceholder: "খোলার পর দেখা যাবে এমন গোপন কৌতুক",
      capsuleTitle: "টাইম ক্যাপসুল (Time Capsule Lock)",
      capsuleDateLabel: "কবে এই উপহার খুলবে?",
      capsuleMessagePlaceholder: "ভবিষ্যতের জন্য গোপন বার্তা...",
    },
    customMemory: {
      customItemTitle: "স্মারক স্মৃতির ব্যাজ (Custom Souvenir)",
      customItemPlaceholder: "স্মারকটির নাম (উদা. আমাদের প্রথম কফির কাপ)",
      customItemTagPlaceholder: "ছোট ট্যাগ",
      memoryBuddyTrainerTitle: "Memory Buddy AI-কে আপনার গল্প শেখান",
      memoryBuddyTrainerSubtitle: "আপনার স্মৃতি লিখুন যাতে AI আপনার মতো করে কথা বলতে পারে",
      memoryInputPlaceholder: "কোনো মিষ্টি অভ্যাস বা গল্প যোগ করুন...",
      addMemoryBtn: "স্মৃতি যোগ করুন (Add Memory)",
    },
    saveAndSealBtn: "বাক্স সিল করুন এবং লিঙ্ক পান",
    savingBox: "উপহার বাক্স তৈরি হচ্ছে...",
    cancelBtn: "বাতিল করুন",
  },
  pa: {
    studioTitle: "ਤੋਹਫ਼ਾ ਸਟੂਡੀਓ (Artisan Creator Studio)",
    studioSubtitle: "ਆਪਣੇ ਪਿਆਰੇ ਲਈ ਦਿਲੋਂ ਇੱਕ ਖ਼ੂਬਸੂਰਤ ਡਿਜੀਟਲ ਤੋਹਫ਼ਾ ਬਣਾਓ",
    languageSelectLabel: "ਬਣਾਉਣ ਦੀ ਬੋਲੀ (Crafting Language):",
    tabs: {
      workshop: "ਪੈਕਿੰਗ ਟੇਬਲ",
      basics: "ਮੁਢਲੀ ਜਾਣਕਾਰੀ",
      whySpecial: "ਕਿਉਂ ਖ਼ਾਸ ਹੈ?",
      vortexHeart: "3D ਦਿਲ ਦਾ ਜਾਦੂ",
      letter: "AI ਚਿੱਠੀ",
      scrapbook: "ਯਾਦਾਂ ਦੀ ਡਾਇਰੀ",
      voice: "ਆਵਾਜ਼ ਦਾ ਸੁਨੇਹਾ",
      cake: "ਕੇਕ ਤੇ ਸ਼ੁਭਕਾਮਨਾਵਾਂ",
      delights: "ਮਿੱਠਾ ਤੋਹਫ਼ਾ",
      customMemory: "ਨਿਸ਼ਾਨੀ ਤੇ AI",
      giftBlast: "ਗਿਫ਼ਟ ਬਲਾਸਟ",
      lastNote: "ਆਖ਼ਰੀ ਗੁਪਤ ਚਿੱਠੀ",
      seal: "ਸੀਲ ਤੇ ਸ਼ੇਅਰ",
    },
    tableWorkshop: {
      title: "ਅਸਲੀ ਪੈਕਿੰਗ ਦਾ ਮਜ਼ਾ (Virtual Gift Table)",
      subtitle: "ਡੱਬੇ ਵਿੱਚ ਖ਼ੁਸ਼ਬੋ, ਰੰਗੀਨ ਕਾਗਜ਼ੀ ਕਤਰਨਾਂ ਅਤੇ ਟੈਗ ਸਜਾਉਣ ਲਈ ਕਲਿੱਕ ਕਰੋ",
      beddingTitle: "ਕਾਗਜ਼ ਦੀਆਂ ਕਤਰਨਾਂ (Shredded Bedding)",
      beddingSubtitle: "ਡੱਬੇ ਦੇ ਥੱਲੇ ਰੰਗੀਨ ਕਤਰਨਾਂ ਖਿਲਾਰੋ",
      scatterBeddingBtn: "ਕਤਰਨਾਂ ਖਿਲਾਰੋ (Scatter Bedding)",
      tagTitle: "ਹੱਥ-ਲਿਖਤ ਕਾਰਡ ਟੈਗ (Gift Tag)",
      tagSubtitle: "ਰੇਸ਼ਮੀ ਰਿਬਨ 'ਤੇ ਨਾਂ ਦਾ ਟੈਗ ਬੰਨ੍ਹੋ",
      stickersTitle: "ਸੋਹਣੇ ਸਟਿੱਕਰ (Stickers)",
      stickersSubtitle: "ਤੋਹਫ਼ਿਆਂ 'ਤੇ ਖ਼ਾਸ ਸਟਿੱਕਰ ਲਗਾਓ",
      aromaTitle: "ਖ਼ੁਸ਼ਬੋ ਤੇ ਮਾਹੌਲ (Aroma Mood)",
      aromaSubtitle: "ਡੱਬੇ ਦੀ ਮਹਿਕ ਤੇ ਫੁੱਲਾਂ ਦੀਆਂ ਪੱਤੀਆਂ ਚੁਣੋ",
    },
    basics: {
      boxTitleLabel: "ਤੋਹਫ਼ੇ ਦਾ ਨਾਂ (Title)",
      boxTitlePlaceholder: "ਉਦਾ. ਮੇਰੀ ਜਾਨ ਲਈ — ਚੌਥੀ ਵਰ੍ਹੇਗੰਢ ਦਾ ਤੋਹਫ਼ਾ",
      recipientLabel: "ਕਿਸ ਲਈ ਹੈ? (ਨਾਂ)",
      recipientPlaceholder: "ਉਦਾ. ਸਿਮਰਨ / ਪ੍ਰੀਤ / ਅਮਨ",
      senderLabel: "ਤੁਹਾਡਾ ਨਾਂ (ਭੇਜਣ ਵਾਲਾ)",
      senderPlaceholder: "ਉਦਾ. ਕਰਨ / ਹਰਮਨ / ਰਾਜ",
      occasionLabel: "ਖ਼ਾਸ ਮੌਕਾ (Occasion)",
      themeLabel: "ਡੱਬੇ ਦਾ ਰੰਗ ਤੇ ਰੇਸ਼ਮੀ ਰਿਬਨ",
      passwordLabel: "ਗੁਪਤ ਪਾਸਵਰਡ (ਜੇ ਲਾਕ ਕਰਨਾ ਹੋਵੇ)",
      passwordPlaceholder: "ਉਦਾ. ourfirstcoffee",
      passwordHintLabel: "ਪਾਸਵਰਡ ਦਾ ਇਸ਼ਾਰਾ (Hint)",
      passwordHintPlaceholder: "ਉਦਾ. ਜਿੱਥੇ ਅਸੀਂ ਪਹਿਲੀ ਵਾਰ ਕੌਫ਼ੀ ਪੀਤੀ ਸੀ...",
      waxSealLabel: "ਸੀਲ ਦੇ ਅੱਖਰ (Initials)",
    },
    letter: {
      title: "ਹੱਥੀਂ ਲਿਖੀ ਚਿੱਠੀ (Parchment Letter)",
      aiHelperTitle: "Gemini AI ਚਿੱਠੀ ਲੇਖਕ",
      aiHelperDesc: "ਆਪਣੀਆਂ ਯਾਦਾਂ ਨੂੰ ਪੰਜਾਬੀ ਵਿੱਚ ਇੱਕ ਬਹੁਤ ਹੀ ਭਾਵੁਕ ਤੇ ਰੂਹਾਨੀ ਚਿੱਠੀ ਵਿੱਚ ਬਦਲੋ",
      toneLabel: "ਚਿੱਠੀ ਦਾ ਰੰਗ ਤੇ ਅੰਦਾਜ਼",
      memoriesPromptLabel: "ਚਿੱਠੀ ਵਿੱਚ ਲਿਖਣ ਵਾਲੀਆਂ ਖ਼ਾਸ ਯਾਦਾਂ",
      memoriesPromptPlaceholder: "ਉਦਾ. ਮੀਂਹ ਵਾਲੇ ਦਿਨ ਦੀ ਮੁਲਾਕਾਤ, ਪਹਿਲੀ ਲੌਂਗ ਡਰਾਈਵ...",
      generateLetterBtn: "Gemini AI ਨਾਲ ਚਿੱਠੀ ਲਿਖਵਾਓ",
      generatingLetter: "ਪੰਜਾਬੀ ਵਿੱਚ ਦਿਲ ਦੇ ਅਲਫ਼ਾਜ਼ ਤਿਆਰ ਹੋ ਰਹੇ ਹਨ...",
      letterTitlePlaceholder: "ਚਿੱਠੀ ਦਾ ਨਾਂ (ਉਦਾ. ਤੇਰੇ ਨਾਲ ਹੀ ਮੇਰੀ ਦੁਨੀਆ ਹੈ)",
      letterContentPlaceholder: "ਆਪਣੇ ਦਿਲ ਦੀ ਗੱਲ ਲਿਖੋ...",
      paperStyleLabel: "ਕਾਗਜ਼ ਦਾ ਸਟਾਈਲ",
    },
    scrapbook: {
      title: "ਯਾਦਾਂ ਦੀ ਪੋਲਰਾਈਡ ਡਾਇਰੀ (Scrapbook)",
      subtitle: "ਰੰਗੀਨ ਟੇਪਾਂ ਤੇ ਤਾਰੀਖ਼ਾਂ ਨਾਲ ਤਸਵੀਰਾਂ ਸਜਾਓ",
      addPhotoBtn: "ਨਵੀਂ ਤਸਵੀਰ ਜੋੜੋ",
      photoCaptionPlaceholder: "ਤਸਵੀਰ ਦੀ ਸ਼ਾਇਰੀ (ਉਦਾ. ਜਦੋਂ ਵਕਤ ਠਹਿਰ ਗਿਆ ਸੀ...)",
      photoDatePlaceholder: "ਤਾਰੀਖ਼ (ਉਦਾ. ੧੪ ਅਕਤੂਬਰ, ੨੦੨੧)",
      photoNotePlaceholder: "ਇਸ ਤਸਵੀਰ ਦੀ ਕਹਾਣੀ...",
      washiTapeLabel: "ਵਾਸ਼ੀ ਟੇਪ",
    },
    voice: {
      title: "ਕੈਸੇਟ 'ਤੇ ਆਵਾਜ਼ ਦਾ ਸੁਨੇਹਾ (Voice Note)",
      subtitle: "ਆਪਣੀ ਅਸਲੀ ਆਵਾਜ਼ ਰਿਕਾਰਡ ਕਰੋ",
      recordBtn: "ਆਵਾਜ਼ ਰਿਕਾਰਡ ਕਰੋ",
      stopBtn: "ਰੋਕੋ ਤੇ ਸੇਵ ਕਰੋ",
      recording: "ਰਿਕਾਰਡਿੰਗ ਚੱਲ ਰਹੀ ਹੈ...",
      noteTitlePlaceholder: "ਸੁਨੇਹੇ ਦਾ ਨਾਂ (ਉਦਾ. ਸਿਰਫ਼ ਤੇਰੇ ਲਈ)",
      transcriptPlaceholder: "ਬੋਲੇ ਗਏ ਸ਼ਬਦ...",
    },
    delights: {
      title: "ਮਿੱਠਾ ਤੋਹਫ਼ਾ, ਗੁਪਤ ਮਜ਼ਾਕ ਤੇ ਟਾਈਮ ਕੈਪਸੂਲ",
      subtitle: "ਚਾਕਲੇਟ, ਤੋਹਫ਼ੇ ਅੰਦਰ ਛੁਪਿਆ ਮਜ਼ਾਕ ਤੇ ਭਵਿੱਖ ਦਾ ਸਰਪ੍ਰਾਈਜ਼",
      treatLabel: "ਮਿੱਠੇ ਤੋਹਫ਼ੇ ਦੀ ਚੋਣ",
      insideJokePlaceholder: "ਤੋਹਫ਼ਾ ਖੋਲ੍ਹਣ 'ਤੇ ਦਿਖਣ ਵਾਲਾ ਗੁਪਤ ਮਜ਼ਾਕ",
      capsuleTitle: "ਟਾਈਮ ਕੈਪਸੂਲ (Time Capsule Lock)",
      capsuleDateLabel: "ਇਹ ਤੋਹਫ਼ਾ ਕਦੋਂ ਖੁੱਲ੍ਹੇਗਾ?",
      capsuleMessagePlaceholder: "ਭਵਿੱਖ ਲਈ ਖ਼ਾਸ ਸੁਨੇਹਾ...",
    },
    customMemory: {
      customItemTitle: "ਖ਼ਾਸ ਨਿਸ਼ਾਨੀ ਦਾ ਬੈਜ (Custom Souvenir)",
      customItemPlaceholder: "ਨਿਸ਼ਾਨੀ ਦਾ ਨਾਂ (ਉਦਾ. ਸਾਡਾ ਪਹਿਲਾ ਕੌਫ਼ੀ ਕੱਪ)",
      customItemTagPlaceholder: "ਛੋਟਾ ਟੈਗ",
      memoryBuddyTrainerTitle: "Memory Buddy AI ਨੂੰ ਆਪਣੀਆਂ ਗੱਲਾਂ ਸਿਖਾਓ",
      memoryBuddyTrainerSubtitle: "ਆਪਣੀਆਂ ਯਾਦਾਂ ਲਿਖੋ ਤਾਂ ਜੋ AI ਤੁਹਾਡੇ ਵਾਂਗ ਗੱਲ ਕਰ ਸਕੇ",
      memoryInputPlaceholder: "ਕੋਈ ਪਿਆਰੀ ਆਦਤ ਜਾਂ ਕਿੱਸਾ ਜੋੜੋ...",
      addMemoryBtn: "ਯਾਦ ਜੋੜੋ (Add Memory)",
    },
    saveAndSealBtn: "ਡੱਬਾ ਸੀਲ ਕਰੋ ਤੇ ਲਿੰਕ ਬਣਾਓ",
    savingBox: "ਤੋਹਫ਼ਾ ਤਿਆਰ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    cancelBtn: "ਰੱਦ ਕਰੋ",
  },
  ta: {
    studioTitle: "பரிசு உருவாக்கும் கூடம் (Artisan Creator Studio)",
    studioSubtitle: "உங்கள் அன்பிற்குரியவருக்கு இதயப்பூர்வமான நினைவுகளின் பெட்டகத்தை உருவாக்குங்கள்",
    languageSelectLabel: "உருவாக்கும் மொழி (Crafting Language):",
    tabs: {
      workshop: "பேக்கிங் மேஜை",
      basics: "அடிப்படை & பூட்டு",
      whySpecial: "ஏன் சிறப்பு?",
      vortexHeart: "3D இதய அனிமேஷன்",
      letter: "AI காதல் கடிதம்",
      scrapbook: "நினைவேடு",
      voice: "குரல் பதிவு",
      cake: "கொண்டாட்ட கேக்",
      delights: "இனிப்பு பரிசு",
      customMemory: "நினைவு & AI",
      giftBlast: "கிஃப்ட் பிளாஸ்ட்",
      lastNote: "கடைசி ரகசிய கடிதம்",
      seal: "சீல் & பகிர்",
    },
    tableWorkshop: {
      title: "நேரடி பேக்கிங் அனுபவம் (Virtual Gift Table)",
      subtitle: "பெட்டியில் நறுமணம், காகிதத் துண்டுகள் மற்றும் டேக்குகளை அடுக்க கிளிக் செய்யவும்",
      beddingTitle: "மென்மையான காகிதத் துண்டுகள் (Shredded Bedding)",
      beddingSubtitle: "பெட்டியின் அடியில் வண்ணக் காகிதத் துண்டுகளை நிரப்பவும்",
      scatterBeddingBtn: "காகிதத் துண்டுகளை நிரப்பு",
      tagTitle: "கையெழுத்து டேக் & கயிறு (Gift Tag)",
      tagSubtitle: "பட்டு ரிப்பனில் கையால் எழுதிய பெயர் பலகையை கட்டவும்",
      stickersTitle: "அழகிய ஸ்டிக்கர்கள் (Stickers)",
      stickersSubtitle: "பரிசுகளின் மீது நினைவுகளின் ஸ்டிக்கர்களை ஒட்டவும்",
      aromaTitle: "நறுமணம் & சூழல் (Aroma Mood)",
      aromaSubtitle: "பெட்டியின் நறுமணத்தை தேர்வு செய்யவும்",
    },
    basics: {
      boxTitleLabel: "பெட்டகத்தின் தலைப்பு (Title)",
      boxTitlePlaceholder: "எ.கா: என் அன்பே — 4வது ஆண்டு நினைவுப் பரிசு",
      recipientLabel: "யாருக்காக? (பெயர்)",
      recipientPlaceholder: "எ.கா: அனன்யா / பிரியா / கவிதா",
      senderLabel: "உங்கள் பெயர் (அனுப்புபவர்)",
      senderPlaceholder: "எ.கா: ஆர்யன் / கார்த்திக் / விஜய்",
      occasionLabel: "சிறப்பு நிகழ்வு (Occasion)",
      themeLabel: "பெட்டியின் தோல் மற்றும் ரிப்பன் நிறம்",
      passwordLabel: "ரகசிய கடவுச்சொல் (விரும்பினால்)",
      passwordPlaceholder: "எ.கா: ourfirstcoffee",
      passwordHintLabel: "கடவுச்சொல் குறிப்பு (Hint)",
      passwordHintPlaceholder: "எ.கா: நாம் முதன்முதலில் 4 மணி நேரம் பேசிய இடம்...",
      waxSealLabel: "சீல் எழுத்துக்கள் (Initials)",
    },
    letter: {
      title: "கையால் எழுதப்பட்ட காதல் கடிதம் (Parchment Letter)",
      aiHelperTitle: "Gemini AI கடித உதவியாளர்",
      aiHelperDesc: "உங்கள் நினைவுகளை தமிழில் ஒரு கவித்துவமான காதல் கடிதமாக மாற்றுங்கள்",
      toneLabel: "கடிதத்தின் உணர்ச்சி",
      memoriesPromptLabel: "கடிதத்தில் சேர்க்க வேண்டிய நினைவுகள்",
      memoriesPromptPlaceholder: "எ.கா: முதல் மழை சந்திப்பு, முதல் ஆண்டு கொண்டாட்டம்...",
      generateLetterBtn: "Gemini AI மூலம் கடிதம் எழுது",
      generatingLetter: "தமிழில் உணர்ச்சிகரமான வார்த்தைகள் உருவாக்கப்படுகின்றன...",
      letterTitlePlaceholder: "கடித தலைப்பு (எ.கா: நீயே என் உயிர்)",
      letterContentPlaceholder: "உங்கள் இதயத்தின் வார்த்தைகளை எழுதுங்கள்...",
      paperStyleLabel: "காகித பாணி",
    },
    scrapbook: {
      title: "நினைவுகளின் ஆல்பம் (Scrapbook)",
      subtitle: "புகைப்படங்களை அழகிய டேப் மற்றும் தேதிகளுடன் அடுக்கவும்",
      addPhotoBtn: "புகைப்படம் சேர்க்க",
      photoCaptionPlaceholder: "புகைப்பட கவிதை (எ.கா: காலம் நின்ற தருணம்...)",
      photoDatePlaceholder: "தேதி (எ.கா: அக்டோபர் 14, 2021)",
      photoNotePlaceholder: "இதன் பின்னணியில் உள்ள கதை...",
      washiTapeLabel: "வாஷி டேப்",
    },
    voice: {
      title: "குரல் பதிவு (Voice Note)",
      subtitle: "உங்கள் உண்மையான குரலை பதிவு செய்யுங்கள்",
      recordBtn: "குரல் பதிவு தொடங்கு",
      stopBtn: "நிறுத்தி சேமிக்கவும்",
      recording: "பதிவு செய்யப்படுகிறது...",
      noteTitlePlaceholder: "பதிவின் தலைப்பு (எ.கா: உனக்காக ஒரு ரகசியம்)",
      transcriptPlaceholder: "பேசிய வார்த்தைகள்...",
    },
    delights: {
      title: "இனிப்பு பரிசு, ரகசிய நகைச்சுவை & காலப் பெட்டகம்",
      subtitle: "சாக்லேட் மற்றும் எதிர்காலத்தில் திறக்கும் சர்ப்ரைஸ் பரிசு",
      treatLabel: "இனிப்பு தேர்வு",
      insideJokePlaceholder: "திறக்கும் போது வெளிப்படும் ரகசிய நகைச்சுவை",
      capsuleTitle: "காலப் பெட்டகம் (Time Capsule Lock)",
      capsuleDateLabel: "எப்போது திறக்க வேண்டும்?",
      capsuleMessagePlaceholder: "எதிர்காலத்திற்கான ரகசிய செய்தி...",
    },
    customMemory: {
      customItemTitle: "சிறப்பு நினைவு சின்னம் (Custom Souvenir)",
      customItemPlaceholder: "பொருளின் பெயர் (எ.கா: நம் முதல் காபி கப்)",
      customItemTagPlaceholder: "சிறிய டேக்",
      memoryBuddyTrainerTitle: "Memory Buddy AI-க்கு உங்கள் கதைகளை கற்றுக்கொடுங்கள்",
      memoryBuddyTrainerSubtitle: "உங்கள் நினைவுகளை எழுதுங்கள், AI உங்களைப் போலவே பேசும்",
      memoryInputPlaceholder: "ஒரு அழகான பழக்கம் அல்லது நிகழ்வை சேர்க்க...",
      addMemoryBtn: "நினைவு சேர்க்க (Add Memory)",
    },
    saveAndSealBtn: "பெட்டியை சீல் செய்து லிங்க் பெறவும்",
    savingBox: "பெட்டி தயாராகிறது...",
    cancelBtn: "ரத்து செய்",
  },
  te: {
    studioTitle: "బహుమతి సృష్టి కేంద్రం (Artisan Creator Studio)",
    studioSubtitle: "మీ ప్రియమైన వారి కోసం ప్రేమతో నిండిన వర్చువల్ జ్ఞాపకాల పేటికను రూపొందించండి",
    languageSelectLabel: "రూపొందించే భాష (Crafting Language):",
    tabs: {
      workshop: "ప్యాకింగ్ టేబుల్",
      basics: "వివరాలు & లాక్",
      whySpecial: "ఎందుకు ప్రత్యేకం?",
      vortexHeart: "3D హార్ట్ మ్యాజిక్",
      letter: "AI ప్రేమలేఖ",
      scrapbook: "జ్ఞాపకాల డైరీ",
      voice: "వాయిస్ సందేశం",
      cake: "సెలబ్రేషన్ కేక్",
      delights: "తీపి కానుక",
      customMemory: "జ్ఞాపకం & AI",
      giftBlast: "గిఫ్ట్ బ్లాస్ట్",
      lastNote: "చివరి రహస్య లేఖ",
      seal: "సీల్ & షేర్",
    },
    tableWorkshop: {
      title: "ప్రత్యక్ష ప్యాకింగ్ అనుభవం (Virtual Gift Table)",
      subtitle: "పేటికలో సువాసన, కాగితపు ముక్కలు మరియు ట్యాగ్‌లను సర్దడానికి క్లిక్ చేయండి",
      beddingTitle: "మెత్తని కాగితపు ముక్కలు (Shredded Bedding)",
      beddingSubtitle: "పేటిక అడుగున రంగురంగుల కాగితపు ముక్కలను పరవండి",
      scatterBeddingBtn: "కాగితపు ముక్కలను పరవండి",
      tagTitle: "చేతిరాత కార్డు ట్యాగ్ (Gift Tag)",
      tagSubtitle: "సిల్క్ రిబ్బన్‌పై పేరు రాసిన ట్యాగ్‌ను కట్టండి",
      stickersTitle: "అందమైన స్టిక్కర్లు (Stickers)",
      stickersSubtitle: "బహుమతులపై జ్ఞాపకాల స్టిక్కర్లను అతికించండి",
      aromaTitle: "సువాసన & వాతావరణం (Aroma Mood)",
      aromaSubtitle: "పేటిక యొక్క సువాసనను ఎంచుకోండి",
    },
    basics: {
      boxTitleLabel: "పేటిక పేరు (Title)",
      boxTitlePlaceholder: "ఉదా: నా ప్రాణానికి — 4వ వార్షికోత్సవ కానుక",
      recipientLabel: "ఎవరి కోసం? (పేరు)",
      recipientPlaceholder: "ఉదా: అనన్య / ప్రియ / శ్రేయ",
      senderLabel: "మీ పేరు (పంపేవారు)",
      senderPlaceholder: "ఉదా: ఆర్యన్ / రోహిత్ / వరుణ్",
      occasionLabel: "ప్రత్యేక సందర్భం (Occasion)",
      themeLabel: "పేటిక రంగు మరియు రిబ్బన్",
      passwordLabel: "రహస్య పాస్‌వర్డ్ (కావాలనుకుంటే)",
      passwordPlaceholder: "ఉదా: ourfirstcoffee",
      passwordHintLabel: "పాస్‌వర్డ్ సూచన (Hint)",
      passwordHintPlaceholder: "ఉదా: మనం మొదటిసారి 4 గంటలు మాట్లాడిన ప్రదేశం...",
      waxSealLabel: "సీల్ అక్షరాలు (Initials)",
    },
    letter: {
      title: "చేతితో రాసిన ప్రేమలేఖ (Parchment Letter)",
      aiHelperTitle: "Gemini AI ప్రేమలేఖ రచయిత",
      aiHelperDesc: "మీ జ్ఞాపకాలను తెలుగులో భావోద్వేగభరితమైన అందమైన లేఖగా మార్చండి",
      toneLabel: "లేఖ శైలి",
      memoriesPromptLabel: "లేఖలో చేర్చాల్సిన జ్ఞాపకాలు",
      memoriesPromptPlaceholder: "ఉదా: మొదటి వర్షపు రోజు కలయిక, మొదటి వార్షికోత్సవం...",
      generateLetterBtn: "Gemini AI తో లేఖ రాయించండి",
      generatingLetter: "తెలుగులో మనసుకు హత్తుకునే పదాలు రూపొందుతున్నాయి...",
      letterTitlePlaceholder: "లేఖ శీర్షిక (ఉదా: నీవే నా సర్వస్వం)",
      letterContentPlaceholder: "మీ మనసులోని మాటలను రాయండి...",
      paperStyleLabel: "కాగితం శైలి",
    },
    scrapbook: {
      title: "జ్ఞాపకాల ఫోటో డైరీ (Scrapbook)",
      subtitle: "రంగురంగుల టేపులు మరియు తేదీలతో ఫోటోలను సర్దండి",
      addPhotoBtn: "ఫోటో జోడించండి",
      photoCaptionPlaceholder: "ఫోటో క్యాప్షన్ (ఉదా: కాలం ఆగిపోయిన క్షణం...)",
      photoDatePlaceholder: "తేదీ (ఉదా: అక్టోబర్ 14, 2021)",
      photoNotePlaceholder: "ఈ ఫోటో వెనుక ఉన్న కథ...",
      washiTapeLabel: "వాషి టేప్",
    },
    voice: {
      title: "వాయిస్ మెసేజ్ (Voice Note)",
      subtitle: "మీ నిజమైన గొంతును రికార్డ్ చేయండి",
      recordBtn: "రికార్డింగ్ ప్రారంభించండి",
      stopBtn: "ఆపి సేవ్ చేయండి",
      recording: "రికార్డింగ్ అవుతోంది...",
      noteTitlePlaceholder: "ఆడియో పేరు (ఉదా: నీ కోసమే ఈ మాట)",
      transcriptPlaceholder: "మాట్లాడిన మాటలు...",
    },
    delights: {
      title: "తీపి కానుక, రహస్య హాస్యం & టైమ్ క్యాప్సూల్",
      subtitle: "చాక్లెట్ మరియు భవిష్యత్తులో తెరుచుకునే ఆశ్చర్యకరమైన బహుమతి",
      treatLabel: "తీపి కానుక ఎంపిక",
      insideJokePlaceholder: "తెరవగానే కనిపించే రహస్య హాస్యం",
      capsuleTitle: "టైమ్ క్యాప్సూల్ (Time Capsule Lock)",
      capsuleDateLabel: "ఈ బహుమతి ఎప్పుడు తెరవాలి?",
      capsuleMessagePlaceholder: "భవిష్యత్తు కోసం రహస్య సందేశం...",
    },
    customMemory: {
      customItemTitle: "ప్రత్యేక జ్ఞాపక చిహ్నం (Custom Souvenir)",
      customItemPlaceholder: "వస్తువు పేరు (ఉదా: మన మొదటి కాఫీ కప్పు)",
      customItemTagPlaceholder: "చిన్న ట్యాగ్",
      memoryBuddyTrainerTitle: "Memory Buddy AI కి మీ కథలను నేర్పించండి",
      memoryBuddyTrainerSubtitle: "మీ జ్ఞాపకాలను రాయండి, AI మీలాగే మాట్లాడుతుంది",
      memoryInputPlaceholder: "మధురమైన జ్ఞాపకాన్ని జోడించండి...",
      addMemoryBtn: "జ్ఞాపకం జోడించు (Add Memory)",
    },
    saveAndSealBtn: "పేటికను సీల్ చేసి లింక్ పొందండి",
    savingBox: "పేటిక సిద్ధమవుతోంది...",
    cancelBtn: "రద్దు చేయండి",
  },
  es: {
    studioTitle: "Estudio de Creación Artesanal",
    studioSubtitle: "Diseña un baúl digital lleno de emociones y recuerdos para esa persona especial",
    languageSelectLabel: "Idioma de Creación (Crafting Language):",
    tabs: {
      workshop: "Mesa de Empaque",
      basics: "Datos y Candado",
      whySpecial: "¿Por qué especial?",
      vortexHeart: "Corazón Vortex 3D",
      letter: "Carta con IA",
      scrapbook: "Álbum de Fotos",
      voice: "Mensaje de Voz",
      cake: "Pastel de Celebración",
      delights: "Delicias y Dulces",
      customMemory: "Recuerdo e IA",
      giftBlast: "Explosión de Regalos",
      lastNote: "La Última Carta",
      seal: "Sellar y Compartir",
    },
    tableWorkshop: {
      title: "Mesa de Empaque Artesanal Interactiva",
      subtitle: "Haz clic para añadir aroma, virutas de papel, etiquetas y sellos al cofre",
      beddingTitle: "Virutas de Papel Suave (Bedding)",
      beddingSubtitle: "Esparce virutas de papel decorativo en la base",
      scatterBeddingBtn: "Esparcir Virutas de Papel",
      tagTitle: "Etiqueta Caligráfica y Cuerda",
      tagSubtitle: "Ata una tarjeta manuscrita en el lazo de satén",
      stickersTitle: "Stickers y Cintas Washi",
      stickersSubtitle: "Pega sellos y bromas privadas en los regalos",
      aromaTitle: "Aroma y Atmósfera Sensorial",
      aromaSubtitle: "Elige la fragancia ambiental y los pétalos flotantes",
    },
    basics: {
      boxTitleLabel: "Título del Cofre",
      boxTitlePlaceholder: "ej. Para el amor de mi vida — 4to Aniversario",
      recipientLabel: "¿Para quién es? (Destinatario)",
      recipientPlaceholder: "ej. Sofía / Valentina / Mateo",
      senderLabel: "Tu Nombre (Remitente)",
      senderPlaceholder: "ej. Alejandro / Diego / Lucas",
      occasionLabel: "Ocasión Especial",
      themeLabel: "Cuero del Baúl y Terciopelo del Lazo",
      passwordLabel: "Contraseña Secreta (Opcional)",
      passwordPlaceholder: "ej. nuestroprimerbeso",
      passwordHintLabel: "Pista Secreta para la Contraseña",
      passwordHintPlaceholder: "ej. Donde nos sentamos 4 horas en nuestra primera cita...",
      waxSealLabel: "Iniciales del Sello de Cera",
    },
    letter: {
      title: "Carta Manuscrita en Pergamino",
      aiHelperTitle: "Asistente de Cartas de Amor con Gemini IA",
      aiHelperDesc: "Convierte tus recuerdos reales en una carta emotiva y poética en español",
      toneLabel: "Tono Emocional",
      memoriesPromptLabel: "Recuerdos clave y apodos cariñosos",
      memoriesPromptPlaceholder: "ej. La lluvia en la cafetería, la pasta quemada de aniversario...",
      generateLetterBtn: "Redactar Carta Emotiva con Gemini IA",
      generatingLetter: "Escribiendo palabras desde el corazón en español...",
      letterTitlePlaceholder: "Título de la Carta (ej. Una Promesa Eterna)",
      letterContentPlaceholder: "Escribe tus sentimientos más profundos...",
      paperStyleLabel: "Estilo del Pergamino",
    },
    scrapbook: {
      title: "Álbum de Fotos Polaroid",
      subtitle: "Fotos inclinadas con cintas washi, fechas y anécdotas",
      addPhotoBtn: "Añadir Foto Polaroid",
      photoCaptionPlaceholder: "Pie de foto (ej. El día que el mundo se detuvo...)",
      photoDatePlaceholder: "Fecha (ej. 14 de Octubre, 2021)",
      photoNotePlaceholder: "La historia detrás de esta foto...",
      washiTapeLabel: "Cinta Washi Pastel",
    },
    voice: {
      title: "Nota de Voz en Casete Vintage",
      subtitle: "Graba tu voz real desde el navegador para que escuche tus latidos",
      recordBtn: "Iniciar Grabación de Voz",
      stopBtn: "Detener y Guardar Nota",
      recording: "Grabando voz...",
      noteTitlePlaceholder: "Título del Audio (ej. Un susurro para ti)",
      transcriptPlaceholder: "Transcripción del mensaje...",
    },
    delights: {
      title: "Delicias Dulces, Chistes Privados y Cápsula del Tiempo",
      subtitle: "Chocolates finos, secretos al desenvolver y regalos bloqueados hasta una fecha",
      treatLabel: "Selección del Dulce",
      insideJokePlaceholder: "Chiste privado al abrir (ej. '¡La piña en la pizza es un crimen!')",
      capsuleTitle: "Cápsula del Tiempo (Bloqueo por Fecha)",
      capsuleDateLabel: "¿En qué fecha se desbloqueará?",
      capsuleMessagePlaceholder: "Mensaje sorpresa para el futuro...",
    },
    customMemory: {
      customItemTitle: "Insignia de Recuerdo Personalizado",
      customItemPlaceholder: "Nombre del Objeto (ej. Nuestra Primera Taza de Café)",
      customItemTagPlaceholder: "Etiqueta Corta",
      memoryBuddyTrainerTitle: "Entrena a tu Compañero con IA (Memory Buddy)",
      memoryBuddyTrainerSubtitle: "Escribe anécdotas para que la IA responda con sus recuerdos reales",
      memoryInputPlaceholder: "Añade una anécdota, costumbre o chiste...",
      addMemoryBtn: "Añadir Anécdota",
    },
    saveAndSealBtn: "Sellar Cofre y Generar Enlace",
    savingBox: "Sellando el cofre con cera...",
    cancelBtn: "Cancelar",
  },
  fr: {
    studioTitle: "Studio de Création Artisanale",
    studioSubtitle: "Créez un coffret virtuel sur mesure chargé d'émotion et de doux souvenirs",
    languageSelectLabel: "Langue de Création (Crafting Language):",
    tabs: {
      workshop: "Table d'Atelier",
      basics: "Infos & Clé",
      whySpecial: "Pourquoi Unique ?",
      vortexHeart: "Cœur Vortex 3D",
      letter: "Lettre d'Amour IA",
      scrapbook: "Album Photos",
      voice: "Message Vocal",
      cake: "Gâteau de Fête",
      delights: "Douceurs & Délices",
      customMemory: "Souvenir & IA",
      giftBlast: "Explosion Surprise",
      lastNote: "Le Dernier Mot",
      seal: "Sceller & Partager",
    },
    tableWorkshop: {
      title: "Table d'Emballage Virtuelle Interactive",
      subtitle: "Cliquez pour déposer parfum, copeaux de papier doux, étiquettes et rubans",
      beddingTitle: "Copeaux de Papier Décoratif",
      beddingSubtitle: "Dispersez du papier froissé au fond de la boîte",
      scatterBeddingBtn: "Disperser les Copeaux",
      tagTitle: "Étiquette Calligraphiée & Ficelle",
      tagSubtitle: "Attachez une étiquette manuscrite sur le ruban",
      stickersTitle: "Stickers & Rubans Washi",
      stickersSubtitle: "Collez des sceaux et des clins d'œil sur les cadeaux",
      aromaTitle: "Senteur & Atmosphère",
      aromaSubtitle: "Choisissez la fragrance d'ambiance et les pétales flottants",
    },
    basics: {
      boxTitleLabel: "Titre du Coffret",
      boxTitlePlaceholder: "ex: À mon amour éternel — 4e Anniversaire",
      recipientLabel: "Pour qui ? (Destinataire)",
      recipientPlaceholder: "ex: Camille / Juliette / Thomas",
      senderLabel: "Votre Nom (Expéditeur)",
      senderPlaceholder: "ex: Antoine / Gabriel / Louis",
      occasionLabel: "Occasion Spéciale",
      themeLabel: "Cuir du Coffret et Ruban de Velours",
      passwordLabel: "Mot de Passe Secret (Facultatif)",
      passwordPlaceholder: "ex: notrepremierecafe",
      passwordHintLabel: "Indice pour le Mot de Passe",
      passwordHintPlaceholder: "ex: Le café où nous sommes restés 4 heures...",
      waxSealLabel: "Initiales du Sceau de Cire",
    },
    letter: {
      title: "Lettre Manuscrite sur Parchemin",
      aiHelperTitle: "Assistant Lettre d'Amour avec Gemini IA",
      aiHelperDesc: "Transformez vos souvenirs en une lettre bouleversante et poétique en français",
      toneLabel: "Tonalité Émotionnelle",
      memoriesPromptLabel: "Souvenirs clés et petits surnoms",
      memoriesPromptPlaceholder: "ex: La pluie au café, le dîner où les pâtes ont brûlé...",
      generateLetterBtn: "Rédiger la Lettre avec Gemini IA",
      generatingLetter: "Écriture de mots sincères en français...",
      letterTitlePlaceholder: "Titre de la Lettre (ex: Une Promesse Éternelle)",
      letterContentPlaceholder: "Exprimez tout votre amour...",
      paperStyleLabel: "Style de Parchemin",
    },
    scrapbook: {
      title: "Album Photo Polaroid Vintage",
      subtitle: "Photos inclinées avec rubans washi, dates manuscrites et récits",
      addPhotoBtn: "Ajouter une Photo Polaroid",
      photoCaptionPlaceholder: "Légende de la photo (ex: Le jour où le temps s'est arrêté...)",
      photoDatePlaceholder: "Date (ex: 14 Octobre 2021)",
      photoNotePlaceholder: "L'histoire derrière cette photo...",
      washiTapeLabel: "Ruban Washi Pastel",
    },
    voice: {
      title: "Note Vocale sur Cassette Vintage",
      subtitle: "Enregistrez votre vraie voix depuis le navigateur",
      recordBtn: "Démarrer l'Enregistrement",
      stopBtn: "Arrêter et Sauvegarder",
      recording: "Enregistrement en cours...",
      noteTitlePlaceholder: "Titre de l'Audio (ex: Un doux murmure pour toi)",
      transcriptPlaceholder: "Transcription du message...",
    },
    delights: {
      title: "Douceurs, Clins d'œil & Capsule Temporelle",
      subtitle: "Chocolats fins, secrets au déballage et cadeaux scellés jusqu'à une date",
      treatLabel: "Choix de la Gourmandise",
      insideJokePlaceholder: "Clin d'œil secret au déballage",
      capsuleTitle: "Capsule Temporelle (Verrouillée par Date)",
      capsuleDateLabel: "Date de Déverrouillage",
      capsuleMessagePlaceholder: "Message secret pour le futur...",
    },
    customMemory: {
      customItemTitle: "Badge Souvenir Personnalisé",
      customItemPlaceholder: "Nom de l'Objet (ex: Notre Première Tasse de Café)",
      customItemTagPlaceholder: "Petite Étiquette",
      memoryBuddyTrainerTitle: "Entraînez le Compagnon IA (Memory Buddy)",
      memoryBuddyTrainerSubtitle: "Ajoutez vos anecdotes pour que l'IA réponde avec vos vrais souvenirs",
      memoryInputPlaceholder: "Ajoutez une anecdote, habitude ou souvenir...",
      addMemoryBtn: "Ajouter une Anecdote",
    },
    saveAndSealBtn: "Sceller le Coffret et Obtenir le Lien",
    savingBox: "Scellement du coffret à la cire...",
    cancelBtn: "Annuler",
  },
  it: {
    studioTitle: "Studio di Creazione Artigianale",
    studioSubtitle: "Crea uno scrigno digitale colmo di emozioni e ricordi preziosi",
    languageSelectLabel: "Lingua di Creazione (Crafting Language):",
    tabs: {
      workshop: "Tavolo da Lavoro",
      basics: "Info & Lucchetto",
      whySpecial: "Perché Speciale?",
      vortexHeart: "Cuore Vortex 3D",
      letter: "Lettera d'Amore IA",
      scrapbook: "Album Foto",
      voice: "Nota Vocale",
      cake: "Torta di Festa",
      delights: "Dolcezze",
      customMemory: "Ricordo & IA",
      giftBlast: "Esplosione a Sorpresa",
      lastNote: "L'Ultima Nota",
      seal: "Sigilla & Condividi",
    },
    tableWorkshop: {
      title: "Tavolo di Confezionamento Interattivo",
      subtitle: "Clicca per aggiungere profumo, pagliuzze di carta e nastri di raso al baule",
      beddingTitle: "Pagliuzze di Carta Morbida",
      beddingSubtitle: "Disperdi pagliuzze colorate sul fondo",
      scatterBeddingBtn: "Disperdi Pagliuzze",
      tagTitle: "Cartellino Calligrafico & Spago",
      tagSubtitle: "Lega un cartellino sul nastro di raso",
      stickersTitle: "Adesivi & Nastri Washi",
      stickersSubtitle: "Incolla sigilli e battute private sui regali",
      aromaTitle: "Aroma e Atmosfera",
      aromaSubtitle: "Scegli il profumo e i petali fluttuanti",
    },
    basics: {
      boxTitleLabel: "Titolo dello Scrigno",
      boxTitlePlaceholder: "es: Al mio grande amore — 4° Anniversario",
      recipientLabel: "Per chi è? (Destinatario)",
      recipientPlaceholder: "es: Chiara / Giulia / Marco",
      senderLabel: "Il tuo Nome (Mittente)",
      senderPlaceholder: "es: Alessandro / Matteo / Luca",
      occasionLabel: "Occasione Speciale",
      themeLabel: "Pelle del Baule e Nastro di Velluto",
      passwordLabel: "Parola Segreta (Opzionale)",
      passwordPlaceholder: "es: ilnostroprimocaffe",
      passwordHintLabel: "Indizio per la Password",
      passwordHintPlaceholder: "es: Il bar dove siamo rimasti a parlare per 4 ore...",
      waxSealLabel: "Iniziali del Sigillo di Cera",
    },
    letter: {
      title: "Lettera Manoscritta su Pergamena",
      aiHelperTitle: "Assistente Lettere d'Amore con Gemini IA",
      aiHelperDesc: "Trasforma i tuoi ricordi in una lettera emozionante in italiano",
      toneLabel: "Tono Emotivo",
      memoriesPromptLabel: "Ricordi speciali e nomignoli",
      memoriesPromptPlaceholder: "es: La pioggia al bar, la pasta bruciata al primo anniversario...",
      generateLetterBtn: "Scrivi Lettera con Gemini IA",
      generatingLetter: "Creazione di parole dal cuore...",
      letterTitlePlaceholder: "Titolo della Lettera",
      letterContentPlaceholder: "Scrivi ciò che provi...",
      paperStyleLabel: "Stile Pergamena",
    },
    scrapbook: {
      title: "Album di Foto Polaroid",
      subtitle: "Foto inclinate con nastri washi e date scritte a mano",
      addPhotoBtn: "Aggiungi Foto Polaroid",
      photoCaptionPlaceholder: "Didascalia",
      photoDatePlaceholder: "Data",
      photoNotePlaceholder: "La storia dietro questa foto...",
      washiTapeLabel: "Nastro Washi",
    },
    voice: {
      title: "Messaggio Vocale su Cassetta Vintage",
      subtitle: "Registra la tua voce reale dal browser",
      recordBtn: "Inizia Registrazione",
      stopBtn: "Ferma e Salva",
      recording: "Registrazione in corso...",
      noteTitlePlaceholder: "Titolo dell'Audio",
      transcriptPlaceholder: "Trascrizione...",
    },
    delights: {
      title: "Dolcezze, Battute e Capsula del Tempo",
      subtitle: "Cioccolatini, segreti all'apertura e regali con conto alla rovescia",
      treatLabel: "Scelta del Dolce",
      insideJokePlaceholder: "Battuta segreta",
      capsuleTitle: "Capsula del Tempo (Lucchetto con Data)",
      capsuleDateLabel: "Data di Sblocco",
      capsuleMessagePlaceholder: "Messaggio segreto per il futuro...",
    },
    customMemory: {
      customItemTitle: "Spilla Ricordo Personalizzata",
      customItemPlaceholder: "Nome Oggetto (es: La Nostra Prima Tazza di Caffè)",
      customItemTagPlaceholder: "Etichetta Breve",
      memoryBuddyTrainerTitle: "Allena il Tuo Compagno IA (Memory Buddy)",
      memoryBuddyTrainerSubtitle: "Aggiungi aneddoti per far parlare l'IA come voi",
      memoryInputPlaceholder: "Aggiungi un aneddoto...",
      addMemoryBtn: "Aggiungi Ricordo",
    },
    saveAndSealBtn: "Sigilla lo Scrigno e Ottieni il Link",
    savingBox: "Sigillatura dello scrigno in corso...",
    cancelBtn: "Annulla",
  },
  de: {
    studioTitle: "Geschenk-Gestaltungsstudio",
    studioSubtitle: "Erschaffe eine handgemachte, emotionale digitale Schatztruhe für deine Liebsten",
    languageSelectLabel: "Sprache wählen (Crafting Language):",
    tabs: {
      workshop: "Packtisch",
      basics: "Basis & Schloss",
      whySpecial: "Warum besonders?",
      vortexHeart: "3D Vortex Herz",
      letter: "KI-Liebesbrief",
      scrapbook: "Fotoalbum",
      voice: "Sprachnachricht",
      cake: "Festtagskuchen",
      delights: "Leckereien",
      customMemory: "Andenken & KI",
      giftBlast: "Geschenk-Explosion",
      lastNote: "Der letzte Brief",
      seal: "Versiegeln & Teilen",
    },
    tableWorkshop: {
      title: "Interaktiver Geschenk-Packtisch",
      subtitle: "Klicke, um Duft, Papierstreifen, Anhänger und Bänder in die Schatztruhe zu packen",
      beddingTitle: "Weiche Papierstreifen (Bedding)",
      beddingSubtitle: "Verteile dekorative Papierstreifen auf dem Boden",
      scatterBeddingBtn: "Papierstreifen verteilen",
      tagTitle: "Kalligrafie-Anhänger & Kordel",
      tagSubtitle: "Binde einen handgeschriebenen Anhänger an das Satinband",
      stickersTitle: "Sticker & Washi-Tapes",
      stickersSubtitle: "Klebe Siegel und Insider-Witze auf die Geschenke",
      aromaTitle: "Aroma & Atmosphäre",
      aromaSubtitle: "Wähle den Raumduft und schwebende Blütenblätter",
    },
    basics: {
      boxTitleLabel: "Titel der Schatztruhe",
      boxTitlePlaceholder: "z.B. Für meine große Liebe — 4. Jahrestag",
      recipientLabel: "Für wen? (Empfänger)",
      recipientPlaceholder: "z.B. Anna / Laura / Felix",
      senderLabel: "Dein Name (Absender)",
      senderPlaceholder: "z.B. Lukas / Maximilian / Paul",
      occasionLabel: "Besonderer Anlass",
      themeLabel: "Leder- und Samtband-Farbe",
      passwordLabel: "Geheimwort (Optional)",
      passwordPlaceholder: "z.B. unsererstertag",
      passwordHintLabel: "Geheimer Hinweis",
      passwordHintPlaceholder: "z.B. Das Café, in dem wir 4 Stunden saßen...",
      waxSealLabel: "Initialen für das Wachssiegel",
    },
    letter: {
      title: "Handgeschriebener Pergamentbrief",
      aiHelperTitle: "Liebesbrief-Assistent mit Gemini KI",
      aiHelperDesc: "Verwandle deine Erinnerungen in einen tief berührenden Brief auf Deutsch",
      toneLabel: "Emotionaler Ton",
      memoriesPromptLabel: "Wichtige Erinnerungen & Kosenamen",
      memoriesPromptPlaceholder: "z.B. Der Regen beim ersten Date, der Jahrestag...",
      generateLetterBtn: "Brief mit Gemini KI verfassen",
      generatingLetter: "Herzergreifende Worte werden verfasst...",
      letterTitlePlaceholder: "Titel des Briefes",
      letterContentPlaceholder: "Schreibe aus tiefstem Herzen...",
      paperStyleLabel: "Pergament-Stil",
    },
    scrapbook: {
      title: "Polaroid-Fotoalbum",
      subtitle: "Geneigte Fotos mit Washi-Tape und handgeschriebenen Daten",
      addPhotoBtn: "Foto hinzufügen",
      photoCaptionPlaceholder: "Bildunterschrift",
      photoDatePlaceholder: "Datum",
      photoNotePlaceholder: "Die Geschichte dahinter...",
      washiTapeLabel: "Washi-Tape",
    },
    voice: {
      title: "Sprachnachricht auf Vintage-Kassette",
      subtitle: "Nimm deine echte Stimme direkt im Browser auf",
      recordBtn: "Aufnahme starten",
      stopBtn: "Stoppen & Speichern",
      recording: "Aufnahme läuft...",
      noteTitlePlaceholder: "Titel der Aufnahme",
      transcriptPlaceholder: "Notiz / Transkript...",
    },
    delights: {
      title: "Leckereien, Insider & Zeitkapsel",
      subtitle: "Pralinen, geheime Botschaften und ein Schloss mit Zieldatum",
      treatLabel: "Süßigkeit auswählen",
      insideJokePlaceholder: "Geheimer Insider-Witz",
      capsuleTitle: "Zeitkapsel (Datums-Schloss)",
      capsuleDateLabel: "Öffnungsdatum",
      capsuleMessagePlaceholder: "Geheime Botschaft für die Zukunft...",
    },
    customMemory: {
      customItemTitle: "Individuelles Erinnerungs-Abzeichen",
      customItemPlaceholder: "Gegenstand (z.B. Unsere erste Kaffeetasse)",
      customItemTagPlaceholder: "Kurzes Etikett",
      memoryBuddyTrainerTitle: "Trainiere den KI-Begleiter (Memory Buddy)",
      memoryBuddyTrainerSubtitle: "Füge Anekdoten hinzu, damit die KI eure gemeinsamen Momente kennt",
      memoryInputPlaceholder: "Erinnerung oder Gewohnheit hinzufügen...",
      addMemoryBtn: "Erinnerung hinzufügen",
    },
    saveAndSealBtn: "Schatztruhe versiegeln & Link erstellen",
    savingBox: "Schatztruhe wird versiegelt...",
    cancelBtn: "Abbrechen",
  },
  ar: {
    studioTitle: "استوديو تصميم الهدايا اليدوية",
    studioSubtitle: "اصنع صندوق هدايا تذكاري دافئ ومليء بالمشاعر الصادقة لمن تحب",
    languageSelectLabel: "لغة التصميم (Crafting Language):",
    tabs: {
      workshop: "طاولة التغليف",
      basics: "الأساسيات والقفل",
      whySpecial: "لماذا هو مميز؟",
      vortexHeart: "قلب ثلاثي الأبعاد",
      letter: "رسالة الحب بالذكاء الاصطناعي",
      scrapbook: "ألبوم الصور",
      voice: "تسجيل صوتي",
      cake: "كعكة الاحتفال",
      delights: "حلوى فاخرة",
      customMemory: "تذكار ومساعد AI",
      giftBlast: "انفجار الهدايا المفاجئ",
      lastNote: "الرسالة الأخيرة",
      seal: "الختم والمشاركة",
    },
    tableWorkshop: {
      title: "طاولة التغليف اليدوية التفاعلية",
      subtitle: "انقر لإضافة العطور وقصاصات الورق الناعمة والأشرطة الحريرية",
      beddingTitle: "قصاصات الورق الناعمة (Bedding)",
      beddingSubtitle: "انثر قصاصات ورقية ملونة في قاع الصندوق",
      scatterBeddingBtn: "نثر قصاصات الورق",
      tagTitle: "بطاقة بالخط العربي وخيط حريري",
      tagSubtitle: "اربط بطاقة مكتوبة بخط اليد على شريط الهدية",
      stickersTitle: "ملصقات وأشرطة واشي",
      stickersSubtitle: "ألصق أختام ومزحات خاصة على الهدايا",
      aromaTitle: "العطر والأجواء الرومانسية",
      aromaSubtitle: "اختر الرائحة العطرية وبتلات الورد المتطايرة",
    },
    basics: {
      boxTitleLabel: "عنوان الصندوق التذكاري",
      boxTitlePlaceholder: "مثال: لحبيبي الأبدي — ذكرى سنوية رابعة",
      recipientLabel: "إلى من؟ (اسم المتلقي)",
      recipientPlaceholder: "مثال: مريم / سارة / ليلى",
      senderLabel: "اسمك (المرسل)",
      senderPlaceholder: "مثال: أحمد / عمر / خالد",
      occasionLabel: "المناسبة الخاصة",
      themeLabel: "لون الصندوق وشريط المخمل",
      passwordLabel: "الكلمة السرية (اختياري)",
      passwordPlaceholder: "مثال: ourfirstcoffee",
      passwordHintLabel: "تلميح الكلمة السرية",
      passwordHintPlaceholder: "مثال: المقهى الذي جلسنا فيه 4 ساعات في أول لقاء...",
      waxSealLabel: "الحروف الأولى لختم الشمع",
    },
    letter: {
      title: "رسالة روحية مكتوبة بخط اليد",
      aiHelperTitle: "مساعد كتابة رسائل الحب مع Gemini AI",
      aiHelperDesc: "حوّل ذكرياتكما إلى رسالة شعرية ومؤثرة جداً باللغة العربية",
      toneLabel: "النبرة والمشاعر",
      memoriesPromptLabel: "ذكريات خاصة وأسماء دلالية",
      memoriesPromptPlaceholder: "مثال: يوم المطر في المقهى، العشاء الأول معاً...",
      generateLetterBtn: "تأليف رسالة شاعرية مع Gemini AI",
      generatingLetter: "جاري صياغة كلمات من صميم القلب بالعربية...",
      letterTitlePlaceholder: "عنوان الرسالة (مثال: وعد أبدي إليك)",
      letterContentPlaceholder: "اكتب مشاعرك الصادقة هنا...",
      paperStyleLabel: "نمط الورق القديم",
    },
    scrapbook: {
      title: "ألبوم صور بولارويد التذكاري",
      subtitle: "صور مائلة مع أشرطة واشي وتواريخ وذكريات مكتوبة",
      addPhotoBtn: "إضافة صورة بولارويد",
      photoCaptionPlaceholder: "عبارة للصورة (مثال: اليوم الذي توقف فيه الزمن...)",
      photoDatePlaceholder: "التاريخ (مثال: 14 أكتوبر 2021)",
      photoNotePlaceholder: "القصة وراء هذه الصورة...",
      washiTapeLabel: "شريط واشي",
    },
    voice: {
      title: "تسجيل صوتي على شريط كاسيت عتيق",
      subtitle: "سجل صوتك الحقيقي مباشرة من المتصفح ليسمع نبضات قلبك",
      recordBtn: "بدء التسجيل الصوتي",
      stopBtn: "إيقاف وحفظ التسجيل",
      recording: "جاري التسجيل...",
      noteTitlePlaceholder: "عنوان التسجيل (مثال: همسة خاصة لك)",
      transcriptPlaceholder: "نص الرسالة المسموعة...",
    },
    delights: {
      title: "حلوى فاخرة ومزحات خاصة وكبسولة زمنية",
      subtitle: "شوكولاتة بلجيكية ومفاجآت تفتح في المستقبل",
      treatLabel: "اختيار الهدية اللذيذة",
      insideJokePlaceholder: "مزحة خاصة تظهر عند فتح الهدية",
      capsuleTitle: "كبسولة الزمن (قفل بتاريخ محدد)",
      capsuleDateLabel: "تاريخ فتح هذه الهدية",
      capsuleMessagePlaceholder: "رسالة سرية للمستقبل...",
    },
    customMemory: {
      customItemTitle: "تذكار خاص وشارة تذكارية",
      customItemPlaceholder: "اسم الغرض (مثال: كوب القهوة الأول لنا)",
      customItemTagPlaceholder: "وسم قصير",
      memoryBuddyTrainerTitle: "درّب رفيق الذكريات الذكي (Memory Buddy)",
      memoryBuddyTrainerSubtitle: "اكتب قصصكما ليتحدث الذكاء الاصطناعي بنفس ذكرياتكما",
      memoryInputPlaceholder: "أضف قصة، عادة لطيفة أو ذكرى...",
      addMemoryBtn: "إضافة ذكرى",
    },
    saveAndSealBtn: "ختم الصندوق بالشمع وإنشاء الرابط",
    savingBox: "جاري ختم وتجهيز الصندوق التذكاري...",
    cancelBtn: "إلغاء",
  },
  ja: {
    studioTitle: "記念ギフト制作アトリエ (Artisan Creator Studio)",
    studioSubtitle: "大切な人のために、心温まる手作りのデジタル宝石箱を作成しましょう",
    languageSelectLabel: "制作言語 (Crafting Language):",
    tabs: {
      workshop: "ラッピング台",
      basics: "基本と鍵",
      whySpecial: "特別な理由",
      vortexHeart: "3Dボルテックスハート",
      letter: "AIラブレター",
      scrapbook: "思い出アルバム",
      voice: "音声メッセージ",
      cake: "お祝いケーキ",
      delights: "お菓子とスイーツ",
      customMemory: "記念品とAI",
      giftBlast: "ギフトブラスト",
      lastNote: "最後の秘密の手紙",
      seal: "封印と共有",
    },
    tableWorkshop: {
      title: "体験型ギフトパッキングテーブル (Virtual Gift Table)",
      subtitle: "クリックして香り、クレープ紙の緩衝材、タグ、ステッカーを箱に詰めます",
      beddingTitle: "ふわふわの紙パッキン (Shredded Bedding)",
      beddingSubtitle: "箱の底に柔らかいカラーペーパーを敷き詰めます",
      scatterBeddingBtn: "紙パッキンを敷き詰める",
      tagTitle: "手書き風ギフトタグと紐 (Gift Tag)",
      tagSubtitle: "サテンリボンに手書きの名前タグを結びます",
      stickersTitle: "スタンプステッカーと和紙テープ",
      stickersSubtitle: "プレゼントに思い出のスタンプを貼ります",
      aromaTitle: "アロマの香りと雰囲気 (Aroma Mood)",
      aromaSubtitle: "箱の香りと舞い散る花びらを選びます",
    },
    basics: {
      boxTitleLabel: "ギフトボックスのタイトル",
      boxTitlePlaceholder: "例: 大切なあなたへ — 4周年の贈り物",
      recipientLabel: "相手のお名前 (宛名)",
      recipientPlaceholder: "例: 葵 / 結衣 / 蓮",
      senderLabel: "あなたのお名前 (送り主)",
      senderPlaceholder: "例: 翔太 / 陸 / 陽向",
      occasionLabel: "特別なお祝い事 (Occasion)",
      themeLabel: "箱のレザーとベルベットリボンの色",
      passwordLabel: "秘密の合言葉 (パスワード)",
      passwordPlaceholder: "例: ourfirstcoffee",
      passwordHintLabel: "合言葉のヒント (Hint)",
      passwordHintPlaceholder: "例: 初めて4時間話し込んだあのカフェ...",
      waxSealLabel: "シーリングワックスのイニシャル",
    },
    letter: {
      title: "手書き風羊皮紙の手紙 (Parchment Letter)",
      aiHelperTitle: "Gemini AI 手紙作成アシスタント",
      aiHelperDesc: "二人の思い出を日本語で心温まる感動的な手紙に仕上げます",
      toneLabel: "手紙のトーンと感情",
      memoriesPromptLabel: "手紙に入れたい思い出や愛称",
      memoriesPromptPlaceholder: "例: 雨の日のカフェ、焦がしてしまったパスタの思い出...",
      generateLetterBtn: "Gemini AIで手紙を作成する",
      generatingLetter: "日本語で心を込めた文章を執筆中...",
      letterTitlePlaceholder: "手紙のタイトル (例: あなたと出会えて)",
      letterContentPlaceholder: "心からの想いを書きましょう...",
      paperStyleLabel: "便箋のスタイル",
    },
    scrapbook: {
      title: "ポラロイド思い出アルバム (Scrapbook)",
      subtitle: "マスキングテープと手書きの日付で写真を飾ります",
      addPhotoBtn: "写真を追加する",
      photoCaptionPlaceholder: "写真のひと言 (例: 時間が止まったあの日...)",
      photoDatePlaceholder: "日付 (例: 2021年10月14日)",
      photoNotePlaceholder: "この写真のストーリー...",
      washiTapeLabel: "マスキングテープ",
    },
    voice: {
      title: "カセット風音声メッセージ (Voice Note)",
      subtitle: "ブラウザから本物の声を録音して届けましょう",
      recordBtn: "声を録音する",
      stopBtn: "停止して保存する",
      recording: "録音中...",
      noteTitlePlaceholder: "音声のタイトル (例: あなたへ贈る言葉)",
      transcriptPlaceholder: "メッセージの要約...",
    },
    delights: {
      title: "お菓子、内緒のジョーク、タイムカプセル",
      subtitle: "チョコレート、開けた時のサプライズ、未来に開く鍵付きカプセル",
      treatLabel: "お菓子の選択",
      insideJokePlaceholder: "開けた時にわかる内緒のジョーク",
      capsuleTitle: "タイムカプセル (日付ロック)",
      capsuleDateLabel: "いつ開けるか (未来の日付)",
      capsuleMessagePlaceholder: "未来の相手へのサプライズメッセージ...",
    },
    customMemory: {
      customItemTitle: "オリジナルの思い出バッジ (Custom Souvenir)",
      customItemPlaceholder: "アイテムの名前 (例: 初めてのコーヒーカップ)",
      customItemTagPlaceholder: "短いタグ",
      memoryBuddyTrainerTitle: "Memory Buddy AIに二人の思い出を教える",
      memoryBuddyTrainerSubtitle: "エピソードを入力すると、AIが二人だけの思い出を覚えます",
      memoryInputPlaceholder: "可愛い口癖や思い出のエピソード...",
      addMemoryBtn: "思い出を追加",
    },
    saveAndSealBtn: "ワックスで封印してリンクを作成",
    savingBox: "宝石箱を仕上げています...",
    cancelBtn: "キャンセル",
  },
};

